### ISSUE TITLE
Published Benchmark Results

### ISSUE THREAD

**Issue by cdiggins** [IFCjs/web-ifc#111]
It would be very helpful to see a list of benchmark results published automatically to this web-site as a table:

I would suggest the following fields:
* Input File Size
* Number of IFC Entities
* Total number of produced meshes
* Total number of polygons
* Processing Time
* Processing Success
* Error/Warning Count

**Comment by agviegas** [comment]
This issue is now a bounty. Whoever solves this will get $200. More information [here](https://bounties.ifcjs.io/).

**Comment by GuyOnsight** [comment]
May I try to take this and start working on it?

**Comment by agviegas** [comment]
It's yours @GuyOnsight!

**Comment by agviegas** [comment]
Hey @GuyOnsight we have just automated the bounty system. Can you please use the `::take` command? Just make a comment containing that command. Cheers!

**Comment by GuyOnsight** [comment]
::take command

Still in progress
@agviegas @amirmiz

**Comment by agviegas** [comment]
::take

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::take

Hi, @agviegas! Thanks for taking this bounty! The due date is August 31, 2022 UTC.

If you need to submit some pull requests (PR) to complete the tasks, make sure that the last and only the last PR has a title that either starts with the bounty ID or is exactly the same as the bounty name. After the PR is merged, this bounty’s status will automatically changed to done.

If you do not need to make a PR, tell the manager @agviegas to run `::done` command after your tasks is confirmed to be done.

Good luck!

**Comment by agviegas** [comment]
::drop

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::drop

Hi, @agviegas! Thanks for giving it a try! It’s now once again available for anyone to take.

**Comment by agviegas** [comment]
Can you please try again like I did @GuyOnsight ? Thanks!

**Comment by GuyOnsight** [comment]
::take

Thanks for the opportunity @agviegas 
We will try another bounty when it will be possible for us

@amirmiz

**Comment by agviegas** [comment]
Hey @GuyOnsight the comment can only contain the `::take` command, like I did. Can you please try again? Thanks a lot for your help!

**Comment by TxTony** [comment]
Hi just to recap.
During the build process for a new version of web-ifc.  We have to run a script locally  and this script will write the results into a table ( see exemple below ).

Question : the table is injected in the readme or it should be in another file named benchmark.md ?

| filename  |  Input file size |  IFCEntities quantity |  Total number of produced mesh  |  Total number of polygons | Processing Time | Error/Warning Count |
|---|---|---|---|---|---|---|
| duplex-apartment.ifc  | xxx Mo  |  xxxxxxxxxxx  | xxxxxxxxxxx  | xxxxxxxxxx | 2000 ms |  0  |
| test.ifc  | xx Mo  |  xxxxxxxxx  | xxxxxxxxx  | xxxxxxxx | 1000 ms |  0  |

thanks @agviegas

**Comment by arunkvijay** [comment]
::take

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::take

Hi, @arunkvijay! Thanks for taking this bounty! The due date is October 7, 2022 UTC.

If you need to submit some pull requests (PR) to complete the tasks, make sure that the last and only the last PR has a title that either starts with the bounty ID or is exactly the same as the bounty name. After the PR is merged, this bounty’s status will automatically changed to done.

If you do not need to make a PR, tell the manager @agviegas to run `::done` command after your tasks is confirmed to be done.

Good luck!

**Comment by arunkvijay** [comment]
::drop

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::drop

Hi, @arunkvijay! Thanks for giving it a try! It’s now once again available for anyone to take.

**Comment by TxTony** [comment]
::take

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::take

Hi, @TxTony! Thanks for taking this bounty! The due date is October 26, 2022 UTC.

If you need to submit some pull requests (PR) to complete the tasks, make sure that the last and only the last PR has a title that either starts with the bounty ID or is exactly the same as the bounty name. After the PR is merged, this bounty’s status will automatically changed to done.

If you do not need to make a PR, tell the manager @agviegas to run `::done` command after your tasks is confirmed to be done.

Good luck!

**Comment by TxTony** [comment]
::extend

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::extend

Hi, @TxTony! The due date is successfully extended by 21 days to November 16, 2022 UTC.

**Comment by TxTony** [comment]
Hi @agviegas  this is a first draft. I just need to add more ifc files and refactor some methods.
the file is written on web-ifc root folder, so you will just have to add a link in the readme.md to benchmark.md. :relaxed:
 i just noticed the date and the web-ifc version is missing, i will add them under system information section

# System informations 
 {"gpu":"","cpuName":"Intel(R) Core(TM) i7-3630QM CPU @ 2.40GHz","freeRam":1135.95703125,"totalRam":8088.74609375}
 _________ 
| filename | fileSize | timeTakenToOpenModel | timeSuccess | numberOfIfcEntities | totalNumberOfProducedMesh | totalNumberOfGeometries | totalNumberOfErrors | 
|-------|------|-------|-------|-------|-------|-------|-------| 
| ifcfiles\example.ifc | 0.4 | 19 | 46 | 6487 | 115 | 119 | 0 |

**Comment by agviegas** [comment]
Hey @TxTony thanks a lot! We'll review this and let you know 🙏

**Comment by agviegas** [comment]
### 🔴🔴🔴

Hi, @TxTony! The date is past due, your assignment has been revoked. It’s now available for anyone to take.

**Comment by TxTony** [comment]
::take

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::take

Hi, @TxTony! Thanks for taking this bounty! The due date is December 8, 2022 UTC.

If you need to submit some pull requests (PR) to complete the tasks, make sure that the last and only the last PR has a title that either starts with the bounty ID or is exactly the same as the bounty name. After the PR is merged, this bounty’s status will automatically changed to done.

If you do not need to make a PR, tell the manager @agviegas to run `::done` command after your tasks is confirmed to be done.

Good luck!

**Comment by TxTony** [comment]
Hi @agviegas do you have one large ifc file i ran with one file of 2.5Mo and one with 12.Mo if you got a file of 60Mo or higher that could be integrated in the benchmark loop. 

thanks

**Comment by agviegas** [comment]
Hey @TxTony did you check [this](https://github.com/IFCjs/test-ifc-files) out?

**Comment by TxTony** [comment]
Hi @agviegas ok i'll grab some of them i publish the update tonight or tomorrow. thanks

**Comment by agviegas** [comment]
### 🔴🔴🔴

Hi, @TxTony! The date is past due, your assignment has been revoked. It’s now available for anyone to take.

**Comment by TxTony** [comment]
@agviegas @QuimMoya  Hi guys, after validating this PR https://github.com/IFCjs/web-ifc/pull/288 could you change the status of this issue to done 

thanks

**Comment by agviegas** [comment]
@TxTony take it again and I'll mark this as done! Thanks a lot :)

**Comment by TxTony** [comment]
::take

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::take

Hi, @TxTony! Thanks for taking this bounty! The due date is January 14, 2023 UTC.

If you need to submit some pull requests (PR) to complete the tasks, make sure that the last and only the last PR has a title that either starts with the bounty ID or is exactly the same as the bounty name. After the PR is merged, this bounty’s status will automatically changed to done.

If you do not need to make a PR, tell the manager @agviegas to run `::done` command after your tasks is confirmed to be done.

Good luck!

**Comment by TxTony** [comment]
@agviegas Hi i forgot to notice you it's taken ( you can set status to done ) happy new year to you and your team ;)

**Comment by agviegas** [comment]
::done

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::done

Hi, @TxTony! Thanks for your contributions! Please submit an expense to IFC.js Open Collective. Then, tell us the invoice number via the `::expense::_____` command (replace the `_____` with the invoice number).

**Comment by TxTony** [comment]
::expense::118787

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::expense::118787

Hi, @TxTony! Thanks for the confirmation! We’ll proceed to review the expense. Once it’s approved, the payment will be scheduled.

**Comment by agviegas** [comment]
### 🟢🟢🟢

Hi, @TxTony! Your [expense](https://opencollective.com/ifcjs/expenses/118787) has been approved!

**Comment by agviegas** [comment]
### 🎉🎉🎉

Hi, @TxTony! Thanks for your contributions! The reward of this bounty has been transferred to your Open Collective account.
