### ISSUE TITLE
Some pipe geometries not displayed 

### ISSUE THREAD

**Issue by favreau84** [IFCjs/web-ifc#121]
Open this model : [VE_RT1801-EQ-D-FC-150_AIR_PRIMAIRE_V2.ifc.zip](https://github.com/tomvandig/web-ifc/files/7722753/VE_RT1801-EQ-D-FC-150_AIR_PRIMAIRE_V2.ifc.zip)

Some pipes geometries are not displayed. Here the expected result

![model](https://user-images.githubusercontent.com/18169247/146266362-d13b8d5f-18c9-4dec-9319-6bbb398715ec.png)

**Comment by dlabz** [comment]
More examples of the same issue.
https://drive.google.com/file/d/1A1f6MvuzzV2cJ0pvbN1qiDVcDx6tCXue/view?usp=sharing

**Comment by agviegas** [comment]
This issue is now a bounty. Whoever solves this will get $100. More information [here](https://bounties.ifcjs.io/).

**Comment by dlabz** [comment]
same as #21

**Comment by QuimMoya** [comment]
Ok problem solved
![image](https://user-images.githubusercontent.com/12625508/182830693-72dd3c39-7c59-43c2-a13f-12fe0f4c51a7.png)
