### ISSUE TITLE
Advanced BREP support

### ISSUE THREAD

**Issue by jonas32** [IFCjs/web-ifc#125]
Here is the output log of the viewers dev console (related to discussion in #123)

https://pastebin.com/FQAxwZ2h

**Comment by tomvandig** [comment]
Hi, these are advanced BREPs

I've currently not even considered implementing these, its quite advanced stuff.

I will reconsider this if more people request these entities, and leave the issue open.

**Comment by dlabz** [comment]
Might be a good idea to return the raw IFC data for unsupported types, as there are number of libraries that could be used to generate geometry.

https://github.com/donalffons/opencascade.js/
https://polyscope.run/

**Comment by tomvandig** [comment]
A user is free to request the individual IFC lines, or to recursively request those lines, this is possible in the current api. See https://github.com/tomvandig/web-ifc/blob/fe50ba5dbd654f24b782fc147e177e96279494ab/examples/usage/src/properties.ts#L8

**Comment by agviegas** [comment]
This issue is now a bounty. Whoever solves this will get $500. More information [here](https://bounties.ifcjs.io/).

**Comment by QuimMoya** [comment]
This issue is related to #156 and we are solving #156

**Comment by agviegas** [comment]
Merged with the other advanced breps bounties!

**Comment by QuimMoya** [comment]
In APOGEA we are solving this issue, along with user Dlabz.

**Comment by agviegas** [comment]
::take

**Comment by agviegas** [comment]
::take
