### ISSUE TITLE
IFC with no materials fails to load

### ISSUE THREAD

**Issue by simon-gd** [IFCjs/web-ifc#137]
A simple IFC file that doesn't have properties or materials doesn't load. Since it seems to open fine in BIM Vision, I assume that the IFC is ok, but not 100% sure. Might be worth investigation
<img width="1587" alt="Screenshot 2021-11-30 09 51 34" src="https://user-images.githubusercontent.com/57882634/144072114-e88a1d22-3707-4873-803c-0628e89ab81d.png">

This zip contains two version of the model, the original (slightly larger) and a smaller one that was run through  Solibri IFC Optimizer (I was hoping that would fix any IFC issues the file might have, but it didn't.

[very_simple.zip](https://github.com/tomvandig/web-ifc/files/7925983/very_simple.zip)

 [Issue moved from web-ifc-three to here](https://github.com/IFCjs/web-ifc-three/issues/71)

**Comment by agviegas** [comment]
This issue is now a bounty. Whoever solves this will get $100. More information [here](https://bounties.ifcjs.io/).

**Comment by QuimMoya** [comment]
Hi, the problem is that the IFC does not contain any IFCSHAPEREPRESENTATION with the identifier "Body", so IFC.JS does not construct any geometry. 
-> #82=IFCSHAPEREPRESENTATION(#13,**'Facetation'**,'SurfaceModel',(#81));

If you replace "Facetation" by "Body" IFC.JS will read this geometry

Is it solved?

**Comment by QuimMoya** [comment]
![image](https://user-images.githubusercontent.com/12625508/172675217-02373416-f069-4a33-ae63-11e85af8305b.png)
By changing all 'Facetation' by 'Body' you obtain this
