### ISSUE TITLE
Some objects are wrongly placed

### ISSUE THREAD

**Issue by clement-procal** [IFCjs/web-ifc#162]
Hello, I tried to import an Ifc file, and I noticed that there are some issue with some objects position. I can't really fix this by myself, so I hope that somebody can have a look :)
IFCjs:
![Capture d’écran 2022-05-11 105420](https://user-images.githubusercontent.com/92861638/167813248-e012828b-fca4-43c5-86f5-f4b5ce4e3712.png)
Expected:
![Capture d’écran 2022-05-11 105444](https://user-images.githubusercontent.com/92861638/167813250-7a418cad-6346-46ef-9a7f-2fa028b731da.png)

By the way, the IFCSITE is not drawn, I don't if that is on purpose, or if that is an issue.

Here is the ifc file I used for this test:
[FZK-Haus-EliteCAD.zip](https://github.com/IFCjs/web-ifc-three/files/8668427/FZK-Haus-EliteCAD.zip)

Thanks!

**Comment by agviegas** [comment]
::take

**Comment by agviegas** [comment]
::take

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::take

Hi, @agviegas! Thanks for taking this bounty! The due date is October 28, 2022 UTC.

If you need to submit some pull requests (PR) to complete the tasks, make sure that the last and only the last PR has a title that either starts with the bounty ID or is exactly the same as the bounty name. After the PR is merged, this bounty’s status will automatically changed to done.

If you do not need to make a PR, tell the manager @agviegas to run `::done` command after your tasks is confirmed to be done.

Good luck!

**Comment by agviegas** [comment]
::drop

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::drop

Hi, @agviegas! Thanks for giving it a try! It’s now once again available for anyone to take.

**Comment by agviegas** [comment]
::take

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::take

Hi, @agviegas! Thanks for taking this bounty! The due date is November 14, 2022 UTC.

If you need to submit some pull requests (PR) to complete the tasks, make sure that the last and only the last PR has a title that either starts with the bounty ID or is exactly the same as the bounty name. After the PR is merged, this bounty’s status will automatically changed to done.

If you do not need to make a PR, tell the manager @agviegas to run `::done` command after your tasks is confirmed to be done.

Good luck!

**Comment by agviegas** [comment]
::done

**Comment by agviegas** [comment]
::done

**Comment by agviegas** [comment]
### 🔴🔴🔴

Hi, @agviegas! The date is past due, your assignment has been revoked. It’s now available for anyone to take.

**Comment by QuimMoya** [comment]
Solved in the next release
![image](https://user-images.githubusercontent.com/12625508/218727294-a31af373-2c1b-4842-8b87-74a7bb042ecb.png)
