### ISSUE TITLE
Add support for IfcSurfaceCurveSweptAreaSolid 

### ISSUE THREAD

**Issue by brunopostle** [IFCjs/web-ifc#171]
IFC.js doesn't render IfcSurfaceCurveSweptAreaSolid geometry. See discussion here: https://twitter.com/topologicBIM/status/1529736071076106241?t=c0qRyBK2FVaiX597unteJg&s=19

**Comment by agviegas** [comment]
Hey @brunopostle can you please provide the model? Cheers!

**Comment by brunopostle** [comment]
Here's a model with seven IfcSurfaceCurveSweptAreaSolid representation items, it has both closed and open-ended directrixes. The reference surfaces are simple planes, so this isn't the worst case.

[IfcSurfaceCurveSweptAreaSolid.ifc.txt](https://github.com/IFCjs/web-ifc/files/9290175/IfcSurfaceCurveSweptAreaSolid.ifc.txt)

It should look something like this:

![Screenshot from 2022-08-09 13-46-22](https://user-images.githubusercontent.com/1747315/183642962-2202ac61-dea3-4fce-bfef-1405d0a35dc2.png)

**Comment by aka-blackboots** [comment]
::take

**Comment by aka-blackboots** [comment]
::drop

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::drop

Hi, @aka-blackboots! Thanks for giving it a try! It’s now once again available for anyone to take.

**Comment by QuimMoya** [comment]
Improvement
![image](https://user-images.githubusercontent.com/12625508/201324627-99f01dce-f20c-4db6-bbcb-3d29192b36da.png)

**Comment by QuimMoya** [comment]
I think now it's working
![image](https://user-images.githubusercontent.com/12625508/201636680-56f9bdb8-e1d7-40b8-b879-6bd1e9acf666.png)

**Comment by QuimMoya** [comment]
This issue is solved
