### ISSUE TITLE
Wrong flat transformation for certain meshes

### ISSUE THREAD

**Issue by hellghostx** [IFCjs/web-ifc#173]
For a certain meshes with expressId: 
![WrongFlatTransformation](https://user-images.githubusercontent.com/26725817/170997543-58839f0a-5d08-4d22-b06f-aa05afcd8397.png)
 
there is a wrong flat transformation, which results in the wrong vertex positions, which results in wrong bounding box. Since the whole model is translated towards positions with enourmous units and this wrong flat transformation is based around origin, the bounding box makes whole scene unworkable. Basically for those meshes, the outcome is that all those meshes are above each other in vertical axis, instead of on different places of the given model.
 
![WrongMeshes](https://user-images.githubusercontent.com/26725817/170999588-65c37ebe-a9ca-40c8-b977-3537d9cc664d.png)
 
 Open IFC Viewer can visualise it correctly:
 
![OpenViewer](https://user-images.githubusercontent.com/26725817/171000041-ddadd8d3-27c9-4485-8f23-6b8e6f1a288c.png)

**Comment by aka-blackboots** [comment]
::take

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::take

Hi, @aka-blackboots! Thanks for taking this bounty! The due date is October 31, 2022 UTC.

If you need to submit some pull requests (PR) to complete the tasks, make sure that the last and only the last PR has a title that either starts with the bounty ID or is exactly the same as the bounty name. After the PR is merged, this bounty’s status will automatically changed to done.

If you do not need to make a PR, tell the manager @agviegas to run `::done` command after your tasks is confirmed to be done.

Good luck!

**Comment by aka-blackboots** [comment]
::drop

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::drop

Hi, @aka-blackboots! Thanks for giving it a try! It’s now once again available for anyone to take.

**Comment by beachtom** [comment]
@hellghostx I am trying to triage any still open issues? can you confirm if this is still an issue - and if it is possible share a model?

**Comment by beachtom** [comment]
No response, so assuming this is fixed (no model attach for us to test)

**Comment by hellghostx** [comment]
Sorry for late answer - it seems to be fixed with current version of web-ifc
