### ISSUE TITLE
Wrong bool operation result

### ISSUE THREAD

**Issue by deadman2000** [IFCjs/web-ifc#191]
Xbim:
![изображение](https://user-images.githubusercontent.com/12889180/175961626-84646075-31dd-4e58-a6cc-5c333b1315b9.png)

Xeokit:
![изображение](https://user-images.githubusercontent.com/12889180/175961579-62000257-1f2d-44e3-baac-117a40e7f79e.png)

model:
[bad_wall.zip](https://github.com/tomvandig/web-ifc/files/8992716/bad_wall.zip)

**Comment by deadman2000** [comment]
I used fast bools. Settings: `{USE_FAST_BOOLS: true}`

**Comment by agviegas** [comment]
Solved! You can try [here](https://ifcjs.github.io/web-ifc/examples/viewer/index.html). 
![image](https://user-images.githubusercontent.com/56475338/183528050-4611da6b-a8db-429d-b69f-912f4531ccef.png)
