### ISSUE TITLE
IFCSURFACEOFREVOLUTION support

### ISSUE THREAD

**Issue by deadman2000** [IFCjs/web-ifc#192]
Open IFC Viewer:
![изображение](https://user-images.githubusercontent.com/12889180/175971955-e8998018-ed36-4f6a-9d13-0ce255273b5b.png)

model:
[IFCSURFACEOFREVOLUTION.zip](https://github.com/tomvandig/web-ifc/files/8993109/IFCSURFACEOFREVOLUTION.zip)

**Comment by QuimMoya** [comment]
I think that advanced breps have solved this issue
![image](https://user-images.githubusercontent.com/12625508/182776820-af618928-05c8-4ce4-8000-f95a92a1ee86.png)
