### ISSUE TITLE
Shape not created in IFC4 format

### ISSUE THREAD

**Issue by vulpes1399** [IFCjs/web-ifc#195]
When FILE_SCHEMA is IFC4, IFCCIRCLE may not be properly output.

three : 0.134.0
web-ifc-viewer": 1.0.103

In this version, IFCCIRCLE is not created with the following message
=> degenerate polygon in extrude

And the IFCCIRCLE is not created with the following message, either downloading the code from Git or from Demo.

=> main.js:9913 THREE.BufferGeometry.computeBoundingSphere(): Computed radius is NaN. The "position" attribute is likely to have NaN values. 

Please, I need your help

**Comment by QuimMoya** [comment]
Can you post the IFC file?

**Comment by aka-blackboots** [comment]
@QuimMoya, did you receive the IFC file for this or were you able to recreate the issue?

**Comment by beachtom** [comment]
@vulpes1399  I am trying to triage any still open issues? can you confirm if this is still an issue - and if it is possible share a model?

**Comment by beachtom** [comment]
No response (no model). From my testing I believe this is now fixed.
