### ISSUE TITLE
Native IFC support and three-way merging

### ISSUE THREAD

**Issue by brunopostle** [IFCjs/web-ifc#197]
I raised a question on the discord channel, basically does IFC.js support Native IFC as implemented in blenderbim? Amongst other things, Native IFC allows three-way merging and a modern git fork, branch, pull-request, merge workflow with BIM data.

Here is a Native IFC definition discussion: IfcOpenShell/IfcOpenShell#2240

A good place to start would be to use IFC.js to modify (delete, change or add entities) one of the scratch IFC files in the ifcmerge repository, and generate a pull-request. I can then try and merge this with a local branch and see if it works: https://github.com/brunopostle/ifcmerge

**Comment by beachtom** [comment]
So from my tests this is now how our IFC writing works - please let me know if we are still non compliant in some way.
