### ISSUE TITLE
Elalish/Manifold library fails in some models.

### ISSUE THREAD

**Issue by QuimMoya** [IFCjs/web-ifc#209]
When disabling FAST_BOOLS many models fail to load. The error message could vary, but is something like this:
![image](https://user-images.githubusercontent.com/12625508/184292251-2bb43a5d-d3fa-4b0c-bbde-493178d9162a.png)
or this
![image](https://user-images.githubusercontent.com/12625508/184292481-4137ecf3-5c56-4e9f-a8c7-909c02d2a94a.png)

testing files:
[S_Office_Integrated Design Archi.zip](https://github.com/IFCjs/web-ifc/files/9313960/S_Office_Integrated.Design.Archi.zip)
[15.zip](https://github.com/IFCjs/web-ifc/files/9313965/15.zip)

**Comment by prideout** [comment]
Possibly related to https://github.com/IFCjs/web-ifc/issues/216
