### ISSUE TITLE
IFC file doesnt load correctly

### ISSUE THREAD

**Issue by MauroLemmens** [IFCjs/web-ifc#21]
When I open a IFC file into the model loader it shows like this:
![afbeelding](https://user-images.githubusercontent.com/67467107/115032233-6250a700-9ec9-11eb-9f1c-01314a6e95c9.png)

and it should look like this:
![afbeelding](https://user-images.githubusercontent.com/67467107/115032252-68468800-9ec9-11eb-8d58-85749148e406.png)

What can I do to let it load correctly?

**Comment by agviegas** [comment]
Hey, can you provide link to the file to check it?

**Comment by MenderBlender** [comment]
IFC file: [miniproject.zip](https://github.com/tomvandig/web-ifc/files/6331204/miniproject.zip)
Thanks for helping!

**Comment by MenderBlender** [comment]
Hey, did you find what the problem is? I tried different IFC files and they also have missing parts.

**Comment by agviegas** [comment]
Hey, I've managed to reproduce it on my end, so we'll correct it eventually. As you know, this is not a finished library. We're investing all the time we have in moving forward, but I can't tell you when we'll be able to have this problem solved. Don't think we've ignored this issue, but it's not the only thing on the todo list!

**Comment by vegarringdal** [comment]
Tried it with version 0.19
This is the error messages

![image](https://user-images.githubusercontent.com/2901416/121067514-70d18580-c7cb-11eb-95aa-21ff9a44b8c3.png)

**Comment by tomvandig** [comment]
Update for v 0.0.20

![image](https://user-images.githubusercontent.com/49716596/122680818-88f4cc00-d1f1-11eb-986c-b423fcd124ec.png)

Some entities still unimplemented.

**Comment by agviegas** [comment]
This issue is now a bounty. Whoever solves this will get $100. More information [here](https://bounties.ifcjs.io/).

**Comment by dlabz** [comment]
Solved! At least for @MenderBlender ...

The bug was caused by a [change between IFC2x3 and IFC4](https://standards.buildingsmart.org/IFC/DEV/IFC4_3/RC1/HTML/schema/ifcgeometryresource/lexical/ifccompositecurve.htm) for type property `SelfIntersect` in `IfcCompositeCurve`  which used to be `LOGICAL` (`.T.`) and is changed to `IfcLogical` (`IFCLOGICAL(.T.)`).  

For file to load without error, the following lines in the attached IFC file `Mini Project.ifc`:
```
#1259= IFCCOMPOSITECURVE((#1225,#1229,#1235,#1239,#1244,#1248,#1254,#1258),.T.);
#1607= IFCCOMPOSITECURVE((#1225,#1580,#1585,#1589,#1594,#1598,#1603,#1606),.T.);
```

need to be changed to, respectively: 
```
#1259= IFCCOMPOSITECURVE((#1225,#1229,#1235,#1239,#1244,#1248,#1254,#1258),IFCLOGICAL(.T.));
#1607= IFCCOMPOSITECURVE((#1225,#1580,#1585,#1589,#1594,#1598,#1603,#1606),IFCLOGICAL(.T.));
```

I'm guessing this is far from only instance of this issue, as IFC4 also introduces `IfcBoolean` replacing **SOME INSTANCES** of `BOOLEAN`. 

@tomvandig I'm guessing there are other cases where IFC2x3 differs from IFC4 to refer to, before I reinvent the wheel?

**Comment by agviegas** [comment]
@dlabz great! Can you create a PR?

**Comment by agviegas** [comment]
Hey @dlabz if you don't create a PR or give a specific estimated date, we'll open the issue again! Cheers 🙂

**Comment by dlabz** [comment]
I got in to AdvencedBREP issue with @QuimMoya, and we lost three days on a bug, so probably won’t be able to cleanup the PR before the weekend.  

If someone else is interested in this task, feel free to delegate. 

I’ll focus on finishing IfcBSplineWithKnots and IfcRationalBSplineWithKnots.

**Comment by agviegas** [comment]
@dlabz ok! Could you please specify an estimated date for this one? Cheers!

**Comment by dlabz** [comment]
I’m tempted to say tomorrow, but don’t want to jinx it. We’ve had some
really bad luck with code compiling without errors, yet wasm throwing
promise rejection on startup, and one git clash messing everything up, so
this the third time we’re reintroducing changes one by one… fingers
crossed….

Neither of us have any experience with both wasm and c++, and it takes a
serpentine to climb the curve, if you know what I mean.

Most of it is done, but some instances of IfcRationalBezireSurfaceWithKnots
are off. Let’s touch base on Monday.
