### ISSUE TITLE
Unexpected style type message when loading model

### ISSUE THREAD

**Issue by Nevernat** [IFCjs/web-ifc#211]
Loading IFC files with the ifc.js library i often get many messages like this in console:
```
Unexpected style type: 3800577675 at 213152 (web-ifc-api.js: 933)
Unexpected style type: 3800577675 at 213511 (web-ifc-api.js: 933)
...
```
What are they due to? 
Is it possible to prevent them from appearing?

**Comment by Nevernat** [comment]
The file is here:
[301110Nem-FZK-Haus-2x3.ifc](https://github.com/Nevernat/IFC-examples/blob/main/301110Nem-FZK-Haus-2x3.ifc)
I found the example on web.

Same error for the THREE.js example: 
[THREE.js example](https://github.com/mrdoob/three.js/tree/dev/examples/models/ifc)

PS: in my case the warning appears using ifc.js integrated in THREE.js (r143)

**Comment by beachtom** [comment]
This style is now supported

**Comment by danielazaffalon** [comment]
I keep getting the same error but sometimes I can see the model even with the error, but other times, I can't see the model but I just get this error.

**Comment by beachtom** [comment]
Hi can you confirm you are using the latest version? If not can provide a screenshot and the model
