### ISSUE TITLE
REAL numbers written by ExportFileAsIFC() are in an invalid format

### ISSUE THREAD

**Issue by brunopostle** [IFCjs/web-ifc#214]
Files created using ExportFileAsIFC() have invalid real numbers, validation of a file generated by the `hello-world/examples/web-ifc-three/editing/` tool gives lots of errors like this:

```
$ python -m ifcopenshell.validate ~/Downloads/modified.ifc
For instance:
    #6=IfcCartesianPoint((0,0,0))
                         ^^^^^^^ 
With attribute:
    <type IfcLengthMeasure: <real>>
Value:
    0
Not valid
```

Here is how [IfcOpenShell writes reals](https://github.com/IfcOpenShell/IfcOpenShell/blob/de6b578d9c1752c55f74afee6970d05015f2dfe7/src/ifcparse/IfcWrite.cpp#L71)

Basically, whole number real numbers need to be written with a trailing '.', like so:

    #6=IfcCartesianPoint((0.,0.,0.));

..and exponents need to be written with a 'E' not 'e', i.e. this:

    #13=IFCGEOMETRICREPRESENTATIONCONTEXT($,'Model',3,1.000000000000001e-05,#12,$);

should be:

    #13=IFCGEOMETRICREPRESENTATIONCONTEXT($,'Model',3,1.000000000000001E-05,#12,$);

**Comment by brunopostle** [comment]
Another error in the exported file, the FILE_NAME header should have 7 attributes not 5, i.e this is invalid:

    FILE_NAME('no name', '', (''), (''), 'web-ifc-export');

See diagnosis in IfcOpenShell/IfcOpenShell#2358

**Comment by aka-blackboots** [comment]
::take

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::take

Hi, @aka-blackboots! Thanks for taking this bounty! The due date is November 1, 2022 UTC.

If you need to submit some pull requests (PR) to complete the tasks, make sure that the last and only the last PR has a title that either starts with the bounty ID or is exactly the same as the bounty name. After the PR is merged, this bounty’s status will automatically changed to done.

If you do not need to make a PR, tell the manager @agviegas to run `::done` command after your tasks is confirmed to be done.

Good luck!

**Comment by aka-blackboots** [comment]
::drop

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::drop

Hi, @aka-blackboots! Thanks for giving it a try! It’s now once again available for anyone to take.

**Comment by Mivit** [comment]
::take

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::take

Hi, @Mivit! Thanks for taking this bounty! The due date is November 17, 2022 UTC.

If you need to submit some pull requests (PR) to complete the tasks, make sure that the last and only the last PR has a title that either starts with the bounty ID or is exactly the same as the bounty name. After the PR is merged, this bounty’s status will automatically changed to done.

If you do not need to make a PR, tell the manager @agviegas to run `::done` command after your tasks is confirmed to be done.

Good luck!

**Comment by Mivit** [comment]
::done

**Comment by agviegas** [comment]
::done

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::done

Hi, @Mivit! Thanks for your contributions! Please submit an expense to IFC.js Open Collective. Then, tell us the invoice number via the `::expense::_____` command (replace the `_____` with the invoice number).

**Comment by Mivit** [comment]
::expense::105043

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::expense::105043

Hi, @Mivit! Thanks for the confirmation! We’ll proceed to review the expense. Once it’s approved, the payment will be scheduled.

**Comment by agviegas** [comment]
### 🟢🟢🟢

Hi, @Mivit! Your [expense](https://opencollective.com/ifcjs/expenses/105043) has been approved!

**Comment by agviegas** [comment]
### 🟢🟢🟢

Hi, @Mivit! Your [expense](https://opencollective.com/ifcjs/expenses/105043) has been approved!

**Comment by beachtom** [comment]
This is now fixed
