### ISSUE TITLE
!!! Please help !!! - Web-IFC load file to objects form - Diagramm

### ISSUE THREAD

**Issue by mysterieux30** [IFCjs/web-ifc#215]
Hello, Please, is there any good explained Diagramm or Schema that could allow me to understand the meaning of every attribute in every object, and if any further necessary information to know exactly how I could interact with all these objects? There are some attributes in the objects extracted from the WASM that doesn't even exist in the IFC format (Example in the picture: 1 "IfcPropertySingleValue"  in "HasProperties" of an "IfcPropertySet", there are two objects as attributes "Name" and "NominalValue"; they both have an attribute "Type", and "NominalValue" has an attribute "valueType" too, and all these attributes don't even exist in the IFC structure.[THEY ARE HIGHLIGHTED IN THE PICTURE])

P.S:
"Name" matches IfcIdentifier in the IFC Schema.
"NominalValue" matches Ifcvalue in the IFC Schema.

Thanks.

![a-1](https://user-images.githubusercontent.com/55838562/186241860-d8d8b211-24a5-46e9-a718-f2ed5498e302.png)
s

**Comment by Moult** [comment]
You can browse the IFC docs here: http://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/lexical/IfcPropertySingleValue.htm

As you can see, the Name and NominalValue are attributes of the IfcPropertySingleValue class.

**Comment by beachtom** [comment]
I thin this has been answered so I am going to close it
