### ISSUE TITLE
unable open larger ifc file (~50mb)

### ISSUE THREAD

**Issue by lukyrys** [IFCjs/web-ifc#216]
Hello, i have problem with opening larger ifc file. IFC file is about 50mb and tried on demo page https://ifcjs.github.io/web-ifc/examples/viewer/index.html

Output from browser console
```
Reading took 0 ms [web-ifc-viewer.js:215998:11](https://ifcjs.github.io/web-ifc/examples/viewer/web-ifc-viewer.js)
Opening model took 2037 ms [web-ifc-viewer.js:216005:11](https://ifcjs.github.io/web-ifc/examples/viewer/web-ifc-viewer.js)
unexpected style type 9 [web-ifc-viewer.js:7697:16](https://ifcjs.github.io/web-ifc/examples/viewer/web-ifc-viewer.js)
zero trizero trizero trizero trizero trizero trizero trizero trizero trizero trizero trizero trizero trizero trizero trizero trizero trizero triunexpected style type [web-ifc-viewer.js:7697:16](https://ifcjs.github.io/web-ifc/examples/viewer/web-ifc-viewer.js)
unexpected style type 85 [web-ifc-viewer.js:7697:16](https://ifcjs.github.io/web-ifc/examples/viewer/web-ifc-viewer.js)
Error in file: C:\Users\Makc\4ifc\manifold\manifold\src\impl.cpp (298): 'IsManifold()' is false: Input mesh is not manifold! [web-ifc-viewer.js:7697:16](https://ifcjs.github.io/web-ifc/examples/viewer/web-ifc-viewer.js)
zero trizero triError in file: C:\Users\Makc\4ifc\manifold\manifold\src\impl.cpp (298): 'IsManifold()' is false: Input mesh is not manifold! [web-ifc-viewer.js:7697:16](https://ifcjs.github.io/web-ifc/examples/viewer/web-ifc-viewer.js)
Error in file: C:\Users\Makc\4ifc\manifold\manifold\src\impl.cpp (298): 'IsManifold()' is false: Input mesh is not manifold! [web-ifc-viewer.js:7697:16](https://ifcjs.github.io/web-ifc/examples/viewer/web-ifc-viewer.js)
Uncaught 39480680
```

**Comment by brutestack** [comment]
I have the same issue when using web-ifc-three v0.0.121 and web-ifc v0.0.36 with 19 Mb model
![image](https://user-images.githubusercontent.com/2864137/195984390-b7bd027b-f0e3-43e6-a664-a74d6ef7d8be.png)

**Comment by vulevukusej** [comment]
can confirm I'm also having this issue with web-ifc-three v0.0.122

**Comment by jespa007** [comment]
> can confirm I'm also having this issue with web-ifc-three v0.0.122

The issue here is related to `web-ifc` not `web-ifc-three`. AFAIK, `web-ifc-three` v0.0.122 installed from `npm` still uses web-ifc 0.36.0 but if you download code from github (i.e https://github.com/IFCjs/web-ifc-three) it uses the new version of web-ifc (i.e web-ifc 0.0.39)

**Comment by beachtom** [comment]
Hi - can you please send the error you get - those particular ones earlier in the thread are no longer in the code - so if you are seeing them it looks like an old version is introduced somewhere

**Comment by brutestack** [comment]
@beachtom @jespa007 
This issue is gone and everything works OK after update to web-ifc-three 0.0.122 and web-ifc 0.0.39.
However, NPM version of web-ifc-three 0.0.122 still uses web-ifc 0.0.36 where this issues still exists.

**Comment by beachtom** [comment]
OK - great.

I will close this then - if it reoccurs please feel to reopen
