### ISSUE TITLE
Ifc loader fails on load  http://www.solserver.it/casak/test.ifc

### ISSUE THREAD

**Issue by cubalibre** [IFCjs/web-ifc#217]
![Cattura2](https://user-images.githubusercontent.com/904508/189318053-c1532f20-4280-4d85-9da2-db935b4165ba.PNG)
I view a strange model if I load  [this ifc ]( http://www.solserver.it/casak/test.ifc ) with other viewers I see a correct model.

**Comment by cubalibre** [comment]
The corretc mode
![Cattura](https://user-images.githubusercontent.com/904508/189319437-9d173af1-3f04-46af-a5f6-e6e043724d27.PNG)

**Comment by QuimMoya** [comment]
I think this issue is solved
![image](https://user-images.githubusercontent.com/12625508/199689725-2298ba14-8d8e-4965-a6ee-26796097c35c.png)
