### ISSUE TITLE
Sample files for failed geometry conversion

### ISSUE THREAD

**Issue by andy-wrks** [IFCjs/web-ifc#219]
As discussed in the Discord today, I'm uploading some sample geometry that fails to convert in the current build.
For context: According to the discussion, this could be a regression issue related to the changes in handling boolean operations. But it could also be something else ;-)

![image](https://user-images.githubusercontent.com/111515188/191058448-25c51230-43b0-4c73-8d7f-cceec71f1a88.png)

All sample files are attached, the screenshots were taken from
https://ifcjs.github.io/web-ifc-viewer/example/index
but I had similar experiences when opening the files in our test-app.

Sample1 Output:
![image](https://user-images.githubusercontent.com/111515188/191079446-99517931-6d37-48a0-8704-36edde566725.png)

Sample1 Expected:
![image](https://user-images.githubusercontent.com/111515188/191079526-97cb8a0a-54d9-4800-a4e0-a622deec64f0.png)

Sample 2 Output:
[no image, all elements fail]

Sample 2 Expected:
![image](https://user-images.githubusercontent.com/111515188/191079788-2f3cd004-b64f-4b09-8554-3da747e3b27b.png)

Sample 3 Output:
![image](https://user-images.githubusercontent.com/111515188/191079955-b11f24cd-5865-4750-8921-1249f4666200.png)

Sample 3 Expected:
![image](https://user-images.githubusercontent.com/111515188/191080154-b0a350d8-b1e7-483c-918c-b802c813ef94.png)

[Samples.zip](https://github.com/IFCjs/web-ifc/files/9601159/Samples.zip)

**Comment by aka-blackboots** [comment]
::take

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::take

Hi, @aka-blackboots! Thanks for taking this bounty! The due date is November 4, 2022 UTC.

If you need to submit some pull requests (PR) to complete the tasks, make sure that the last and only the last PR has a title that either starts with the bounty ID or is exactly the same as the bounty name. After the PR is merged, this bounty’s status will automatically changed to done.

If you do not need to make a PR, tell the manager @agviegas to run `::done` command after your tasks is confirmed to be done.

Good luck!

**Comment by aka-blackboots** [comment]
::drop

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::drop

Hi, @aka-blackboots! Thanks for giving it a try! It’s now once again available for anyone to take.

**Comment by QuimMoya** [comment]
Sample 1 is working, seems that it became solved unexpectdely in a previous issue.

![image](https://user-images.githubusercontent.com/12625508/199927647-5e062de0-4193-4330-80a9-362e8eb3ee73.png)

**Comment by QuimMoya** [comment]
Working on sample 2... it seems that composite profiles where not implemented, i'm solving it.

**Comment by QuimMoya** [comment]
![image](https://user-images.githubusercontent.com/12625508/200273444-bb1e19e5-cb97-4a15-975b-8bb17f45b208.png)
Finally!!!... second example working

**Comment by QuimMoya** [comment]
Last commit solved many cases
Third example working !!
![image](https://user-images.githubusercontent.com/12625508/226830094-3897181c-0732-46d7-b5cc-4b6b1e343d4b.png)
![image](https://user-images.githubusercontent.com/12625508/226830248-f21557cb-f0ce-4bbb-b554-c8cac64fdf6e.png)
![image](https://user-images.githubusercontent.com/12625508/226830382-238bb43a-e35d-4db6-b6c6-7c2c3b99941d.png)
