### ISSUE TITLE
Bad transformation matrix size should throw an error

### ISSUE THREAD

**Issue by TxTony** [IFCjs/web-ifc#221]
This could be better to throw an error. 

https://github.com/IFCjs/web-ifc/blob/f68cee99b9e739937949097464d79ecf938a747c/src/web-ifc-api.ts#L335

https://github.com/IFCjs/web-ifc/blob/f68cee99b9e739937949097464d79ecf938a747c/src/web-ifc-api.ts#L281

**Comment by TxTony** [comment]
::take

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::take

Hi, @TxTony! Thanks for taking this bounty! The due date is November 5, 2022 UTC.

If you need to submit some pull requests (PR) to complete the tasks, make sure that the last and only the last PR has a title that either starts with the bounty ID or is exactly the same as the bounty name. After the PR is merged, this bounty’s status will automatically changed to done.

If you do not need to make a PR, tell the manager @agviegas to run `::done` command after your tasks is confirmed to be done.

Good luck!

**Comment by agviegas** [comment]
::done

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::done

Hi, @TxTony! Thanks for your contributions! Please submit an expense to IFC.js Open Collective. Then, tell us the invoice number via the `::expense::_____` command (replace the `_____` with the invoice number).
