### ISSUE TITLE
Problem with rendering an extruded geometry with a profile in x,z

### ISSUE THREAD

**Issue by Danimolonmon** [IFCjs/web-ifc#223]
It seems that when creating a profile to extrude with the coordinates on the axis: x,y. it can be extruded in any direction, but when you substitute y for z to extrude on the 0,1,0 axis, when trying to load it in the ifc loader, it returns the error: degenerate geometry
![Captura de pantalla 2022-10-04 083851](https://user-images.githubusercontent.com/114978722/193751102-71056b39-3fe4-4021-8576-61cfc49c9c14.png)
![Captura de pantalla 2022-10-04 084121](https://user-images.githubusercontent.com/114978722/193751462-cedc7e83-13d5-4f3c-a095-2f40ab170022.png)

**Comment by QuimMoya** [comment]
It will be great if you can share your code. There are many possible reasons for this problem.

**Comment by beachtom** [comment]
Just wanted to check if this was still an issue - or has it been solved?

**Comment by beachtom** [comment]
Closing as no response
