### ISSUE TITLE
IFC-files written with web-ifc can't be imported in FreeCad, Blenderbim, Revit, Archicad

### ISSUE THREAD

**Issue by SchnFlo** [IFCjs/web-ifc#229]
Hi!
First of all, thanks for the great work on web-IFC!

I'm currently using the parser to add elements to existing IFC-files. In the process, I came to the realization that I can no longer open files in CAD-Software(FreeCad, Blenderbim, Revit, Archicad) after parsing them through web-ifc. 

**The web-ifc viewer demo still manages to open the files.**

I tried around a bit and to me it looks like the problem is that values are being defined as integers instead of floats. (But i did not investigate the c++ code so this is all just blind guessing)

As an Example:
  Before web-ifc:
      #156= IFCDIRECTION((1.,0.,0.));
      #158= IFCDIRECTION((0.,0.,1.));
      #160= IFCCARTESIANPOINT((0.,0.,0.));
  After web-ifc:
      #156=IFCDIRECTION((1,0,0));
      #158=IFCDIRECTION((0,0,1));
      #160=IFCCARTESIANPOINT((0,0,0));
After adding the dots through additional code, the file worked again.

I attached a .zip with a sample .ifc of 2 Walls exported out of ArchiCAD and then parsed through web-ifc.

Thanks for looking into it!

[BIM_MODELS.zip](https://github.com/IFCjs/web-ifc/files/9768018/BIM_MODELS.zip)

**Comment by Mivit** [comment]
This may be related to issue #214?

**Comment by Moult** [comment]
Indeed it's a duplicate issue, web-ifc needs to output the correct data type.
