### ISSUE TITLE
Get the next highest expressID

### ISSUE THREAD

**Issue by clemensjur** [IFCjs/web-ifc#230]
Hi!

It would be great to have a function that returns the next highest expressID of the IFC file.

Thanks!

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::take

Hi, @rfdiazpr! Thanks for taking this bounty! The due date is November 9, 2022 UTC.

If you need to submit some pull requests (PR) to complete the tasks, make sure that the last and only the last PR has a title that either starts with the bounty ID or is exactly the same as the bounty name. After the PR is merged, this bounty’s status will automatically changed to done.

If you do not need to make a PR, tell the manager @agviegas to run `::done` command after your tasks is confirmed to be done.

Good luck!

**Comment by rfdiazpr** [comment]
::extend

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::extend

Hi, @rfdiazpr! The due date is successfully extended by 21 days to November 30, 2022 UTC.

**Comment by agviegas** [comment]
### 🔴🔴🔴

Hi, @rfdiazpr! The date is past due, your assignment has been revoked. It’s now available for anyone to take.

**Comment by BSchafer01** [comment]
::take

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::take

Hi, @BSchafer01! Thanks for taking this bounty! The due date is December 22, 2022 UTC.

If you need to submit some pull requests (PR) to complete the tasks, make sure that the last and only the last PR has a title that either starts with the bounty ID or is exactly the same as the bounty name. After the PR is merged, this bounty’s status will automatically changed to done.

If you do not need to make a PR, tell the manager @agviegas to run `::done` command after your tasks is confirmed to be done.

Good luck!

**Comment by BSchafer01** [comment]
::done

**Comment by agviegas** [comment]
::done

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::done

Hi, @BSchafer01! Thanks for your contributions! Please submit an expense to IFC.js Open Collective. Then, tell us the invoice number via the `::expense::_____` command (replace the `_____` with the invoice number).

**Comment by BSchafer01** [comment]
::expense::114008

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::expense::114008

Hi, @BSchafer01! Thanks for the confirmation! We’ll proceed to review the expense. Once it’s approved, the payment will be scheduled.

**Comment by agviegas** [comment]
### 🟢🟢🟢

Hi, @BSchafer01! Your [expense](https://opencollective.com/ifcjs/expenses/114008) has been approved!

**Comment by agviegas** [comment]
### 🎉🎉🎉

Hi, @BSchafer01! Thanks for your contributions! The reward of this bounty has been transferred to your Open Collective account.
