### ISSUE TITLE
degenerate polygon in extrude for slab

### ISSUE THREAD

**Issue by Moult** [IFCjs/web-ifc#231]
See test file: [test.txt](https://github.com/IFCjs/web-ifc/files/9776528/test.txt)

**Comment by QuimMoya** [comment]
Not 100% sure... still have to test it... but i think we have solved it.
![image](https://user-images.githubusercontent.com/12625508/199705636-f7ab5b65-9319-478f-bf66-11fb116fdd29.png)

**Comment by Moult** [comment]
Nice! What was the issue?

**Comment by QuimMoya** [comment]
Well ... 
![image](https://user-images.githubusercontent.com/12625508/199710724-46ab0158-47f2-4f29-8818-71fed7d8b620.png)

**Comment by Moult** [comment]
Oh wow segments weren't supported?

**Comment by QuimMoya** [comment]
Not in this format. It was prepared to receive References not direct objects.

**Comment by Moult** [comment]
@QuimMoya the IFC spec defines those as types, not entities, so it must always be "direct objects", never references.

**Comment by QuimMoya** [comment]
Maybe... i have found many files containing it, i'm going to test them

**Comment by rvouilloz** [comment]
Thanks QuimMoya, but I still don't have the slabs displayed here : https://enac-cnpa.github.io/BlenderBIM-Tutoriel-Villa-Le-Sextant/ifc/5-column/index.html
Or is that another issue?

**Comment by QuimMoya** [comment]
@rvouilloz Is this viewer updated with the last PR?

**Comment by QuimMoya** [comment]
@Moult I think i know what is happening. IFC.JS is using the same function to read lists of points, therefore it must be able to read both, refs and types. I'm working on it.
