### ISSUE TITLE
File doesn't open because of geometry

### ISSUE THREAD

**Issue by agviegas** [IFCjs/web-ifc#232]
Here is the [file](https://drive.google.com/file/d/1r_bMWOeJ-_1QYqii7TpMF23bKnjtSKQi/view?usp=sharing). This happens when opening the model and `USE_FAST_BOOLS=false`. Actually, many files throw errors when being open with this configuration. Probably due to the integration of elalish/manifold.

**Comment by QuimMoya** [comment]
Last commit (today) is able to load this model
![image](https://user-images.githubusercontent.com/12625508/219051026-3bdcd2ba-be64-44e3-bdce-8200f9452dd3.png)
