### ISSUE TITLE
Missing elements in the loaded file

### ISSUE THREAD

**Issue by yermolim** [IFCjs/web-ifc#236]
Hello! I have an issue with missing elements in one of the models. I hope you could help.
Here is the [model](https://drive.google.com/file/d/1zHltT_DOwP3eA7s1USaql7QDpFo_2_xB/view?usp=sharing).

Here is how it should look in the viewer (Open IFC Viewer), the missing elements are selected (green):
<img width="480" alt="image" src="https://user-images.githubusercontent.com/39064665/196238739-21a35441-80d7-4e83-8625-792def959acd.png">

Here is how it looks in the web-ifc-viewer:
<img width="480" alt="image" src="https://user-images.githubusercontent.com/39064665/196239073-658997c9-8088-43e1-a58d-8e34fa05312e.png">
I see the same thing in my viewer when I try to load it using web-ifc@0.0.35.

If I try to open it using [examples/viewer](https://ifcjs.github.io/web-ifc/examples/viewer/index.html) or locally using web-ifc@0.0.36 I see the following error:
<img width="480" alt="image" src="https://user-images.githubusercontent.com/39064665/196240227-2b040811-646e-4210-b99c-4a748ab5dbcd.png">

In case it helps, the problematic objects' global IDs are:
_0Gx0nCGradHwXsXRcq645r
1tqNNy1nzEJ8cfWf_6SXLV
1rVYA3AYFmGuDG_fmdbU_6_

**Comment by arantesf** [comment]
Having the same problem here!

**Comment by QuimMoya** [comment]
Hello... i can't access the link to the IFC file... i will try to solve it.

**Comment by yermolim** [comment]
> Hello... i can't access the link to the IFC file... i will try to solve it.

Hi, I've updated the access to the link. It should work fine now. I'm sorry for the inconvenience.

**Comment by QuimMoya** [comment]
Seem that the issue has been already solved in a previous issue
![image](https://user-images.githubusercontent.com/12625508/199922073-53710677-9d7a-4299-bbe5-e793661e04c0.png)

**Comment by yermolim** [comment]
> Seem that the issue has been already solved in a previous issue

Looks promising, thanks for your efforts! 

Could you tell me where I can find the updated version to make a local test? 
Haven't these changes been pushed into this repo yet? Because I've tried to clone this repo and run the dev server. And the file doesn't seem to open in 'examples/viewer', at least I see nothing in the viewport.

**Comment by QuimMoya** [comment]
@yermolim The actual repo should be able to open it. The 'examples/viewer' requires some steps to wrok. First you must run 'build-release-all', then 'build-viewer' and finally 'dev'

By doing so it should work... if doesn't just tell me and we will try to find a solution.

**Comment by yermolim** [comment]
<img width="320" alt="image" src="https://user-images.githubusercontent.com/39064665/200185497-efeb99f6-f79b-469b-8c2d-9293a637e370.png">
Thanks a lot! I can confirm it works with the current repo!
Looking forward to the changes being published to npm. Thanks again for your help!
