### ISSUE TITLE
Some visual glitches with rendering half space solid booleans

### ISSUE THREAD

**Issue by Moult** [IFCjs/web-ifc#240]
Reported here by user: https://community.osarch.org/discussion/1197/bug-on-ifcwalls-connections-when-exporting-ifc-from-blenderbim-to-ifc-js

I'm not sure if this is a web-ifc issue or a web-ifc-viewer issue, since technically the half space solid boolean plane is applied and clips the wall, yet in the viewer it shows some form of infinite plane.

One guess is due to geometric tolerance where the clipping is coincident with the edges of the extrusion?

**Comment by QuimMoya** [comment]
Solving issue 219 has solved this issue.
![image](https://user-images.githubusercontent.com/12625508/200002831-285c822d-6998-48d9-8019-8bb4f8eb4868.png)
