### ISSUE TITLE
Using web-ifc WASM from other languages

### ISSUE THREAD

**Issue by wlinna** [IFCjs/web-ifc#244]
Hello,

I'm toying with the idea of using web-ifc to implement an IFC importer. My program is written in Rust, and it runs on a desktop / server and on modern web browsers .

Do you see any obstacles on using the WASM module in this manner? Are you aware of any similar experiments that I could refer to?

**Comment by Moult** [comment]
Cross referencing to https://github.com/IfcOpenShell/IfcOpenShell/issues/2265 in case @aothms has any insights

**Comment by aothms** [comment]
> in case @aothms has any insights

Nope, it's also a bit new to me still. We're likely going to bypass all of this complexity simply by using pyodide or (rather new, but promising) https://github.com/sagemathinc/cowasm

That way we can reuse the ten thousands of sloc of python code in IfcOpenShell in the browser.

It's not going to give the same module size as a nifty cross compiled rust binary, but at the same time I've also came to appreciate runtime typing for writing schema-agnostic code. The differences between schema versions are often too minimal to care about, but large enough to end up in serious fights with your type system. (And to my knowledge Rust is still quite limited there with generics or dependent types).

**Comment by wlinna** [comment]
> The differences between schema versions are often too minimal to care about, but large enough to end up in serious fights with your type system.

Fortunately for me though, I'm thinking of using only the geometry (triangulated) and the type names (e.g. IfcWindow,IfcSlab, ...). I hope this will help me to avoid fights with the type system.

**Comment by aothms** [comment]
Makes sense @wlinna  :)

**Comment by beachtom** [comment]
I'm just cleaning up the issues - did you make any progress on this? For now I'm going to close - but if you want more discussion feel free to re-open

**Comment by wlinna** [comment]
I haven't started yet because of other priorities. Integrating web-ifc is still on the horizon, and if/when I encounter problems I will reopen this.
