### ISSUE TITLE
Docs: pls add web-ifc debugging instructions

### ISSUE THREAD

**Issue by pablo-mayrgundter** [IFCjs/web-ifc#248]
I was able to debug JS->ASM in Chrome today, with some help from @QuimMoya.  Not obvious how to get it all working together so would be good to have a wiki page or dev page somewhere to refer to and improve over time.

1) Need to build the code with debug symbols.  The existing target is dead for me.. anyone else?
2) Chrome needs to be configured for remote debugging
https://stackoverflow.com/questions/45592581/cannot-debug-in-vs-code-by-attaching-to-chrome
3) VSCode needs a magic config as described at SO that specifies the debug port used by the web-ifc dev server

**Comment by beachtom** [comment]
These are now on the homepage of the repo ( I actually did this a while ago)- let me know if they do not make sense
