### ISSUE TITLE
Styles assigned through material representations are not supported

### ISSUE THREAD

**Issue by Moult** [IFCjs/web-ifc#253]
IFC styles may be assigned either to a geometry directly (right branch of diagram), or first to a material, which is then assigned to geometry (left branch of diagram). See diagram below. It seems as though IFCJS does not support the left branch of the diagram.

See attached sample model:

[model.ifc.txt](https://github.com/IFCjs/web-ifc/files/9877318/model.ifc.txt)

![image](https://user-images.githubusercontent.com/88302/198229503-bbf95cb5-21e1-4f2e-a6a1-047281a4abbb.png)

This is what IFCJS shows:

![2022-10-27-191702_605x497_scrot](https://user-images.githubusercontent.com/88302/198229994-4f085aa8-23da-422a-88b1-65f464699fda.png)

This is how it should look:

![2022-10-27-191724_709x624_scrot](https://user-images.githubusercontent.com/88302/198230073-ef6f86fa-4a5c-4e42-8c3b-0da3d431d387.png)

**Comment by QuimMoya** [comment]
Solving other issues we obtained many improvements in this issue
![image](https://user-images.githubusercontent.com/12625508/200003070-1430a9db-4d06-42b9-8d9c-6b9a4ed3dd24.png)

**Comment by QuimMoya** [comment]
Solved in the last commit

![image](https://user-images.githubusercontent.com/12625508/211255369-b078f938-d3c9-46f5-9670-dccda9ae3634.png)
