### ISSUE TITLE
Some issues with Solibri sample models

### ISSUE THREAD

**Issue by kongsgard** [IFCjs/web-ifc#266]
There seems to be some spurious triangles generated for the inner walls in the "Solibri Building Structural" sample model (one of the walls are highlighted in this screenshot, this is generated from current web-ifc main):
![image](https://user-images.githubusercontent.com/13556755/200286477-e2c1beff-984a-455a-b93c-b4e3d3398603.png)

Expected result:
![image](https://user-images.githubusercontent.com/13556755/200286539-3b0cba5f-c24f-451a-b50b-f9b45c047694.png)

There are also some visual artifacts in the result for the "Solibri Building" sample model:
![image](https://user-images.githubusercontent.com/13556755/200287300-2357757a-aa2a-4edb-ba61-e06981f7c1b7.png)
(Most of the issues with this model seems to have been fixed recently in web-ifc main, though. The result from the current package on npm produces some huge cylinders covering most of the model.)

I don't think I can share the models directly, but they can be acquired by downloading Solibri Anywhere. By default they're stored in `C:/Users/Public/Solibri/SOLIBRI/Samples/ifc` on Windows.

**Comment by beachtom** [comment]
I took a quick look at this tonight - but didn't manage to get to the bottom of it. The errors only appear when USE_FAST_BOOLS = true - so almost certainly something in the fast bool calculation functions

**Comment by QuimMoya** [comment]
Last commit solved these issues
![image](https://user-images.githubusercontent.com/12625508/226829730-52ea1211-b5a9-45f3-9740-db9fc0a3aa0c.png)
![image](https://user-images.githubusercontent.com/12625508/226829830-c6960192-107f-49ef-8ae5-212b273be949.png)
