### ISSUE TITLE
serialized value is too large

### ISSUE THREAD

**Issue by quasarchimaere** [IFCjs/web-ifc#269]
![GW_00001](https://user-images.githubusercontent.com/8503486/189336987-ce917c1b-52fa-40e5-8bae-e38d0c1037a5.png)

Happens on a rather small (20mb) file, i try and reproduce the issue with another ifc file, currently we are not allowed to post/share the file due to costumer restrictions

**Comment by agviegas** [comment]
We will probably need to have those files in order to sort this out. We will be happy to sign a NDA if needed. Cheers!

**Comment by Exathera** [comment]
Hello,
I have same problem with this big file from another issue: https://github.com/IFCjs/web-ifc/issues/119.
File won't load with active webWorkers. Looks like pc performance issue, becouse on stronger pc it will load perfectly. However, if i don't use this `await viewer.IFC.loader.ifcManager.useWebWorkers(true, 'build/files/IFCWorker.js');`, it will load.

Same behavior with your examples: https://ifcjs.github.io/info/docs/Guide/web-ifc-three/Tutorials/AdvancedLoading (WON'T load), https://ifcjs.github.io/web-ifc-viewer/example/ (WILL load)

**Comment by agviegas** [comment]
@Exathera we are currently working on a more performant geometric system (https://ifcjs.github.io/components/examples/fragment-loader-tiles.html) that will be the way to go in this cases. This system will imply converting the IFC into another format called [fragments](https://github.com/ifcjs/fragment). In the end, IFC has many limitations, and trying to open an IFC fast every time inside a browser doesn't make much sense. Hopefully we'll have a first version of this before the end of this year.

**Comment by Exathera** [comment]
Nice, it's great to hear that. Thanks so much, can't wait to try it :)

**Comment by beachtom** [comment]
On clearing up issues I think this is either an issue with something outside of web-ifc or it is now solved. In any case the next version has a better IFC loading mechanism that should prevent issues like this.
