### ISSUE TITLE
Exported IFC File does not encode propertyvalues to ifc unicode again

### ISSUE THREAD

**Issue by quasarchimaere** [IFCjs/web-ifc#273]
Since https://github.com/IFCjs/web-ifc/pull/176 has been merged exporting an open ifc file does not encode the values anymore and thus properties are stored improperly.

Example:
Original Line:
`#283= IFCPROPERTYSET('0m0f03tmn2$uLR5br3Hdyv',#41,'Ph\X2\00E4\X0\sen',$,(#222,#281));`
Exported Line:
`#283=IFCPROPERTYSET('0m0f03tmn2$uLR5br3Hdyv',#41,'Phäsen',$,(#222,#281));`

**Comment by QuimMoya** [comment]
I see... it decodes, but never encodes again.

**Comment by beachtom** [comment]
This if fixed now
