### ISSUE TITLE
Inconsistent mesh rendering

### ISSUE THREAD

**Issue by tymokvo** [IFCjs/web-ifc#278]
Hello,

Thanks for making IFC.js, it's great :smile_cat: .

I'm just looking for a hint on how to solve a slightly annoying rendering issue. I'm generating IFC files manually and using IFC.js to display them. But, some of the meshes seem to render inconsistently:

![image](https://user-images.githubusercontent.com/12144028/200916371-3782ef3d-0669-4fb7-9a14-3b3fe5c6def9.png)

Here, the top face of one extrusion renders very dark but the top face renders how I would expect on the other. This is reversed when viewing the same model from the bottom.

It's possible that the way I'm generating the geometry is the source of the issue, but I thought I would see if it's known case when rendering with IFC.js.

I've attached the file in question in case that helps.

[extrusions.zip](https://github.com/IFCjs/web-ifc-viewer/files/9974284/extrusions.zip)

**Comment by agviegas** [comment]
Hey @tymokvo [here](https://drive.google.com/file/d/1GI3i9feFsz6l-VrTh6iKbYCGQh9F3WFr/view?usp=share_link) you have a video explaining how this repository works. You can also contact @QuimMoya (Quim#3042 in Discord) if you have any questions. Cheers!

**Comment by QuimMoya** [comment]
Solved... but still some work to do, 
![image](https://user-images.githubusercontent.com/12625508/223085891-10fa1302-bf33-4962-8cc4-f86fe0f03505.png)

**Comment by tymokvo** [comment]
Awesome! Thank you! Sorry I wasn't able to find time to contribute sooner. Is there a branch where I could see how the fix works?

**Comment by QuimMoya** [comment]
@tymokvo 
I will commit changes to the main branch. Tomorrow you will have it.

**Comment by QuimMoya** [comment]
I commit changes, now you can test it in main.
