### ISSUE TITLE
Surely correct representation of IfcPositiveInteger?

### ISSUE THREAD

**Issue by fkleedorfer** [IFCjs/web-ifc#279]
I am not convinced that the [IfcPositiveInteger](https://standards.buildingsmart.org/IFC/DEV/IFC4_3/RC2/HTML/link/ifcpositiveinteger.htm), whose express definition is
```
TYPE IfcPositiveInteger = IfcInteger;
 WHERE
  WR1 : SELF > 0
END_TYPE;
```
is correctly represented as 
```
export declare class IfcPositiveInteger {
    value: IfcInteger;
    constructor(v: IfcInteger);
}
```
Having the IfcInteger nested in there seems redundant and complicates my code if I want to generate such a value. In STEP, such values are not written as `IfcPositiveInteger(IfcInteger(5))` but as `IfcPositiveInteger(5)`. Might it be a transpilation error from Express to Typescript?

If so, there are a few other types that have the same problem, such as `IfcPositivePlaneAngleMeasure` and `IfcPositiveLengthMeasure`

**Comment by beachtom** [comment]
@fkleedorfer this should be fixed in latest - can you let me know and come back to me if it is not.
