### ISSUE TITLE
Steel profile not rendered

### ISSUE THREAD

**Issue by fedelaport** [IFCjs/web-ifc#280]
Hi guys.

We have this file. It's a cold formed steel panel. Some profiles are not rendered.

[W11.zip](https://github.com/IFCjs/web-ifc/files/10189530/W11.zip)

This is a desktop viewer:
![image](https://user-images.githubusercontent.com/20012908/206570148-7b54a632-880a-4598-9374-663e1151f57f.png)

This is IFCjs latest published viewer:
![image](https://user-images.githubusercontent.com/20012908/206570476-f9d58bbb-5ec6-40d3-9171-05fbd7059507.png)

In console we get a bunch of "ERROR: unexpected profile type" logs.

Hope somebody can take a look at it or at least point us in a good direction, so we can try to fix it ourselves 😃 . 

Thanks in advance.

**Comment by QuimMoya** [comment]
![image](https://user-images.githubusercontent.com/12625508/216086905-b0e647fc-2e0f-437a-9652-cdb242f26ac2.png)
Solved
