### ISSUE TITLE
Error loading large model with web-ifc using IfcAPI2

### ISSUE THREAD

**Issue by rkaeplive** [IFCjs/web-ifc#282]
Im trying to load large model (600mb) and then I read ifc as a text, this happens!
Error: abort(Error: Cannot create a string longer than 0x1fffffe8 characters)

On this part:
<img width="806" alt="Screenshot 2022-12-07 at 13 17 47" src="https://user-images.githubusercontent.com/80881455/206152396-2ac554fc-cc52-4b1f-ac51-24976e4e677b.png">

**Comment by aka-blackboots** [comment]
::take

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::take

Hi, @aka-blackboots! Thanks for taking this bounty! The due date is February 7, 2023 UTC.

If you need to submit some pull requests (PR) to complete the tasks, make sure that the last and only the last PR has a title that either starts with the bounty ID or is exactly the same as the bounty name. After the PR is merged, this bounty’s status will automatically changed to done.

If you do not need to make a PR, tell the manager @agviegas to run `::done` command after your tasks is confirmed to be done.

Good luck!

**Comment by aka-blackboots** [comment]
::drop

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::drop

Hi, @aka-blackboots! Thanks for giving it a try! It’s now once again available for anyone to take.

**Comment by beachtom** [comment]
I am just trying to resolve old issues. I think this is more to do with how you encode the input into a UInt8Array - mostly it would come from a reader of some sort - not a string. I am closing this as not an web-ifc issue - but if it is still causing issues please re-open
