### ISSUE TITLE
IFCSensor not rendered

### ISSUE THREAD

**Issue by sh-aix** [IFCjs/web-ifc#283]
Hello, 

I have an IFCx4 Model containing an IFCSensor. Everything is rendered fine except the IFCSensor, which is never displayed. However, using 3Dviewer.net the model is perfectly shown including the IFCSensor. 

I am using IFC.js in Version 1.0.213. I thought 3Dviewer.net is using ifc.js as well. What is the problem here?

Regards,
Stefan

**Comment by QuimMoya** [comment]
@sh-aix Can you share the ifc model?

**Comment by aka-blackboots** [comment]
@QuimMoya did you receive the IFC file for this?

**Comment by beachtom** [comment]
Is this still an issue - can you share the model?

**Comment by beachtom** [comment]
Closing as no response
