### ISSUE TITLE
ExportFileAsIFC(): Header not reproduced properly

### ISSUE THREAD

**Issue by fkleedorfer** [IFCjs/web-ifc#291]
Reading an IFC file and writing it using `ExportAsIFC()`.

Problem: the IFC header changes. It should not.

Example file is attached. 

The input file's header is: 
```
HEADER;
FILE_DESCRIPTION(('ViewDefinition [CoordinationView_V2.0]'),'2;1');
FILE_NAME('test');
FILE_SCHEMA(('IFC2X3'));
ENDSEC;
```
output:
```
HEADER;
FILE_DESCRIPTION(('no description'), '2;1');
FILE_NAME('no name', '', (''), (''), 'web-ifc-export', '', '');
FILE_SCHEMA(('IFC2X3'));
ENDSEC;
```

Attaching an [IFC file for which this happens](https://github.com/IFCjs/web-ifc/files/10260396/one_wall.txt).

**Comment by aka-blackboots** [comment]
::take

**Comment by aka-blackboots** [comment]
::drop

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::drop

Hi, @aka-blackboots! Thanks for giving it a try! It’s now once again available for anyone to take.

**Comment by beachtom** [comment]
@fkleedorfer this should be fixed now on the latest version committed. Can you try and re-open if any issues?
