### ISSUE TITLE
Numeric instability of real values

### ISSUE THREAD

**Issue by fkleedorfer** [IFCjs/web-ifc#292]
Reading an IFC file with the following property: 
```
IFCPROPERTYSINGLEVALUE('Width',$,IFCLENGTHMEASURE(0.16),$);
```
leads to a value of  `0.16000000000000003` in the IFC model. I see many similar cases in files I use for testing.

It stands to reason that a JS Number is not the best type for representing IFC REALs. 

I see two options to fix this - either we keep the string value (i.e.,  `"0.16"`), or we use a library like [decimal.js](https://www.npmjs.com/package/decimal.js) to represent numbers accurately.

Attaching an [IFC file that contains a property with this problem](https://github.com/IFCjs/web-ifc/files/10260579/input.txt).

**Comment by andy-wrks** [comment]
I also encountered this problem and would welcome a solution that retains the original decimals from the text based EXPRESS  notation.

**Comment by beachtom** [comment]
So while I didn't directly fix this - I think in all the other fixes to the parser this has also been fixed

**Comment by fkleedorfer** [comment]
So the value in the JSON structure is a string now?

**Comment by beachtom** [comment]
so no I left it as decimal and for my models it seems to work as expected so I wrote a decimal to an IFC file - wrote it out - then read it back in and it maintained precision

**Comment by fkleedorfer** [comment]
Not sure if your test really reproduces the issue. You wrote a decimal to an IFC file and read it back in, and it maintained precision. I think in most cases, IFC.js did that already when this issue was created. This issue is about specific values, such as 0.16 or 0.2, that seem to cause problems because they cannot be accurately represented as binary numbers (they are both periodic in binary).

Could you try this:

1. Manually view an IFC file and if necessary edit it so it contains a numeric value of 0.16 somewhere (0.2 will work just as well - both are perodic in binary)
2. Read it with IFC.js
3. look at the value in the parsed object in Javascript.

If the value is the same number that is in the IFC file, this is fixed.

**Comment by beachtom** [comment]
Right ok I get it now! No it is not fixed

**Comment by fkleedorfer** [comment]
I am not sure it **can** be fixed without using a different data type for the values in the javascript object structure. `string` is probably the best option. For an illustration, try this in the javascript console of your browser: 
```
0.3 - 0.1 
> 0.19999999999999998
```
(taken from https://github.com/MikeMcl/decimal.js)

**Comment by beachtom** [comment]
I'll do some investigating as to where it originates - is it in the C++ parsing or only in the JS and will come back

**Comment by fkleedorfer** [comment]
I guess you will have some amount of instability in any language unless you use something like BigDecimal... And strings in json

**Comment by beachtom** [comment]
So this is now properly fixed. Essentially the imprecision is introduced in the transfer from C++->Javascript - but oddly enough not in the opposite direction. So these values are being kept as strings until they leave C++ then cast to double inside javascript only which seems to work.
