### ISSUE TITLE
Some IFC models return 'IsManifold()' is false: Input mesh is not manifold!

### ISSUE THREAD

**Issue by kvandake** [IFCjs/web-ifc#293]
I use https://github.com/xeokit/xeokit-convert. The library use [web-ifc](https://github.com/IFCjs/web-ifc) and when I converting I get the error:
```
IsManifold()' is false: Input mesh is not manifold!
```
I found a line with [IsManifold](https://github.com/IFCjs/web-ifc/blob/main/src/wasm/include/math/bool-mesh-mesh.h#L208).

I don`t know C++ and cannot fix it... Can you help resolve this error?
I can attach the ifc with error.

Reference issues:
- https://github.com/xeokit/xeokit-convert/issues/93
- https://github.com/IFCjs/web-ifc/issues/216

**Comment by QuimMoya** [comment]
We are not using manifold anymore
