### ISSUE TITLE
Geometry: Cylindrical shapes not displayed correctly

### ISSUE THREAD

**Issue by andy-wrks** [IFCjs/web-ifc#295]
The attached file contains some cylindrical shapes that are displayed as triangular shapes.
Not sure if this is due to very rough tesselation settings or some other issue.

The issue can be reproduced on
https://ifcjs.github.io/web-ifc-viewer/example/index and
https://ifcjs.github.io/web-ifc-three/example/

Current output:

![image](https://user-images.githubusercontent.com/111515188/209819640-5be48c7f-0562-44c6-bfc9-bece8a4f86f1.png)

Expected output:

![image](https://user-images.githubusercontent.com/111515188/209819816-6490414d-dd10-45c3-9844-88bc5442f0ee.png)

Sample file:
[cylinders.zip](https://github.com/IFCjs/web-ifc/files/10314440/cylinders.zip)

**Comment by QuimMoya** [comment]
Solved

![image](https://user-images.githubusercontent.com/12625508/211764753-de6a6ea5-96dc-4122-b896-ea2c3886372b.png)

I will upload the changes in the next commit

**Comment by QuimMoya** [comment]
We can increase definition if needed
![image](https://user-images.githubusercontent.com/12625508/211766223-9fee58e1-c6af-4ddf-b7a1-6000244f3b6d.png)

**Comment by linoygabay** [comment]
Cool! it sloved also my problem .
but I would like to know if you can upgrade web-ifc 0.0.36 in web-ifc-viewer that I could show the model good :)

**Comment by yoifox** [comment]
doesnt work in latest version with this file
[ifc.zip](https://github.com/IFCjs/web-ifc/files/10568175/ifc.zip)

**Comment by QuimMoya** [comment]
@yoifox  
![image](https://user-images.githubusercontent.com/12625508/216536335-612b3fd1-e722-432e-a939-edf7b10d3e53.png)
probably you are not using fast bools. If you activate this option it should work
