### ISSUE TITLE
Geometry: Slab is not displayed

### ISSUE THREAD

**Issue by andy-wrks** [IFCjs/web-ifc#296]
The attached sample file contains a slanted IfcRamp and a flat IfcSlab.
The IfcSlab is not displayed in the viewport.

The issue can be reproduced on
https://ifcjs.github.io/web-ifc-viewer/example/index and
https://ifcjs.github.io/web-ifc-three/example/

Current output:

![image](https://user-images.githubusercontent.com/111515188/209821058-29809ec9-9520-4dfc-9de0-6212f63ca50a.png)

Expected output:

![image](https://user-images.githubusercontent.com/111515188/209821122-3958f574-d289-4894-8af0-eb1b39d36105.png)

Sample file:
[ramp.zip](https://github.com/IFCjs/web-ifc/files/10314487/ramp.zip)

**Comment by QuimMoya** [comment]
Solved in the last commit:
![image](https://user-images.githubusercontent.com/12625508/211252888-ccccc26d-9fe6-47cc-a05b-f54b010b8179.png)
