### ISSUE TITLE
Geometry: broken wall shapes

### ISSUE THREAD

**Issue by andy-wrks** [IFCjs/web-ifc#297]
The attached example file contains 3 IfcWalls, all of which appear with broken geometry.
The file was originally exported from Revit 2022.

The issue can be reproduced on
https://ifcjs.github.io/web-ifc-viewer/example/index and
https://ifcjs.github.io/web-ifc-three/example/

Current output:

![image](https://user-images.githubusercontent.com/111515188/209826894-69561a5e-b532-4503-8cf2-cdd6c7c4c5c8.png)

Expected output:

![image](https://user-images.githubusercontent.com/111515188/209827153-9ae241b7-db9c-4709-afcc-3501a97d90cf.png)

Sample file:
[walls.zip](https://github.com/IFCjs/web-ifc/files/10314690/walls.zip)

**Comment by QuimMoya** [comment]
The last commit solves this issue.
