### ISSUE TITLE
Geometry: broken wall shapes 2

### ISSUE THREAD

**Issue by andy-wrks** [IFCjs/web-ifc#298]
The attached file contains some walls, where the geometry appears broken.
The file was originally exported from Revit 2020.
(https://github.com/IFCjs/web-ifc/issues/297 contains a similar example from a different building project)

The issue can be reproduced on
https://ifcjs.github.io/web-ifc-viewer/example/index and
https://ifcjs.github.io/web-ifc-three/example/

Current output:

![image](https://user-images.githubusercontent.com/111515188/209955828-5ebfa886-3df7-43e1-a381-616ee875ddb5.png)

Expected output:

![image](https://user-images.githubusercontent.com/111515188/209956241-e57a6d42-fa06-4b24-b48c-47c1b9d26cfc.png)

Sample file:
[Revit2020_walls.zip](https://github.com/IFCjs/web-ifc/files/10319622/Revit2020_walls.zip)

**Comment by QuimMoya** [comment]
Solved in the next release
![image](https://user-images.githubusercontent.com/12625508/218724313-d6e8d8ba-6ec5-4d44-829e-7b43d9274d17.png)
