### ISSUE TITLE
Geometry: broken wall openings

### ISSUE THREAD

**Issue by andy-wrks** [IFCjs/web-ifc#300]
The attached file contains 6 walls with doors in them. 4 of the walls don't display the door opening correctly, the walls seem to be closed from one side.
The file was originally exported from Vectorworks 2020.

The issue can be reproduced on
https://ifcjs.github.io/web-ifc-viewer/example/index and
https://ifcjs.github.io/web-ifc-three/example/

Current output:
![image](https://user-images.githubusercontent.com/111515188/209965202-35c12463-01d2-4c3e-b765-0a7339e41efe.png)

Expected output:
![image](https://user-images.githubusercontent.com/111515188/209965447-21e49d90-a0c9-4f9c-99ef-b3d3616ddf8c.png)

Sample file:
[VW2020-openings.zip](https://github.com/IFCjs/web-ifc/files/10319881/VW2020-openings.zip)

**Comment by sanvie** [comment]
probably same as https://github.com/IFCjs/web-ifc/issues/196 and https://github.com/IFCjs/web-ifc/issues/126

**Comment by QuimMoya** [comment]
Current version is able to open this file properly. But there are still some minor issues.
![image](https://user-images.githubusercontent.com/12625508/223490707-e95d55f9-00dd-414a-8b7c-4a2f107f5224.png)

**Comment by QuimMoya** [comment]
Ok, last commit finally solved this issue.
![image](https://user-images.githubusercontent.com/12625508/226829441-c5de567e-cab0-4e9a-9a50-e4c138fa1f2b.png)
