### ISSUE TITLE
web-ifc versioning

### ISSUE THREAD

**Issue by jespa007** [IFCjs/web-ifc#308]
Hi there,

I post this issue as a Best Practice in the software. Latelly, I've seen that web-ifc has a lot of "commits" in the "main" branch but it package.json keeps the same version (i.e 0.0.36). 

I'd would recommend to create a [milestone](https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/about-milestones) organize and generate versions for a set of issues than people publishes.

Then people can compare better the software within diferents versions.

Also I can see that, there's no any web-ifc release published yet in the releases github section.

![image](https://user-images.githubusercontent.com/7852409/211508330-fa4f0542-ddb6-4916-8db5-4f3e0a1daa0e.png)

**Comment by agviegas** [comment]
Nice idea! I completely agree with this.

**Comment by D4ve-R** [comment]
::take

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::take

Hi, @D4ve-R! Thanks for taking this bounty! The due date is February 23, 2023 UTC.

If you need to submit some pull requests (PR) to complete the tasks, make sure that the last and only the last PR has a title that either starts with the bounty ID or is exactly the same as the bounty name. After the PR is merged, this bounty’s status will automatically changed to done.

If you do not need to make a PR, tell the manager @agviegas to run `::done` command after your tasks is confirmed to be done.

Good luck!

**Comment by D4ve-R** [comment]
@beachtom can you mark this one as done ? Mentioning the issue in pr with a resolve comment somehow breaks the bot 🤔

**Comment by agviegas** [comment]
### 🔴🔴🔴

Hi, @D4ve-R! The date is past due, your assignment has been revoked. It’s now available for anyone to take.

**Comment by agviegas** [comment]
Hey @D4ve-R take this again and I'll mark it as done. Sorry for the fuss!

**Comment by D4ve-R** [comment]
::take

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::take

Hi, @D4ve-R! Thanks for taking this bounty! The due date is March 19, 2023 UTC.

If you need to submit some pull requests (PR) to complete the tasks, make sure that the last and only the last PR has a title that either starts with the bounty ID or is exactly the same as the bounty name. After the PR is merged, this bounty’s status will automatically changed to done.

If you do not need to make a PR, tell the manager @agviegas to run `::done` command after your tasks is confirmed to be done.

Good luck!

**Comment by agviegas** [comment]
::done

**Comment by D4ve-R** [comment]
::expense::125715

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::expense::125715

Hi, @D4ve-R! Thanks for the confirmation! We’ll proceed to review the expense. Once it’s approved, the payment will be scheduled.
