### ISSUE TITLE
missing some geometries

### ISSUE THREAD

**Issue by rkaeplive** [IFCjs/web-ifc#310]
Hi! I have problem with loading ifc file! 
![image](https://user-images.githubusercontent.com/80881455/212704561-0d2545e6-7e99-4cb2-a120-8226b64fc4b7.png)
![image](https://user-images.githubusercontent.com/80881455/212704602-b6a02b20-f728-4f15-aef7-74625b648f05.png)

some geometries didn't load, and there are many warnings on console log
the Ifc file here:
[b548ace8-9a0d-4487-93a2-ceeec8fe73e2.Ifc.zip](https://github.com/IFCjs/web-ifc/files/10426752/b548ace8-9a0d-4487-93a2-ceeec8fe73e2.Ifc.zip)

**Comment by QuimMoya** [comment]
![image](https://user-images.githubusercontent.com/12625508/216015646-0115fff8-783e-47a7-8033-25d4c4a9e9ee.png)
Solved
Is there anything else?
