### ISSUE TITLE
The method ifcApi.WriteLine() doesn't work properly.

### ISSUE THREAD

**Issue by Nicter** [IFCjs/web-ifc#314]
Environment: web-ifc version 0.0.36

The following code is intended to modify the contents of an IFC dataline as described in the code example on the website [IFC.js Docs | Editing Properties](https://ifcjs.github.io/info/docs/Guide/web-ifc/Tutorials/Editing%20Properties).

` const fs = require("fs");
const path = require("path");
const IFCFLOWSEGMENT = require("web-ifc/web-ifc-api-node.js").IFCFLOWSEGMENT;
const WebIFC = require("web-ifc/web-ifc-api-node.js");
// initialize the API
const ifcApi = new WebIFC.IfcAPI();

async function main() {
    // initialize the library
    await ifcApi.Init();

    //load an ifc model
    const ifcData = fs.readFileSync(
        path.join(__dirname, "ifcData", "Clinic_HVAC.ifc")
    );

    // open a model from data
    let modelID = ifcApi.OpenModel(ifcData);

    element = ifcApi.GetLine(modelID, 3563); //This is a IfcFlowSegment

    element.Name.value += "Hello Test";

    ifcApi.WriteLine(modelID, element); // causes the result 'Line object cannot be serialized'

    // close the model, all memory is freed
    ifcApi.CloseModel(modelID);
}

main();`

But instead returns the console log 'Line object cannot be serialized'.

**Comment by beachtom** [comment]
@Nicter this should now be working - can you try it and re-open if still issues?

**Comment by Nicter** [comment]
@beachtom On my system it works too. Thanks for your work.
