### ISSUE TITLE
Add requeriments section in README.md

### ISSUE THREAD

**Issue by jespa007** [IFCjs/web-ifc#324]
Hi there,

Today as 2023-02-06 I've dowloaded and try to compile web-ifc and it fails when it tries to link web-ifc.js. It throws an error `Attemp to set a non-existent setting: 'STACK_SIZE'` . I've search for STACK_SIZE and it seems this option in emscripten was appeared in a version later. 

I suggest put a requeriments section in the README.md that tells the packages (python, emscripten,etc ) and its minimum version in order to build the whole package of web-ifc

Thanks

**Comment by beachtom** [comment]
Really good suggestion! Thanks

**Comment by beachtom** [comment]
This is done!
