### ISSUE TITLE
tsc --emitDeclarationOnly takes a long time to execute

### ISSUE THREAD

**Issue by jespa007** [IFCjs/web-ifc#325]
Hi there,

I've downloaded the code from github today (i.e at date of 2023-02-06) and when I try to execute  `npm run build-ts-api` takes **7 minutes and 30 seconds** .  In fact, the root of this bootleneck is the instruction `tsc --emitDeclarationOnly` that is part of `npm run build-ts-api`.

 I think is too long time! I don't know is the tsc version or something in my configuration that causes that high time.

Compared with the codes I've downloaded  `build-ts-api` it takes,

- web.ifc downloaed today (i.e 2023-02-01): **7 minutes and 30 seconds** 
- web-ifc dowloaded at 2023-02-01: **1 minute and 40 seconds**
- web-ifc from current npm package: **7 seconds**

So, it can see that the original operation time goes from **7 seconds** to the last one that ends with **7 minutes and 30 seconds**. (has been increased x64 times)

Of course I'm aware that web-ifc it improves a lot on each commit but sincerelly, **7 minutes and 30 seconds** is a very long time in terms of productivity.

**Comment by beachtom** [comment]
@jespa007 yes this is because we now have IFC2x3 IFC4 and IFC4.3 schemas in typescript. I am looking at this on issue #321 to try to resolve it right now

**Comment by jespa007** [comment]
Hi @beachtom, 
thanks a lot for your response. Or maybe as a provisional solution do NOT invoke `tsc --emitDeclarationOnly` if the schemas or output files were not generated.

**Comment by beachtom** [comment]
So I am in the processing of reducing the size of the schema - but it is not ready yet - for now what I have done is enabled incremental compilation. So the first time you build it - it will still take the 7 min - but additional times will then be much quicker (unless you edit the schema files).
