### ISSUE TITLE
API Needs a Function to remove an IFC line

### ISSUE THREAD

**Issue by beachtom** [IFCjs/web-ifc#327]
At the moment we have no way to remove a line from an IFC file. This should be added

**Comment by LukasKStavario** [comment]
Is there any update? According to #404?

**Comment by beachtom** [comment]
its the next thing I will be doing so not long - week or so probably.

**Comment by LukasKStavario** [comment]
Thank you!! When are you going to release a new version where will this be available?

**Comment by LukasKStavario** [comment]
Any news on version deploy please?
