### ISSUE TITLE
Issues gen_functional_types_helpers.ts

### ISSUE THREAD

**Issue by jespa007** [IFCjs/web-ifc#334]
Hi,

I have a look at  `gen_functional_types_helpers.ts` and I've discovered a possible bug and an optimize issue,

At line 137 it seems that the condition negates !entity.parent but in the body it doesn't uses entity.parent

```
  if (!entity.parent) // --> if(!entity.parent) is the same as entity.parent!=null ?
  {
       
       buffer.push(`\texport class ${entity.name} extends IfcLineObject {`);
  } 
  else // so here entity.parent==NULL ?
  {
       buffer.push(`\texport class ${entity.name} extends ${entity.parent} {`);
  }

```
Optimize issues

At line 157,177,181 it does the following pattern,

`${entity.derivedProps.filter(i => !entity.ifcDerivedProps.includes(i.name)) ... }`

 so it performs and extra overheaded

**Comment by beachtom** [comment]
So if (!entity.parent) is the same as if (entity.parent==null) so I think that is right

For the 2nd point the derivedProps and ifcDerived props are different - dervivedProps are the types of the entity + the types of all parents - IFC derivedProps are props in that given entity the IFC schema marks as derived. So I think all is good

**Comment by jespa007** [comment]
> For the 2nd point the derivedProps and ifcDerived props are different - dervivedProps are the types of the entity + the types of all parents - IFC derivedProps are props in that given entity the IFC schema marks as derived. So I think all is good

I would like to say the `${entity.derivedProps.filter(i => !entity.ifcDerivedProps.includes(i.name)).map(...` it repeats the same pattern, so maybe it can be calculated once

![image](https://user-images.githubusercontent.com/7852409/219016322-c614b10a-ba9f-44aa-9a38-48ef1f16aa92.png)

**Comment by beachtom** [comment]
ok great - I am currently working on the schema gen to make the output smaller - I will fix this at the same time!

**Comment by jespa007** [comment]
perfect @beachtom. Let's see if the generation time also it decreases :-)

**Comment by beachtom** [comment]
This should be fixed and generation should now be quicker

**Comment by jespa007** [comment]
I've already checked `npm run build-ts-api` from `compressed-schema` branch and the generation long 3 seconds !!! thanks a lot  @beachtom
