### ISSUE TITLE
[Contribution Request] Changes to the Web-IFC WASM Module

### ISSUE THREAD

**Issue by nickcastel50** [IFCjs/web-ifc#336]
Hello,

I'm currently working on a project where we are using the Web-IFC WASM module to enable collaborative viewing and editing of various 3D file formats, starting with the IFC format. Our system requirements demand fast access to streaming assets and updates. Therefore, we have decided to write our own parsing and indexing implementation, and utilize the WASM module to handle the geometry extraction and transformations.  

To achieve our objectives, we plan to make significant modifications to the existing Web-IFC WASM codebase. We intend to extend the WASM module to decouple geometry extraction from parsing and expose functions via Emscripten that enable all the necessary transforms and extractions required for the IFC format, as well as other 3D file formats we plan to support.   Post indexing, the system will communicate with the WASM module via a querying system, allowing a user to make fast queries on subsections of the full IFC file. An example of this would be if a user wanted the geometry for just the walls or floors of a model, they could send a query and receive that from the WASM module in a fast and efficient manner. 

As part of our effort, we're considering contributing our modified Web-IFC WASM codebase (including the parsing and indexing system) to the IFCjs team. Is this contribution something that the IFCjs team would be interested in?

**Comment by beachtom** [comment]
I think in short yes we most certainly would!

**Comment by beachtom** [comment]
I am going to close this - please re-open or message on discord if you have any questions - or let us know when you are ready to contribute
