### ISSUE TITLE
When try to build it throws Error: Failed to replace env in config: ${NPM_TOKEN}

### ISSUE THREAD

**Issue by jespa007** [IFCjs/web-ifc#339]
When I try to run build wasm through `npm run build-release`commandit throws Error: Failed to replace env in config: ${NPM_TOKEN}

To solve/fix this issue I have to remove the file  `.npmrc`

**Comment by beachtom** [comment]
Hmm apologies - that is only supposed to be invoke in the github build I will fix shortly.
