### ISSUE TITLE
Geometry: Sample that loads very slow, busy console + see through Slab

### ISSUE THREAD

**Issue by andy-wrks** [IFCjs/web-ifc#341]
This is a sample taken from a much larger model, It only contains slabs from the ground floor and walls from the 1st floor.
However, it's enough to reproduce the two main issues.
The issues can be reproduced on https://ifcjs.github.io/web-ifc/demo/
For the records: The file was originally exported from ArchiCAD 25, so the quality of the file should be decent. I removed all the metadata+properties though.

Issue #1
The geometry of the sample file loads very slow and the console is very busy printing messages while interpreting/converting the geometric data. From experience, a model of this size and complexity usually loads in a couple of seconds in web-ifc. This file however takes 4 minutes on my laptop. Needless to say, the original full-size file took almost 1h.

Some samples from the console:

console1
![image](https://user-images.githubusercontent.com/111515188/220682252-f2c44cc3-7ecd-4280-8222-8d48022dcfd1.png)

console2
![image](https://user-images.githubusercontent.com/111515188/220682505-c70fed0c-f0bd-45cc-a6b5-de7a663aaef8.png)

console3
![image](https://user-images.githubusercontent.com/111515188/220682784-99f7503e-0394-499b-94c0-b6b7eec351a4.png)

console4
![image](https://user-images.githubusercontent.com/111515188/220683695-180557cb-45a4-480e-9c52-edda1667a9e5.png)

Issue#2
Most prominently, the two main IfcSlabs (which have quite a loooong contour and lots of cut outs) are see through.

Current output:
![image](https://user-images.githubusercontent.com/111515188/220685791-005e803b-ddec-46ed-9059-9d84d10d8590.png)

Expected output:
![image](https://user-images.githubusercontent.com/111515188/220686569-77e73b8a-d06f-4388-a1e3-87f54b04ac96.png)

Sample file:
[sample.zip](https://github.com/IFCjs/web-ifc/files/10805976/sample.zip)

**Comment by QuimMoya** [comment]
Las commit solved also this issue
![image](https://user-images.githubusercontent.com/12625508/226838681-cce3b013-8b31-44e2-a38a-f3e6c719d20a.png)
