### ISSUE TITLE
Geometry: Some IfcWallStandardCase geometries are no longer visible in new version of web.ifc. Regression.

### ISSUE THREAD

**Issue by lmicola** [IFCjs/web-ifc#343]
Hello, 
after update from version 0.0.36 to 0.0.39 some IfcWallStandardCase geometries are no longer visible in my model. 

Example: 

before
![correct-wi2](https://user-images.githubusercontent.com/126453677/221541510-391107d4-2a64-4ae4-a581-cd6954cb3c26.png)
after 
![damaged-wi2](https://user-images.githubusercontent.com/126453677/221541571-f28e0d91-db6f-42ea-8a02-4e02aa1cf459.png)

Previous version had no errors for this geometry. New version logs two errors for this geometry: "incident line!incident line!incident line!incident line!incident line!incident line!Loop in findLoop ... how ironic " and "Loop in findLoop ... how ironic "

**Comment by QuimMoya** [comment]
Hello @lmicola 

Can you send us the model?

**Comment by lmicola** [comment]
@QuimMoya  I can send u model with this specific IfcObject. 
[example.txt](https://github.com/IFCjs/web-ifc/files/10882275/example.txt)

**Comment by lmicola** [comment]
web-ifc-0.0.36:
![web-ifc-36](https://user-images.githubusercontent.com/126453677/222731768-76bc077b-8a9f-439f-8ff5-06d093a39b11.png)
web-ifc-0.0.39:
![web-ifc-39](https://user-images.githubusercontent.com/126453677/222731819-dd60b387-f441-444a-bb85-79c22a4cf042.png)
xbim:
![web-ifc-xbim](https://user-images.githubusercontent.com/126453677/222731845-6a7d09e2-c7a0-43e8-b955-e5ca109fd4ce.png)

**Comment by lmicola** [comment]
I wonder if that extra geometry between window holes is intended on side web-ifc (mby known issue already reported). Never seen anything like that in other ifc viewers/geometry convertors.

**Comment by QuimMoya** [comment]
I tried to open it and this is the result: 
![image](https://user-images.githubusercontent.com/12625508/223407583-7f89d931-61b5-487a-93cc-b867dd0b2609.png)

**Comment by lmicola** [comment]
Alot geometries are now fixed but on other hand alot geometries which were correct are now damaged. Here is example: 
[example2.txt](https://github.com/IFCjs/web-ifc/files/10920552/example2.txt)

**Comment by QuimMoya** [comment]
@lmicola 
I will take a look on this. Hopefully i will find a solution.

**Comment by ENG-Mazri** [comment]
Same here..
This was with web-ifc 0.0.33
![Screenshot 2023-03-16 150612](https://user-images.githubusercontent.com/84850871/225612252-b724186c-c049-4b13-92ed-df71351dd566.png)

and this with web-ifc 0.0.39
![image](https://user-images.githubusercontent.com/84850871/225612124-b67e10ef-b247-4cac-8128-2ef8fe05c596.png)

**Comment by lmicola** [comment]
Good job @QuimMoya now I cant find any broken geometry. Maybe small exception is that some geometries have faces flipped but that (in my case) can be easily fixed with THREE.DoubleSide. Here is example: 
[example3.txt](https://github.com/IFCjs/web-ifc/files/11061501/example3.txt)
I will let u decide if this bug/error should be in scope of this issue. I can open new issue and close this one if u would like to. I will do more extensive testing after new version would be released for npm.
