### ISSUE TITLE
[Bug]: Geometry: Wrong normals and missing openings

### ISSUE THREAD

**Issue by andy-wrks** [IFCjs/web-ifc#346]
### What happened?

There seem to be issues with normals and openings in the new web-ifc version. Some might be regressions (?)
I'm posting a complete sample BuildingStorey from a larger model, because I see several issues.
The original model is from ArchiCAD 24.

Issue #1
Some part of the floor is only visible from the top, another part only from the bottom. This might be a normals issue.

![image](https://user-images.githubusercontent.com/111515188/222521247-3994d121-b73a-45a3-9ea6-603500a26b73.png)

![image](https://user-images.githubusercontent.com/111515188/222521354-64bfcb60-01a0-42ce-9767-13440a7dbfde.png)

Issue #2
The facade insulation is missing all of the openings. Some of them are visible from one side though (see marked part).

![image](https://user-images.githubusercontent.com/111515188/222521880-188c7ea5-1f0b-4b67-be57-e730bd06214a.png)

![image](https://user-images.githubusercontent.com/111515188/222522006-3fcd7ab9-5551-4cba-9ace-c236b7d1aed8.png)

Issue #3
In the highlighted part there should be no ceiling.

![image](https://user-images.githubusercontent.com/111515188/222522433-7aec8ae4-0d72-4472-b2ee-f5be9686dcfb.png)

Expected output (Solibri):

![image](https://user-images.githubusercontent.com/111515188/222522732-75c20e86-9940-4c4e-9d8b-5f9307c07c5b.png)

Let me know if you need further examples etc.
I can share models from different disciplines and applications, but I can't post them publicly. Anonymizing these samples is a painful task...

Keep up the good work, it's back and forth now but eventually we will all enjoy great geometry extraction :-)

Sample file:
[Storey.zip](https://github.com/IFCjs/web-ifc/files/10874876/Storey.zip)

### Version

Latest version deployed here: https://ifcjs.github.io/web-ifc/demo/

### What browsers are you seeing the problem on?

Chrome

**Comment by QuimMoya** [comment]
![image](https://github.com/IFCjs/web-ifc/assets/12625508/1e959d2c-822f-44e7-b515-0ee77816afa6)
 Except for some normals, i think this issue is solved

**Comment by andy-wrks** [comment]
Yes, I think most of the "big" issues are solved here and the file looks good. Fell free to close my issue and thanks for all the progresses, good work!
I'm happy to create more specific tickets with smaller sample files if I run into less obvious geometry issues. No need to bring this file to perfection :-)
