### ISSUE TITLE
[Bug]: Request IfcSite information through GetLine returns information with fields RefLatitude and RefLongitude as an undefined value

### ISSUE THREAD

**Issue by jespa007** [IFCjs/web-ifc#347]
### What happened?

When I trie to request `IfcSite` information through `GetLine`it returns information with fields `RefLatitude` and `RefLongitude` as an undefined value

![image](https://user-images.githubusercontent.com/7852409/224086363-e90503b9-100f-46f5-84fc-d6c90b068d2f.png)

It should be an array of three elements.

### Version

0.0.39

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
I've already attached an image
```

**Comment by beachtom** [comment]
This is fixed now!
