### ISSUE TITLE
[Bug]: Inconsistent version from release section

### ISSUE THREAD

**Issue by jespa007** [IFCjs/web-ifc#349]
### What happened?

I have downloaded version 0.0.39 from releases section

![image](https://user-images.githubusercontent.com/7852409/224095460-ba185128-690f-47fc-aca1-8a6e6e1eb250.png)

Inside the tar.gz package `wasm\version.h` is 0.0.38 that does not matches with 0.0.39

![image](https://user-images.githubusercontent.com/7852409/224092966-d8e23872-f5b2-4d69-a144-c353e6bd4e96.png)

neither the one in `package.json`,

![image](https://user-images.githubusercontent.com/7852409/224092709-488b427f-9dec-4f1d-9368-79a05f3776bb.png)

### Version

0.0.39

### Anything else?

Because the web-ifc `WEB_IFC_VERSION_NUMBER` variable from `wasm/version.h` is set from the `version` field in `package.json` I suggest a way to create github-tag from the `version` in `package.json` too

**Comment by beachtom** [comment]
Hmm this should not be the case I will look into it

**Comment by beachtom** [comment]
So I think I already fixed this - but we haven't published a new version since. In any case I can't replicate it anymore. Hopefully it will fix when we next release
