### ISSUE TITLE
[Bug]: CreateIfcGuidToExpressIdMapping not working properly in 0.0.39

### ISSUE THREAD

**Issue by ENG-Mazri** [IFCjs/web-ifc#351]
I was trying the latest web-ifc version and something caught my attention, using CreateIfcGuidToExpressIdMapping in v 0.0.36 for some testing file I used to get the followig

![image](https://user-images.githubusercontent.com/84850871/225379746-5dfc9bf5-d89c-4cae-8242-a25edab14f3a.png)

now I tried the same file with v 0.0.39 and got 43 elements!

![image](https://user-images.githubusercontent.com/84850871/225381302-dfa2c01d-b10a-43ac-95c5-fea52a7e9d54.png)

and most of the items are not elements, they're like property sets and other stuff.

### Version

0.0.39

**Comment by beachtom** [comment]
So I think technically the new output is correct all those things do have Guids...... but I am not sure which behaviour is actually more desired

**Comment by ENG-Mazri** [comment]
Actually yes, they all have Guids, however I think the behavour of the previous versions is more desired, when we got only elements or IFC products, it's much useful to retrieve them this way and get all elements of an IFC file to process them later.
Otherwise this new behaviour slows down the process of retrieving and filtering those elements.

**Comment by beachtom** [comment]
This should now be fixed
