### ISSUE TITLE
[Bug]: If a circle segment has not a full radius, the rendering is not correct

### ISSUE THREAD

**Issue by hellghostx** [IFCjs/web-ifc#354]
### What happened?

I have a model, which has circle segments. After a testing I was able to change some parts of the model through CIRCLE_SEGMENTS_HIGH of LoaderSettings. 

Sadly other parts are not changing and it seems in code that CIRCLE_SEGMENTS_LOW and MEDIUM are not changing anything.

Model is not mine but of a customer, so I can send it only privately to dev for development purposes only.

### Version

0.0.39

### What browsers are you seeing the problem on?

Chrome

### Anything else?

Here are pictures with segments low/medium/high:

256/256/12:
![obrazek](https://user-images.githubusercontent.com/26725817/225904670-4c854972-50b9-4941-8528-beca54c7349d.png)
5/8/12 (default):
![obrazek](https://user-images.githubusercontent.com/26725817/225904906-a5b1b418-b336-43ec-81bf-9e0f13a3c74a.png)
5/8/256:
![obrazek](https://user-images.githubusercontent.com/26725817/225905611-f2235d87-f62f-41d0-bf01-0fbe24e160d3.png)

**Comment by beachtom** [comment]
So this was an inadvertent change by me currently only circle segments high is being used. Was there value to you in being able to change them independently?

**Comment by hellghostx** [comment]
@beachtom Thank you for clarification. There are parts of the model which are not reacting to the circulation ratio so my first idea was that it is due to the LOW,MEDIUM segments. You can see them at the last picture.

However there is a lot of console output when model is parsed via web-ifc so it might be the problem with parsing, but one can never eliminate the possible problem with the model itself.

**Comment by pbbr** [comment]
@beachtom We have another topic regarding circle segments (see attached IFC). If a circle segment has not a full radius, the rendering is not correct. The number of segments doesn't solve the problem, but based on this settings the result is different.

Current result (with the latest version):
<img width="590" alt="image" src="https://user-images.githubusercontent.com/79220314/227713387-dfba3e96-7a63-4a00-bb3e-f0de87bcc973.png">

Expected result:
<img width="647" alt="image" src="https://user-images.githubusercontent.com/79220314/227713407-6abddc61-44dc-4437-b039-f591cca197c0.png">

[Segments.zip](https://github.com/IFCjs/web-ifc/files/11068696/Segments.zip)

Do you have any idea to improve this behavior? Thanks for your support!

**Comment by beachtom** [comment]
ok thanks - definitely not related to the first but will look into it

**Comment by beachtom** [comment]
Neatened up all the setting values - issue with incomplete circles still open

**Comment by QuimMoya** [comment]
![image](https://github.com/IFCjs/web-ifc/assets/12625508/381cb774-e3eb-4345-bd87-05ab0174aea7)

Seems that the issue has been inadvertently solved.
