### ISSUE TITLE
Messed-up Pipe Geometry

### ISSUE THREAD

**Issue by vulevukusej** [IFCjs/web-ifc#355]
Hey guys, the following is what I see with WIV 1.0.213:
![MicrosoftTeams-image](https://user-images.githubusercontent.com/83825269/225602096-1510f8c7-fdb7-4aab-a824-39c24ecbd020.png)
And what I see in other viewers:
![image](https://user-images.githubusercontent.com/83825269/225602191-f7c32881-9381-4900-ab42-9c5d7ef93c5c.png)

Any suggestions?  I'm happy to share the file confidentially.

**Comment by QuimMoya** [comment]
@vulevukusej 
It is dificult to say without the file. Can you share this model or part of it?

**Comment by vulevukusej** [comment]
@QuimMoya I'm happy to share the file, albeit confidentially.  Please send me an email where I can send you a link.

**Comment by QuimMoya** [comment]
@vulevukusej
ifc.js.contact@gmail.com

**Comment by szamocza** [comment]
Appears to be floating point errors.
Try to open model with ifcApi.OpenModel(..., { COORDINATE_TO_ORIGIN: true }) option.
(https://ifcjs.github.io/info/docs/Guide/web-ifc-three/api/#arguments-3)

**Comment by QuimMoya** [comment]
@vulevukusej Hey, did you send the file? or you managed to solve the problem?

**Comment by vulevukusej** [comment]
@QuimMoya sorry, I just sent an email.

**Comment by beachtom** [comment]
@vulevukusej can you take a look in the current demo viewer - it seems to be fixed now
