### ISSUE TITLE
[Feat]: UTF-8 encoding 

### ISSUE THREAD

**Issue by danieldanwii** [IFCjs/web-ifc#358]
### What is your idea?

I'm from Denmark, and we have the special characters ÆØÅ in our alphabet. Therefore we use UTF-8 encoding. 

Now my issue is that some of my property values read as for example: "Basic Wall:V\X\E6gelement 200mm:4527635", where "\X\E6" equals Æ. 

I'm guessing there midht be similar encoding issues for other languages.

**Comment by beachtom** [comment]
Are you able to share the line from the IFC model with this in? So I can see how it is serialised in IFC?

**Comment by danieldanwii** [comment]
This is the line from the ifc schema: 
#532=IFCWALLSTANDARDCASE('1Uevt2auL7RP8ZkRzzwOF8',#20,'Basic Wall:V\X\E6gelement 200mm:4469601',$,'Basic Wall:V\X\E6gelement 200mm',#520,#531,'4469601');

**Comment by danieldanwii** [comment]
There are several other instances that can be found in the file.

For example this one which contains two danish alphabet symbols: 
#14964=IFCCOLUMN('0RcpKmF$54lRMcqiFKcUlN',#20,'NO_DK_257 St\X\E5ls\X\F8jler Firkant r\X\F8r ligesidet:RHS100x100x10:4533841',$,'NO_DK_257 St\X\E5ls\X\F8jler Firkant r\X\F8r ligesidet:RHS100x100x10',#14963,#14960,'4533841');

From the cases I posted, 
"\X\E6" is "æ"
"\X\E5l" is å
"\X\F8" is ø

I'm not sure, but I assume there must be similar cases for the capitalized letters.

**Comment by beachtom** [comment]
So I think this is working in the current version of web-ifc on main here. Can you check this?
