### ISSUE TITLE
[Bug]: Wall "expands" where it should not be

### ISSUE THREAD

**Issue by hellghostx** [IFCjs/web-ifc#359]
### What happened?

In the attached pictures all pink area is part of one selected IfcWall element. 
In the first picture, there is a current state of git repo.
In second how it is in https://ifcjs.github.io/web-ifc-viewer/example/ (web-ifc 0.0.34) - Artefact at the window is not present.
In last one is how it supposed to be.

Model has been sent to your email address with this issue number in subject.

### Version

latest update of git repo

### What browsers are you seeing the problem on?

Chrome

### Anything else?

![obrazek](https://user-images.githubusercontent.com/26725817/227491646-c593035a-1cb6-4037-9b03-1638acad70da.png)

![obrazek](https://user-images.githubusercontent.com/26725817/227491770-5c2e5521-8bdf-4fc5-a801-86d7fe8e770b.png)

![obrazek](https://user-images.githubusercontent.com/26725817/227491874-b8bf687a-7c3d-4990-bdde-02dc2ba3b289.png)

**Comment by QuimMoya** [comment]
@hellghostx  Working on it

**Comment by QuimMoya** [comment]
Solved, it was caused by halfspace.
![image](https://github.com/IFCjs/web-ifc/assets/12625508/6adb2721-b40f-41d2-93ab-1906b4c3f1f1)

**Comment by QuimMoya** [comment]
The issue is solved.
