### ISSUE TITLE
Infrastructure file does not load

### ISSUE THREAD

**Issue by audeser** [IFCjs/web-ifc#361]
I can visualize it on other viewers, but file refuses to load on IFC.js
[EarthWorks.zip](https://github.com/IFCjs/web-ifc-three/files/9040040/EarthWorks.zip)
File comes from official bSI repository, so it must be legit (https://github.com/bSI-InfraRoom/IFC-infra-unit-test/tree/main/Earthworks-12d-2).

**Comment by beachtom** [comment]
This now works as well
