### ISSUE TITLE
[Bug]: Fail to GetLine on IFCCURVEBOUNDEDPLANE

### ISSUE THREAD

**Issue by perstromswe** [IFCjs/web-ifc#369]
### What happened?

It fails to parse IFCCURVEBOUNDEDPLANE

#5790=IFCCURVEBOUNDEDPLANE(#5789,#5787,$);

 try {
         row = client.GetLine(0, itemId)
      } catch (err) {
        console.log("itemId: " + itemId);
        console.log(err)
      }

### Version

0.0.39

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
itemId: 5790

TypeError: Cannot read properties of null (reading 'map')
        at Object.2827736869 (/node_modules/web-ifc/web-ifc-api-node.js:12481:115)
        at IfcAPI2.GetLine (/node_modules/web-ifc/web-ifc-api-node.js:63239:84)
        at GetLine (/../index.ts:44:23)
```

### Anything else?

Running in NodeJS

I have several files with IFCCURVEBOUNDEDPLANE which fails.

**Comment by beachtom** [comment]
This should now be fixed
