### ISSUE TITLE
[Bug]: Error when trying to load a model

### ISSUE THREAD

**Issue by LeviSTA** [IFCjs/web-ifc#372]
### What happened?

When loading a large model in firefox, we receive this error and the file doesn't load:
`UnknownError: IDBObjectStore.put: The serialized value is too large (size=388116194 bytes, max=267386880 bytes).`

### Version

v0.0.39

### What browsers are you seeing the problem on?

Firefox

**Comment by beachtom** [comment]
Can you try opening the model on the demo viewer on the repository here - and see if the error is replicated?

**Comment by LeviSTA** [comment]
> Can you try opening the model on the demo viewer on the repository here - and see if the error is replicated?

It does load there apparently, does this mean it will get fixed in the new update?

**Comment by LeviSTA** [comment]
As this is where the error is located:
![image](https://user-images.githubusercontent.com/123364333/228771425-dc3b3609-83c1-4a31-aeb1-8071fe43ca22.png)

**Comment by beachtom** [comment]
Yeah this is web-ifc-three issue. Can I suggest you open an issue there?
