### ISSUE TITLE
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

### ISSUE THREAD

**Issue by nhutruong-arent** [IFCjs/web-ifc#376]
### What happened?

When I use IFCLoader in a TypeScript React component and run the command 'yarn start', I receive a warning.

![image](https://user-images.githubusercontent.com/99541143/230780185-78a133d9-0e34-4da5-8818-fe6d8c25bc53.png)

### Version

"web-ifc": "0.0.39", "web-ifc-three": "0.0.124", "web-ifc-viewer": "1.0.214",

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
Compiled with warnings.

Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.

WARNING in ./node_modules/web-ifc/web-ifc-api.js 21:70-77
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./node_modules/web-ifc/web-ifc-api.js 24:45-52
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

webpack compiled with 2 warnings
Files successfully emitted, waiting for typecheck results...
Issues checking in progress...
No issues found.
```

### Anything else?
Expected behavior
Compiled successfully!

You can now view beycons-frontend in the browser.

  Local:            http://localhost:3000        
  On Your Network:  http://xxxx:3000     

Note that the development build is not optimized.
To create a production build, use yarn build.    

webpack compiled successfully
No issues found.

**Comment by beachtom** [comment]
I am honestly not sure if there is anything we can change here. In any case are these not warnings so it should still compile? The lines it is complaining about are part of ESBuild generated code and not our code. I not honestly sure how to turn them off without breaking stuff for others who require them. Happy to discuss if anyone is more knoweldgeable about JS bundling than myself

**Comment by frading** [comment]
I'm hitting the same problem when trying to build web-ifc with webpack. And I agree, since it's a warning, it should still be possible to run the app, but in my case, those warnings remain on top of the screen. This could be due to webpack-dev-server. I plan to look into this deeper in the coming days, but curious to hear any ideas of what could be tried to go around this.

**Comment by beachtom** [comment]
So I did searching into this. The code that is causing the warning is generated by ESbuild and there seems to be no way to turn it off. Is there a way to disable the webpack warning? I can't find much about turning off this code generation is ESBuild itself

**Comment by frading** [comment]
Thanks a lot for your quick answer @beachtom . And I've found 2 possible options that could solve this on webpack's side:

- the option `unknownContextCritical` ( https://webpack.js.org/configuration/module/ ), but I haven't yet found a way to have that applied only to web-ifc
- the option `ignoreWarnings`, which seems more sensible in this case, and can easily be applied to a single module. This is the one I went with for now ( see https://github.com/polygonjs/polygonjs/blob/master/config/webpack/common.js#L108 )

```
ignoreWarnings: [
			{
				module: /web-ifc/,
				message: /require function is used in a way in which dependencies cannot be statically extracted/,
			},
		],
```

**Comment by beachtom** [comment]
I'm going to leave this open - as there is probably more we can do to make our bundling more best practice - but I will need to come back to this,

**Comment by beachtom** [comment]
Do you have a minimal repo that replicates this. I am am not 100% familiar with webpack so I am wanting to do some experiments with a few bundling changes

**Comment by beachtom** [comment]
I have improved the bundling so this should now be fixed
