### ISSUE TITLE
[Bug]: Can't resolve 'perf_hooks' in '.../node_modules/web-ifc'

### ISSUE THREAD

**Issue by lukasvdelft** [IFCjs/web-ifc#377]
### What happened?

I encounter the following (Chrome browser):
ERROR in ./node_modules/web-ifc/web-ifc-api-node.js 2:4676-4709
Module not found: Error: Can't resolve 'perf_hooks' in '.../node_modules/web-ifc'

This happens when I try: let lines = ifcApi.GetLineIDsWithType(modelID, WebIFC.IFCPROPERTYSET)
it does not happen when the type used for instance is IFCRELDEFINESBYPROPERTIES

I am running web-ifc in a Vue/Typescript(v4.5.5) context, npm version 9.5.1.
I tried installing perf-hooks but this is not changing the outcome.

### Version

0.0.39

**Comment by beachtom** [comment]
Can you share some code?

**Comment by lukasvdelft** [comment]
const ifcApi = new IfcAPI()

        async function initIfc() {
            
            ifcApi.Init()
            const ifcData = await getIfcFile('20221221_Boelelaan_1117_Amsterdam_2023_L7.ifc') as Uint8Array
            const modelID = ifcApi.OpenModel(ifcData)
            doTest(modelID, IFCWALL)
            ifcApi.CloseModel(modelID);
        }

        function getIfcFile(url: string) {
            return new Promise((resolve, reject) => {
                var oReq = new XMLHttpRequest();
                oReq.responseType = "arraybuffer";
                oReq.addEventListener("load", () => {
                    resolve(new Uint8Array(oReq.response));
                });
                oReq.open("GET", url);
                oReq.send();
            });
        }

        function doTest(modelID: number, type: any): boolean {
        
            let types = ifcApi.GetIfcEntityList(modelID).filter((f) => (f !== WebIFC.IFCPROPERTYSET && ifcApi.IsIfcElement(f)));
            console.log(types)

            return true
        }

**Comment by lukasvdelft** [comment]
or this doTest function has the same result.

function doTest(modelID: number, type: any): boolean {
        
            let lines = ifcApi.GetLineIDsWithType(modelID, WebIFC.IFCPROPERTYSET)
            console.log(lines)

            return true
        }

**Comment by beachtom** [comment]
Is this in browser or in Node? What version of node are you using?

**Comment by lukasvdelft** [comment]
Node v19.8.1. So I am working in a Vue context and the code runs in a Vue (3) component (Typescript, composition API). The errors are shown in a browser (Chrome).
What I also see is that if I use for instance IFCPROPERTYSET directly, imported from 'web-ifc/web-ifc-api' the error is gone. I am new to this environment, so I don't know the difference yet between WebIFC.IFCPROPERTYSET and IFCPROPERTYSET. In the latter case I do see limited result (only one ifcpropertyset is returned, and there are many more).

**Comment by beachtom** [comment]
Can you share the exact import files you are using?

**Comment by lukasvdelft** [comment]
Do you mean the ifc file itself? I can share but not on a public platform, it is data from an academic hospital.

the other imports are:
import { defineComponent } from 'vue'
import { IfcAPI, IFCSPACE, IFCWALL, IFCCOLUMN, IFCPROPERTYSET, IFCRELDEFINESBYPROPERTIES } from 'web-ifc/web-ifc-api'
import * as WebIFC from 'web-ifc/web-ifc-api-node'

**Comment by beachtom** [comment]
can you try 
import { IfcAPI, IFCSPACE, IFCWALL, IFCCOLUMN, IFCPROPERTYSET, IFCRELDEFINESBYPROPERTIES } from 'web-ifc'

**Comment by lukasvdelft** [comment]
yes i did, same outcome

**Comment by beachtom** [comment]
In that case i will continue testing - but at the moment I cannot replicate this,

**Comment by lukasvdelft** [comment]
Tom, the strange thing is, I can't explain but now your suggestion (using only 'web-ifc') does work. So if I find out why, I will let you know. For now, this bug can be closed I would say. Thanks for the quick response.

**Comment by beachtom** [comment]
Hi, really odd..... - please let me know if you figure out what was happening!
