### ISSUE TITLE
[Bug]: Number in scientific notation written with a trailing point

### ISSUE THREAD

**Issue by jonathan-buildrz** [IFCjs/web-ifc#387]
### What happened?

Here is an example of an owner history, where the timestamp is a big number :
#5=IFCOWNERHISTORY(#3,#4,$,.NOCHANGE.,$,$,$,1.6831E+09.);
We see that there is a trailing point after the timestamp, like smaller integer numbers (which previous versions didn't write). Because of that, the solibri viewer refused to open the file (while precisely pointing the problem)
I'm not even sure this timestamp should be written in scientific notation, so maybe we have 2 problems there ?

### Version

0.039

### What browsers are you seeing the problem on?

Chrome

**Comment by beachtom** [comment]
Hi, this is now fixes
