### ISSUE TITLE
[Bug]: Release tag 0.40 does not match with the version in package.json

### ISSUE THREAD

**Issue by jespa007** [IFCjs/web-ifc#389]
### What happened?

Release 0.40 does not match with package.json (it has a value of 0.0.39). With this mismatch can become confusions to developers when anyone is complaining about error using the version that currently is using.

### Version

0.0.40

### Relevant log output

```shell
If I execute GetVersion() from web_ifc API it returns 0.0.39
```

### Anything else?

May be it could improve that issue through and script that updates package.json before create a tag in github ?

**Comment by beachtom** [comment]
Can I ask you to check if there is any caching going on? I've downloaded the wasm from NPM and I can see the 0.0.40 string inside of it?

**Comment by jespa007** [comment]
Hi @beachtom ,
I downloaded the tar.gz from releases and the package.json tells the version as 0.0.39

![image](https://github.com/IFCjs/web-ifc/assets/7852409/95e414d6-af57-422e-a873-828ef88843bd)


![image](https://github.com/IFCjs/web-ifc/assets/7852409/bda05a96-850b-4f15-b173-53c565dfda07)

**Comment by beachtom** [comment]
This is fixed now - so it won't happen again
