### ISSUE TITLE
Find object knowing only GlobalID

### ISSUE THREAD

**Issue by JoanDuatis** [IFCjs/web-ifc#393]
Hello,
does anyone know if there is any function or method to find an object knowing only its GlobalID?

**Comment by beachtom** [comment]
So there is CreateIfcGuidToExpressIdMapping(modelID)

If you call this this will populate ifcapi.ifcGuidMap

You should be able to then do ifcapi.ifcGuidMap[modelId][globalID] to get the express ID

**Comment by JoanDuatis** [comment]
I can't access the createIfcGuidToExpressIdMapping function.
I have tried it in many ways but I always get the error that it is not a function:
examples:

viewer. createIfcGuidToExpressIdMapping(model.modelID);
viewer.IFC.createIfcGuidToExpressIdMapping(model.modelID);
ifcApi.createIfcGuidToExpressIdMapping(model.modelID);

Can you put how this function is accessed from WIV ?

**Comment by JoanDuatis** [comment]
I know how to get to the function from WIV.

This is the way:

viewer.IFC.loader.ifcManager.ifcAPI.CreateIfcGuidToExpressIdMapping(modelID);

**Comment by JoanDuatis** [comment]
Now that I've managed to create the map between expressID and globalID, I can't access ifcGuidMap.

I get the following error:

![image](https://github.com/IFCjs/web-ifc/assets/130443866/64d57baf-208e-45ed-bf60-01521d6c0448)


What am I doing wrong?

**Comment by beachtom** [comment]
Should it just be [obj] not [obj.guid].

The screenshot seems to suggest obj is the guid.

**Comment by JoanDuatis** [comment]
I understand that ifcGuidMap requires a modelID and a GlobalID. obj.guid has the value of a globalID and should work.
Anyway I have tried using a string variable with the value of a globalID and it keeps showing the same error:

![image](https://github.com/IFCjs/web-ifc/assets/130443866/293ee300-adef-4cd8-94f8-ae7d7b5339f2)

**Comment by JoanDuatis** [comment]
Looking at how the CreateIfcGuidToExpressIdMapping function is implemented, I have observed that it generates a map for each model. It is a map within another map.

So I have come up with the solution: first I get the map from the model and then I look for the GlobalID in this last map.

I'll write down the solution in case someone else has the same thing happen to me:

     var map = viewer.IFC.loader.ifcManager.ifcAPI.ifcGuidMap.get(model.modelID);
     const expressID = map.get(globalID);

**Comment by beachtom** [comment]
I think this is not very to use. I will write a function to help with using this map

**Comment by EngelbertTeh** [comment]
There's no such ifcguidmap()..

**Comment by beachtom** [comment]
So in the latest version there is a function 
viewer.IFC.loader.ifcManager.ifcAPI. GetExpressIdFromGuid(modelID: number, guid: string)
and

viewer.IFC.loader.ifcManager.ifcAPI. GetGuidFromExpressId(modelID: number, expressID: number)
