### ISSUE TITLE
Geometry displays incorrectly

### ISSUE THREAD

**Issue by JoanDuatis** [IFCjs/web-ifc#394]
The attached ifc file does not show the geometry correctly.

The image on the right is the one generated by BIMVISION and is correct. The one on the left is the one that is generated with the viewer that we have in:

https://ifcjs.github.io/web-ifc-viewer/example/index

![image](https://github.com/IFCjs/web-ifc-viewer/assets/130443866/932f97e5-d8f3-46a4-a58f-a561cc08006a)

[TERRENO_02 Pavimentación.zip](https://github.com/IFCjs/web-ifc-viewer/files/11461103/TERRENO_02.Pavimentacion.zip)

**Comment by QuimMoya** [comment]
Solved

I have to review that but ... at the moment it is solved

![image](https://github.com/IFCjs/web-ifc/assets/12625508/b4c94d21-fddb-423c-9beb-994c641a37e0)

**Comment by JoanDuatis** [comment]
It's very nice. The image that you have put is the geometry that should show

**Comment by QuimMoya** [comment]
![image](https://github.com/IFCjs/web-ifc/assets/12625508/b3d4f01b-5106-4fe4-9409-5f9be7ad8086)
This is the final update on the issue. I have addressed various complications and made attempts to resolve them. I believe the problem has been resolved successfully and it is now functioning as intended.

**Comment by JoanDuatis** [comment]
Sorry, I'm a beginner. 
I don't know how I can update the libraries with these corrections and try it

**Comment by QuimMoya** [comment]
@JoanDuatis  Contact me directly in discord Quim#3042
