### ISSUE TITLE
[Bug]: Geometry: Missing wall openings (booleans) in 0.0.39-0.0.41

### ISSUE THREAD

**Issue by andy-wrks** [IFCjs/web-ifc#398]
### What happened?

The attached walls show up without openings, so the windows are not visible.
This happens in 0.0.39 and in the newest version 0.0.41 here https://ifcjs.github.io/web-ifc/demo/
Additional note: The building elements (walls and windows) in the sample file don't have proper Ifc classes (all IfcBuildingElementProxy). I don't have the original model to fix this.

Result in 0.0.39:
![image](https://github.com/IFCjs/web-ifc/assets/111515188/8ae4bd01-2ef5-4f2b-8f02-078997563753)

Result in 0.0.41 from https://ifcjs.github.io/web-ifc/demo/
Note: The windows where the booleans worked have correct transparency compared to 0.0.39 above
![image](https://github.com/IFCjs/web-ifc/assets/111515188/cb94cf50-1331-4005-8547-038804f6d4c7)

Expected (BIMcollab):
![image](https://github.com/IFCjs/web-ifc/assets/111515188/9de95a72-7e5e-4a7b-9adb-f29a42291c3c)

Sample file:
[Wall_samples.zip](https://github.com/IFCjs/web-ifc/files/11487696/Wall_samples.zip)

### Version

0.0.39 and latest version 0.0.41 deployed here: https://ifcjs.github.io/web-ifc/demo/

### What browsers are you seeing the problem on?

Chrome

**Comment by QuimMoya** [comment]
with the help of @beachtom we solved the issue, in the next days we will upload the fix.
![image](https://github.com/IFCjs/web-ifc/assets/12625508/28f3f4c4-a2c7-4c16-9b89-d4b8465ec517)

**Comment by beachtom** [comment]
Fix is merged
