### ISSUE TITLE
[Bug]: Format output of "build-web-ifc-api-browser" was been changed from "iife" to "esm"

### ISSUE THREAD

**Issue by jespa007** [IFCjs/web-ifc#400]
### What happened?

In the current `package.json`, "build-web-ifc-api-browser" output format is transpiled as esm, but previous versions it was transpiled as iife (or UMD). Also `dist/web-ifc-api-browser.js` file is not generated anymore.

Is there any reason about this change? I write this because I'm using iife or UMD in my project.

Thanks

### Version

0.0.41

**Comment by beachtom** [comment]
So I was trying to refine our build - because the wasm integration generates some node specific code that causes webpack issues part of that I remove iife as based on research it was not used that commonly. I can re-added - but I am just wondering what your use case for use?

**Comment by jespa007** [comment]
Thanks @beachtom for you response

I'm may be one of the few people that still it uses UMD. I'm not using ESM in my project and also I am not "bundlering" the project due we have other way to release of js, css, images, etc. 

If the generating of the file "iife" it generates some troubles in webpack, it could be generated by demand (i.e not included in the `npm run build-release`) and in other directory to avoid affects webpack proces. ?

**Comment by beachtom** [comment]
So readding the file is easy - the issue is making sure bundlers dont use it.

How do you refer to the UMD file? Directly by its filename

**Comment by beachtom** [comment]
So for now I added the iife output back in - but it doesn't go into the NPM releases for now - does this work for you?

**Comment by jespa007** [comment]
Hi @beachtom ,
Yes, I referencing wef-ifc-api-browser.js by its filename in the html. The way you mention It should works perfectly. I don't use npm package, I always building web-ifc / web-ifc-three seperately from its source code :-). Thanks!

**Comment by beachtom** [comment]
Ok great - this can be closed then
