### ISSUE TITLE
[Bug]: web-ifc not parsing IFC Railing

### ISSUE THREAD

**Issue by MarinLjuban** [IFCjs/web-ifc#403]
### What happened?

While using web-ifc, parsing does not output IFC Railing entity. The entity is defined in the IFC-STEP with the HANDRAIL enumeration. And it is tried to reach the entity via IfcRelDefinesByType relationship. However, direct reaching for the IfcRailing returns it.
The tested file and the script are attached.
[railingIssue.zip](https://github.com/IFCjs/web-ifc/files/11583060/railingIssue.zip)

### Version

0.0.40

**Comment by beachtom** [comment]
Hi, can you share a screenshot or some code of what you are trying to do and the output you get?

**Comment by MarinLjuban** [comment]
After going thought the IFC-STEP file, this issue seems to be there (the reference is not in it, therefore cannot be parsed by web-ifc). Whether it is a bad implementation in the authoring tool or just the way IFC works I am not sure. It is not however an issue with web-ifc. Sorry for false alarm
