### ISSUE TITLE
[Question]: How can I remove property set via web-ifc?

### ISSUE THREAD

**Issue by LukasKStavario** [IFCjs/web-ifc#404]
Hi I want to make export plugin that change structure of my PropertySets, how to remove original ones and save file?

**Comment by beachtom** [comment]
So we can't actually remove an IFC entity right now (issue #327) is waiting for an enhancement to do that.

I will probably be looking at it myself in the next week or so.

**Comment by LukasKStavario** [comment]
Thank you, I will look at issue you mentioned.
