### ISSUE TITLE
Examples about creating IFC files

### ISSUE THREAD

**Issue by KennanChan** [IFCjs/web-ifc#405]
I'd like to use web-ifc to create a new ifc file and upload it to the server. There seems to be no material about model creation. I tried some apis in the demo website but failed to make things right.

I want to create some extrusions. Are there any detailed documentations on creating models?

**Comment by RyugaRyuzaki** [comment]
Hi, may be this can help you :https://ifcjs.github.io/web-ifc/demo/

**Comment by KennanChan** [comment]
Cool, the default code in the demo helped a lot.
