### ISSUE TITLE
[Bug]: Encoding of special characters "eats" the following character

### ISSUE THREAD

**Issue by jonathan-buildrz** [IFCjs/web-ifc#406]
### What happened?

If I pass "bâtiment" (building in french) as the name of the IFC building, the "â" gets encoded but the t after it disappears :

`#133=IFCBUILDING('8450af4f-0571-48d6-a17a-d4183b786d44',#5,'b\X2\00E2\X0\iment',$,$,#132,$,$,.ELEMENT.,$,$,$);`

If I pass only "ât", only the encoded character is left :

`#133=IFCBUILDING('f7fb95db-5862-4094-80ef-5d83550da581',#5,'\X2\00E2\X0\',$,$,#132,$,$,.ELEMENT.,$,$,$);`

Strangely, if I pass only "tâ", the encoded character disappears :

`#133=IFCBUILDING('127a0c2e-5a72-4692-bd6c-55213739b3cd',#5,'t',$,$,#132,$,$,.ELEMENT.,$,$,$);`

### Version

0.040

### What browsers are you seeing the problem on?

Chrome

**Comment by beachtom** [comment]
This should now be fixed
