### ISSUE TITLE
[Bug]: IFCCURTAINWALLS element types are displaced

### ISSUE THREAD

**Issue by jespa007** [IFCjs/web-ifc#408]
### What happened?

After load a model, all elements as IFCCURTAINWALL types are displaced

![image](https://github.com/IFCjs/web-ifc/assets/7852409/bd7fd51b-f6f3-4a42-ab8c-ec97333b98e7)

### Version

0.0.42

### What browsers are you seeing the problem on?

Chrome

**Comment by beachtom** [comment]
Can you try again - I think we had a fix we put up yesterday that went wrong. Fixed now - I hope.
