### ISSUE TITLE
Normal component of vertex data

### ISSUE THREAD

**Issue by CBenghi** [IFCjs/web-ifc#412]
Hello,
in the past days I've been compiling the project to learn more about it.
I'm liking your work and I will probably be able to push a few contributions to the codebase in the coming weeks.

Anyway, I wanted to warn you about an upcoming breaking change in fuzzy-bool.

They are changing the code to remove normal component from vertices at:

https://github.com/tomvandig/fuzzy-bools/commit/d4dde4d94871d44960dd1569307adff3561bdff6#diff-069768902fcf3c730c12400c2f4e7eb368c4017809750c198cea17d1966e6b91

I'm not familiar enough with your codebase to see if this is a big problem, and I see two options:

1. If normals are required for web-ifc I am happy to write a PR for them to make that change configurable via a define, or
2. If you don't need normal I can write a PR for your codebase that complies with the change they made to the vertex data.

Any thoughts?
Best,
Claudio

**Comment by beachtom** [comment]
Hi Claudio,

I remember working with you many years ago now.

So this library itself does not use the normals for anything - but we do pass them back to the javascript and I guess web-ifc-three. We would need to try and see how this will effect things. I am not sure what the best approach would be at the moment

I guess if it changes/nothing/ little we can just remove them from our end  - but we do calculate the normals when parsing from IFC - so we may want to look to see if we can maintain them through boolean operations - but I am unsure the best approach for this right now

**Comment by CBenghi** [comment]
Hi Tom, good to see you here. It has been a long while.
I figured something of this sort, but I'm not yet familiar with the codebase to consider all the consequences.
I suppose one option could be to propose to @tomvandig a PR that allows us to retain normals in the library with an `#ifdef` condition.
I'd be happy to do that if it considered useful.

**Comment by beachtom** [comment]
I spoke to the author of fuzzy bools - it is a temporary change and will be back.

So I will close this for now - but happy to discuss and receive PRs. If you want to contribute, let me know, and I can fill you in on what is in progress.

**Comment by CBenghi** [comment]
Excellent, thanks.
I've sent an email to ask for a quick call.
