### ISSUE TITLE
[Bug]: Some IFC has IfcRelAssociatesMaterial entities with no RelatedObjects property

### ISSUE THREAD

**Issue by jespa007** [IFCjs/web-ifc#414]
### What happened?

	

In the standard Schema 2x3 `IfcRelAssociatesMaterial` is described as,

```
ENTITY IfcRelAssociatesMaterial;
	ENTITY IfcRoot;
		GlobalId	 : 	IfcGloballyUniqueId;
		OwnerHistory	 : 	IfcOwnerHistory;
		Name	 : 	OPTIONAL IfcLabel;
		Description	 : 	OPTIONAL IfcText;
	ENTITY IfcRelationship;
	ENTITY IfcRelAssociates;
		RelatedObjects	 : 	SET [1:?] OF IfcRoot;
	ENTITY IfcRelAssociatesMaterial;
		RelatingMaterial	 : 	IfcMaterialSelect;
END_ENTITY;
```

It explains that `RelatedObjects`  goes from [1:?], so it tells that it will have as a minimum ONE releated object. However I found some IFCs that has no `RelatedObjects` properties and when I request `IfcRelAssociatesMaterial` entity through web-ifc `GetLine`, because ReleatedObjects that represents the v[4] is null, the program it crashes.

```
FromRawLineData[1] = {
	...
        // IfcRelAssociatesMaterial is represented as `2655215786` as internal id
	2655215786: (id, v) => new IFC2X3.IfcRelAssociatesMaterial(
		id
		, new IFC2X3.IfcGloballyUniqueId(v[0].value) 
		, new Handle(v[1].value) 
		, !v[2] ? null : new IFC2X3.IfcLabel(v[2].value) 
		, !v[3] ? null : new IFC2X3.IfcText(v[3].value) 
		, v[4].map((p) => new Handle(p.value))  // ---> Here v[4] is null so it crash!
		, new Handle(v[5].value) 
	),
	....
}
```

May be is a thing of bad exporting of the IFC.

### Version

0.0.42

### What browsers are you seeing the problem on?

Chrome

### Anything else?

Maybe It can solve this problem be avoided by just put `!v[4] ? null :  v[4].map((p) => new Handle(p.value))`. 
But in anycase maybe is something wrong from the software that exports the IFC file.

**Comment by beachtom** [comment]
Can you share a file that has this issue? Also what error occurs you get when it does crash

**Comment by jespa007** [comment]
Hi @beachtom,

Here it goes,

[Test_Materials_2022.zip](https://github.com/IFCjs/web-ifc/files/11690466/Test_Materials_2022.zip)

If you tries to load the model, and then get the all elements of type `IFCRELASSOCIATESMATERIAL` and try to get each lines it crashes by error described at the begin of this thread,

```
let ifc_rel_defines_by_types = await this.ifc_api.GetLineIDsWithType(model_id, WebIFC.IFCRELASSOCIATESMATERIAL);
for(let i=0; i < ifc_rel_defines_by_types.size(); i++){
      let ifc_rel_defines_by_type=await this.ifc_api.GetLine(model_id,ifc_rel_defines_by_types.get(i)); //<-- it crashes
       // ...
}
```

The thing is that the last line of the model _Test_Materials_2022.ifc_ it has an element IFCRELASSOCIATESMATERIAL with the following content,

```
...
#59994= IFCRELASSOCIATESMATERIAL('1T4sONh1X1$ul3G7Fqu6eB',#20,$,$,$,#59995);
...
```
As you can see in the ifc entity, it has no related objects (i.e it has the symbol $) . This file was exported by REVIT 2022. 
As I told, the standard tells that it have to have at least 1 element as minimum but in this case it haven't. 
So .... In don't know if web-ifc can solve this error in somehow or we have to live with because it does not follow the standard.

**Comment by beachtom** [comment]
So you're right, it is invalid.

What I'm doing is added some error handling, so it logs the error and will not kill the program.
