### ISSUE TITLE
[Bug]: GetLine fails with IfcRelConnectsPathElements

### ISSUE THREAD

**Issue by MadsHolten** [IFCjs/web-ifc#415]
### What happened?

I'm getting a `TypeError: Cannot read properties of null (reading 'map')` when getting properties of lines of the type IfcRelConnectsPathElements.

My quick and dirty quick fix for now is to just add question marks to the method in the bundle file:

Before:
```javascript
  3945020480: (id, v) => new IFC2X3.IfcRelConnectsPathElements(id, new IFC2X3.IfcGloballyUniqueId(v[0].value), new Handle(v[1].value), !v[2] ? null : new IFC2X3.IfcLabel(v[2].value), !v[3] ? null : new IFC2X3.IfcText(v[3].value), !v[4] ? null : new Handle(v[4].value), new Handle(v[5].value), new Handle(v[6].value), v[7].map((p) => p.value), v[8].map((p) => p.value), v[9], v[10]),
```

After:
```javascript
  3945020480: (id, v) => new IFC2X3.IfcRelConnectsPathElements(id, new IFC2X3.IfcGloballyUniqueId(v[0].value), new Handle(v[1].value), !v[2] ? null : new IFC2X3.IfcLabel(v[2].value), !v[3] ? null : new IFC2X3.IfcText(v[3].value), !v[4] ? null : new Handle(v[4].value), new Handle(v[5].value), new Handle(v[6].value), v[7]?.map((p) => p.value), v[8]?.map((p) => p.value), v[9], v[10]),
```

I suppose that it's due to an optional parameter being perceived as mandatory, but not sure how it should be fixed?

### Version

0.0.41

**Comment by MadsHolten** [comment]
[Here](https://github.com/LBD-Hackers/LBD-app-tutorial/blob/BUG/index.html) is an example that will throw the error.

[Here](https://github.com/LBD-Hackers/LBD-app-tutorial/blob/BUG/index.html) is an example where the bug is gone due to my hardcoded fix.

Tested with [this modell](https://raw.githubusercontent.com/MadsHolten/BOT-Duplex-house/master/Model%20files/IFC/Duplex.ifc)

**Comment by beachtom** [comment]
Ahh - this wasn't picking up the optionality in the schema. I've just fixed it!
