### ISSUE TITLE
[Bug]: Infinite loading time (probably due to solids)

### ISSUE THREAD

**Issue by agviegas** [IFCjs/web-ifc#416]
### What happened?

Loading an IFC model results in infinite loading time, probably due to geometry generation. I added the model to the SOLIDOS folder with the name 416.ifc.

### Version

0.0.41

### What browsers are you seeing the problem on?

Chrome

**Comment by QuimMoya** [comment]
![image](https://github.com/IFCjs/web-ifc/assets/12625508/7a75e6c7-a0bb-43ce-a49a-b10b5f0fc561)
It is working on my computer...
