### ISSUE TITLE
[Bug]: npm package not imported

### ISSUE THREAD

**Issue by g-rodigy** [IFCjs/web-ifc#417]
### What happened?

I tried to reproduce [example](https://ifcjs.github.io/info/docs/Guide/web-ifc/Tutorials/Hello%20world/) for version 0.0.41, but got error while compile bundle by rollup.
````js
import {IfcAPI} from "web-ifc/web-ifc-api";
.....
````

### Version

0.0.41

### Relevant log output

```shell
(!) Plugin node-resolve: Could not resolve import "web-ifc/web-ifc-api" in ... using exports defined in .../node_modules/web-ifc/package.json.
```

**Comment by g-rodigy** [comment]
> import {IfcAPI} from "web-ifc"

It work

**Comment by beachtom** [comment]
Thank you. I have passed this over to be changed in the documentation
