### ISSUE TITLE
[Bug]: Model gets empty mesh geometry due to ifcindexedpolycurve 

### ISSUE THREAD

**Issue by hellghostx** [IFCjs/web-ifc#420]
### What happened?

Greetings,

Model which has been sent to you into [ifc.js.contact@gmail.com](mailto:ifc.js.contact@gmail.com) returns "ERROR: Parsing ifcindexedpolycurve in 3D is not possible" that results in empty geometry structure of meshes. 

![obrazek](https://github.com/IFCjs/web-ifc/assets/26725817/986bf538-650a-4bc7-b7d6-1b033ae3e329)

I have checked this ifc with other softwares like BIMVision and it looks like this without any error given:

![obrazek](https://github.com/IFCjs/web-ifc/assets/26725817/05fb41da-f8d2-4ae0-825b-efb30e2a2b20)

If current situation is that web-ifc is just not supporting parsing those elements ("in 3D is not possible" might indicate that it is currently not supported or it cannot be done), then please feel free to change this into feature request.

### Version

0.0.41

### What browsers are you seeing the problem on?

Chrome

**Comment by QuimMoya** [comment]
I will take a look on it

**Comment by QuimMoya** [comment]
![image](https://github.com/IFCjs/web-ifc/assets/12625508/ba76fe8c-0cd7-42be-9b76-7ff469b37e9b)
solved
