### ISSUE TITLE
[Bug]: IfcCompoundPlaneAngleMeasure not written correctly in IfcSite

### ISSUE THREAD

**Issue by jonathan-buildrz** [IFCjs/web-ifc#421]
### What happened?

If I'm passing IfcCompoundPlaneAngleMeasure to IfcSite for the RefLatitude and RefLongitude:
```
    return new WebIfc.IFC2X3.IfcSite(
     [10 arguments skipped for brevity]

      new WebIfc.IFC2X3.IfcCompoundPlaneAngleMeasure([48, 10, 20, 30]),

      new WebIfc.IFC2X3.IfcCompoundPlaneAngleMeasure([2, 40, 50, 60]),

      new WebIfc.IFC2X3.IfcLengthMeasure(0),
      null,
      null
    );
```
Then in the resulting ifc file, the values aren't even there (they should be after .COMPLEX.):
`#118=IFCSITE('00000000-0000-4000-8000-000000000001',#5,'Project site',$,$,#47,#117,$,.COMPLEX.,0.,$,$);`
And I get the following log in the console when writing the IfcSite line (2 times, one for each IfcCompoundPlaneAngleMeasure I guess):
`instrument.js:109 ERROR: Error in writeline: unknown object received`

If I work around that by passing an array of IfcReal (or IfcInteger, doesn't matter):
```
    return new WebIfc.IFC2X3.IfcSite(
     [10 arguments skipped for brevity]

      [48, 10, 20, 30].map(
        n => new WebIfc.IFC2X3.IfcReal(n)
      ) as unknown as WebIfc.IFC2X3.IfcCompoundPlaneAngleMeasure,

      [2, 40, 50, 60].map(
        n => new WebIfc.IFC2X3.IfcReal(n)
      ) as unknown as WebIfc.IFC2X3.IfcCompoundPlaneAngleMeasure,
      
      new WebIfc.IFC2X3.IfcLengthMeasure(0),
      null,
      null
    );
```
Then in the resulting ifc file, the values are written:
`#118=IFCSITE('00000000-0000-4000-8000-000000000001',#5,'Project site',$,$,#47,#117,$,.COMPLEX.,(48.,10.,20.,30.),(2.,40.,50.,60.),0.,$,$);`
and the error log isn't present.

(As those numbers are integers in the IFC specification I think there shouldn't be a trailing point but that will be the subject of a different bug report).

### Version

0.0.41

### What browsers are you seeing the problem on?

Chrome

**Comment by beachtom** [comment]
This should now be fixed! - Still thinking about how to fix the issues with the decimal points though!
