### ISSUE TITLE
[Bug]: Issues with geometry of an IFC

### ISSUE THREAD

**Issue by FirebirdCS** [IFCjs/web-ifc#423]
### What happened?

[](url)Hi I finished the advanced course of IFC.js using react. I managed to load differents IFC without errors except this one. There is parts of the IFC that are missing from the model. If I use the web-ifc demo the parts are showing perfectly.  I'm using the latest openbim-components package showed in the course (0.0.51) that has web-ifc version 0.0.36. 

![ifc1](https://github.com/IFCjs/web-ifc/assets/70920440/74bc956e-c25c-4e1c-a15e-53d7cfe56e0a)
![ifc2](https://github.com/IFCjs/web-ifc/assets/70920440/08e6c9ff-4082-450b-9c49-bf61a463b8f5)

### Version

0.0.36

### What browsers are you seeing the problem on?

Firefox, Chrome

### Anything else?

[CBAYO-BCA-ZZ-ZZ-MC-A-0002.zip](https://github.com/IFCjs/web-ifc/files/11821576/CBAYO-BCA-ZZ-ZZ-MC-A-0002.zip)

**Comment by QuimMoya** [comment]
![image](https://github.com/IFCjs/web-ifc/assets/12625508/be4c9a93-2e2f-4b41-93a5-e6ecfb049005)
I opened the model and this is what i obtain.

**Comment by FirebirdCS** [comment]
> ![image](https://user-images.githubusercontent.com/12625508/249392421-be4c9a93-2e2f-4b41-93a5-e6ecfb049005.png) I opened the model and this is what i obtain.

Yes this the normal behaviour that I am expecting, but this is tested in the web-ifc demo page like I did. Im using the openbim-components package version 0.0.51 which includes the version 0.0.36 of web-ifc. I tried using an alpha version of openbim-components which has a newer version of web-ifc (0.0.41) but It gives me a bunch of errors.

**Comment by beachtom** [comment]
@FirebirdCS just looked at this myself it seems that it is an issue in the open-bim components library. Can you open an issue there?
