### ISSUE TITLE
[Bug]: Can't load ifc files that are originally a dwg format [Exported from Autocad]

### ISSUE THREAD

**Issue by MiguelG97** [IFCjs/web-ifc#428]
### What happened?

I wish to export 2d floorplans from a dwg format into an IFC files and load it in the IFC viewer. However, a dialog error console 
 shows up and perhaps it's related with cad entities:

![image](https://github.com/IFCjs/web-ifc/assets/78984964/665dd599-b5ca-4eef-b6c2-0962be44e0a4)

Link to the sample files:
https://drive.google.com/drive/folders/1nQQJVLWHGw0kLYgXPhd6MnKzCfJonYCb?usp=drive_link

### Version

0.0.39

### What browsers are you seeing the problem on?

Chrome

**Comment by beachtom** [comment]
I have just requested access to this can you grant it

**Comment by MiguelG97** [comment]
My bad, everyone has access to the folder drive now

**Comment by beachtom** [comment]
OK so this file actually contains 0 pieces of geometry. It parses on in web-ifc but returns 0 items of geometry.

The issue is I think in web-ifc-viewer - in that it assumes an IFC file always has at least one item of geometry - but the fact nothing appears on screen is actually correct for what the file is

**Comment by miguelGTailorbird** [comment]
Thanks for taking ownership of this one!

Indeed, it contains 0 geometry as its a pure DWG drawing made out of polylines, blocks, etc exported into an IFC file. 
Most of our contractors work directly with Autocad and it might be convenient to process autocad entities. 
This was the request, to process DWG entities actually. Is it something that goes out of the scope of IFC?

**Comment by MiguelG97** [comment]
Thanks for taking ownership of this one!

Indeed, it contains 0 geometry as its a pure DWG drawing made out of polylines, blocks, etc exported into an IFC file.
Most of our contractors work directly with Autocad and it might be convenient to process autocad entities.
This was the request, to process DWG entities actually. Is it something that goes out of the scope of IFC?

**Comment by beachtom** [comment]
So I think if anything this is a pure export issue.

We can't do 2D only files at the moment as they are rare - but it is something for the future.

However, this file doesn't even contain any 2D geometry at all - it contains 2x X,Y,Z coordinates ( both of which are 0,0,0) - so there is nothing in it to draw.

You may be able to work with autocad to get it export better - but I am not sure how I am afraid.

**Comment by MiguelG97** [comment]
Indeed, the IFC exporter seems to not support 2D lines (polylines, arcs, block referecens with 2D data, etc.). It only read 3d object data apparently.

![image](https://github.com/IFCjs/web-ifc/assets/78984964/1f358723-d81d-4901-a7f4-7a89f824fb2c)

**Comment by MiguelG97** [comment]
How Forge Viewer manage to parse 2D DWG rough data into the viewer? 
Do you suggest any workaround to achieve the same goal?

Best regards
Miguel G.

**Comment by beachtom** [comment]
I'm sorry but I am not at all sure. You may get some more help from an Autodesk forum.  I'm not at all familiar with Autocad itself
