### ISSUE TITLE
[Bug]: Inverted 2d extrusion profiles

### ISSUE THREAD

**Issue by agviegas** [IFCjs/web-ifc#432]
### What happened?

There has been a regression in [this model](https://github.com/IFCjs/test-ifc-files/blob/main/Revit/rac_advanced_sample_project.ifc). I think this happened because recently @QuimMoya and me discovered a bug in IfcAxis2DPlacement which resulted in negative results. As you can see in the picture, it looks like the curve of the deck has been inverted.
 
![image](https://github.com/IFCjs/web-ifc/assets/56475338/9019ee6e-4f61-40fc-b931-1e386f83ea41)

### Version

0.0.42

### What browsers are you seeing the problem on?

Chrome

**Comment by QuimMoya** [comment]
![image](https://github.com/IFCjs/web-ifc/assets/12625508/e06b3b8e-cfcc-4b9e-84cc-4a49ae5da95b)
Solved

**Comment by QuimMoya** [comment]
Solved
