### ISSUE TITLE
[Bug]: offset is out of bounds

### ISSUE THREAD

**Issue by Garripe** [IFCjs/web-ifc#435]
### What happened?

Hi all, I am trying to save a model in a file. With small files it seems to work fine, specifically with the simple [simple rebar.ifc](https://ifcjs.github.io/web-ifc/examples/viewer.html#https://raw.githubusercontent.com/IFCjs/test-ifc-files/main/Structures/simple%20rebar.ifc) file it does it correctly. I have not been able to do it with other files like [TESTED_Simple_project_01.ifc](https://ifcjs.github.io/web-ifc/examples/viewer.html#https://raw.githubusercontent.com/IFCjs/test-ifc-files/main/Revit/TESTED_Simple_project_01.ifc). The function that is giving me an error is **SaveModel()**. This is the execution sequence:

![Captura de pantalla 2023-07-10 a las 10 02 13](https://github.com/IFCjs/web-ifc/assets/39089222/3d0f6466-3379-4a20-a0bf-5ca9bf9e0a9c)

![Captura de pantalla 2023-07-10 a las 10 02 58](https://github.com/IFCjs/web-ifc/assets/39089222/da189bd3-86ea-4700-8642-bd44c91b5fcb)

As you can see in the images the dataBuffer is smaller than the src. Why is this happening? Am I doing something wrong? Thanks in advance

### Version

0.0.39

### What browsers are you seeing the problem on?

Chrome, Safari

### Relevant log output

```shell
RangeError: offset is out of bounds
    at Uint8Array.set (<anonymous>)
    at web-ifc-api.js:62044:18
    at __emval_call (web-ifc-api.js:9241:27)
    at web-ifc.wasm:0x8f2fb
    at web-ifc.wasm:0x81686
    at web-ifc.wasm:0x9135c
    at Object.SaveModel (eval at new_ (web-ifc-api.js:8629:31), <anonymous>:9:1)
    at IfcAPI2.SaveModel (web-ifc-api.js:62041:21)
    at createDownloadLink (IFCViewer.jsx:109:27)
```

**Comment by beachtom** [comment]
This is odd - can you share the code?

**Comment by LukasKStavario** [comment]
Hi @beachtom I have the same problem. I have updated to 0.0.42 because of deleting lines in API (I really need this feature). And it is in this version (thank you very much) but I am not able to save modified model. SaveModel and ExportFileAsIFC end with the same error that mentioned here.
So I am upvoting to repair it - thank you.

![image](https://github.com/IFCjs/web-ifc/assets/112091369/c9746866-1c0b-4128-899a-0ab7c051be03)

**Comment by beachtom** [comment]
This should be fixed now!

**Comment by LukasKStavario** [comment]
Thanks Tom! You mentioned in the past that it is possible to download a zip somewhere in the repository with the current build before you release it, with me replacing the specific files, where can I find it?

**Comment by beachtom** [comment]
There is a link on the readme under current build. 

But it takesa bout 15-20 min to build the entire set - so wait a bit or the changes may not be in
