### ISSUE TITLE
[Bug]: GetLine() with IfcBoolean/IfcLogical properties is broken in 0.0.42

### ISSUE THREAD

**Issue by andy-wrks** [IFCjs/web-ifc#436]
### What happened?

We recently tried to upgrade from 0.0.39 to 0.0.42 and found the following bug:

The attached test file has an IfcColumn with a Pset "Test" with the following properties in it:

![IFC_source](https://github.com/IFCjs/web-ifc/assets/111515188/7d468439-d3fb-428e-8a5d-9bfe85f10e62)

When using GetLine() with IfcPropertySingleValues of defined types IfcBoolean and IfcLogical, we used to get this in 0.0.39:

![web-ifc_0039_ok](https://github.com/IFCjs/web-ifc/assets/111515188/41a81794-325b-4503-82f0-39f626e817e8)
Everything ok, we get Type 3 (enumeration?) and the actual enumeration values "T", "F", "U".

Doing the same in 0.0.42, the values "T", "F", "U" are missing and there's always a boolean false:

![web-ifc_0042_bad](https://github.com/IFCjs/web-ifc/assets/111515188/796c8f2c-ed61-405b-be1e-9bc34e83771f)
So here it's impossible to say what the actual value of an IfcBoolean or IfcLogical was.

### Version

0.0.42

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
See Screenshots above
```

### Anything else?

Test file from above:
[IfcBoolean_IFC4.zip](https://github.com/IFCjs/web-ifc/files/12013427/IfcBoolean_IFC4.zip)

**Comment by beachtom** [comment]
So it was the intention to change this to an actual bool - not sure why it is always returning false - i will look into it,

**Comment by andy-wrks** [comment]
Thanks for looking into it :-) One thing to consider:
IfcLogical can be True, False or Unknown (".U."). The last state can't be converted to a boolean (obviously), so it may be more consistent to keep things as they are in 0.0.39.
We currently are looking for Type3 "T", "F", "U" in order to identify Boolean/Logical values. The question is, what happens to the "U" state? It would be kind of ugly if IfcLogical could result in either a boolean or a string 🤔

**Comment by beachtom** [comment]
This is now fixed - booleans now work correctly - we are using an enum for logical.
