### ISSUE TITLE
[Bug]: Exporting models breaks geometry

### ISSUE THREAD

**Issue by LukasKStavario** [IFCjs/web-ifc#441]
### What happened?

I have load this model:
![image](https://github.com/IFCjs/web-ifc/assets/112091369/d86b0f5f-af6a-4177-9694-55cc00762c62)
Everything in loading is OK, no console issues.
I am exporting it by 0.0.42 with no changes (my goal is delete some props) but for now I am testing export according to #435 and offset error is really repaired. but my exported model - I have tested about 5 and everyone has this behavior - looks like this.

And #440 is the same on every model that not been exported in previos builds.

![image](https://github.com/IFCjs/web-ifc/assets/112091369/97505bbb-6423-4c5e-9664-66ec0867ba18)

### Version

0.0.42

**Comment by beachtom** [comment]
Can you share the original and exported model so I can try and pin down what is happening.

**Comment by LukasKStavario** [comment]
I have sent it to mail beachth..I hope that size would not be problem for mail. Model also contains encoding issue.

**Comment by beachtom** [comment]
This is now fixed!

**Comment by LukasKStavario** [comment]
That was super fast, thank you!
