### ISSUE TITLE
[Bug]: Can't get TypeName with IFCWorker

### ISSUE THREAD

**Issue by rkaeplive** [IFCjs/web-ifc#442]
Hello, Im trying to get IFCTypeName, but it unknown when I use WebWorker
<img width="1578" alt="image" src="https://github.com/IFCjs/web-ifc/assets/80881455/568837a7-50ff-41a5-9f79-5234fa1b8095">

But without WebWorker it work
<img width="683" alt="image" src="https://github.com/IFCjs/web-ifc/assets/80881455/169daf5a-8e81-4b79-8cec-e063b1af93aa">

### Version

last version from npm

**Comment by beachtom** [comment]
So this will be a bug in the web-ifc-three - can i ask you to raise it there so it ends up with the right developers

**Comment by rkaeplive** [comment]
@beachtom ok, I can
