### ISSUE TITLE
[Bug]: Missing or inverted face in roof surface [0.0.43 wip]

### ISSUE THREAD

**Issue by andy-wrks** [IFCjs/web-ifc#443]
### What happened?

In the provided sample file, a face of the roof isn't displayed correctly.

Output on https://ifcjs.github.io/web-ifc/demo/:
![Demo-0042-43](https://github.com/IFCjs/web-ifc/assets/111515188/9da2deb0-4741-4cd4-bb26-47fc6306e8c1)

Expected output:
![BIMcollab](https://github.com/IFCjs/web-ifc/assets/111515188/e8778824-fafe-46b9-9d8e-531803191c97)

### Version

0.0.43 "work in progress" version on demo page

### Anything else?

Sample file with roof object (IfcSlab):
[sample.zip](https://github.com/IFCjs/web-ifc/files/12029154/sample.zip)

The original, full model was originally exported from ArchiCAD 24.

**Comment by QuimMoya** [comment]
I tested it. There are no missing faces but normals are wrong. Will try to solve it

**Comment by QuimMoya** [comment]
We decided to show both faces of each surface... so now it works correctly

![image](https://github.com/IFCjs/web-ifc/assets/12625508/f009ba9f-b49d-4baa-b79c-bd9aa4412ff6)

**Comment by andy-wrks** [comment]
Does this mean that now by default both sides of a surface are rendered? Does this impact performance and the display of translucent objects?
