### ISSUE TITLE
[Bug]: UsageType of IfcFacilityPart is parsed as a IfcTokenType::LABEL instead of IfcTokenType::ENUM

### ISSUE THREAD

**Issue by edlundNWP** [IFCjs/web-ifc#444]
### What happened?

When parsing a line of type IfcFacilityPart, the UsageType attribute does not return an object of the shape:
```
{
  type: 3,
  value: "SOMEENUMVALUE"
}
```
Like other enums do.

Instead it returns:
```
{
  type: 2,
  typecode: 492794765,
  value: "SUPERSTRUCTURE",
}
```

[Checking web-ifc-api.cpp](https://github.com/IFCjs/web-ifc/blob/846018eb4c6caa0133d92f054ccccc862581ed45/src/wasm/web-ifc-api.cpp#L795), this seems to be due to the fact that web-ifc believes this is an IfcTokenType::LABEL instead of an IfcTokenType::ENUM, even though in the IFC4X3 schema, the IfcFacilityUsageEnum is defined like any other enum.

# How to reproduce

I found the issue by calling `getLine()` on expressID 26 [for this test file](https://github.com/bSI-InfraRoom/IFC-infra-unit-test/blob/main/SpatialStructure-2/SpatialStructure_2.ifc). The name of the schema in this file needs to be changed from `FILE_SCHEMA (('IFC4X3_RC3'));` to `FILE_SCHEMA (('IFC4X3'));` for web-ifc to correctly parse it.

### Version

0.0.42

### Relevant log output

```shell
{
  expressID: 26,
  type: 1310830890,
  GlobalId: {
    value: "2r6fGfMerF2OJ6dLEL409U",
    type: 1,
  },
  OwnerHistory: {
    value: 10,
    type: 5,
  },
  Name: {
    value: "överbyggnad (31--)",
    type: 1,
  },
  Description: null,
  ObjectType: null,
  ObjectPlacement: {
    value: 25,
    type: 5,
  },
  Representation: null,
  LongName: null,
  CompositionType: null,
  UsageType: {
    type: 2,
    typecode: 492794765,
    value: "SUPERSTRUCTURE",
  },
}
```

**Comment by beachtom** [comment]
So I think the issue is here - this IFC file does not match the schema was are using for IFC4X3 - and it is spitting out the data in that format as a best effort to parse it. That particular ENUM isn't valid as per the IFC4X3 express file - I am pretty sure the one we have is the final one under ISO voting.
