### ISSUE TITLE
[Feat]: Not able to render IFCs of precast concrete structures with rebars exported from Tekla

### ISSUE THREAD

**Issue by felipecordero** [IFCjs/web-ifc#445]
### What is your idea?

Hello Antonio and thank you very much for everything that you and the team have developed so far. 

By the way, I would like to know if it is possible to do some review on IFCs models of precast concrete structures with rebars exported from Tekla. When I try to load them with IFCjs it takes a long time to load and sometimes it's not possible (models don't render and web browser freezes)

I'll email you a sample so you can explore it and if possible give me some feedback.

Thanks so much in advance!

**Comment by beachtom** [comment]
Hi, can you share some example models with us?

**Comment by beachtom** [comment]
No mode - so cannot progress - closing

**Comment by felipecordero** [comment]
Hi. I sent models by email to Antonio.
