### ISSUE TITLE
[Bug]: Numeric properties in scientific notation return a 0 value (in certain cases)

### ISSUE THREAD

**Issue by andy-wrks** [IFCjs/web-ifc#454]
### What happened?

I made a small test file in order to test numeric artefacts and scientific notation.
It seems that in some cases, scientific notation is converted to a 0 value.

The attached file has 1 IfcColumn with a Pset "Test_Quantities".
The properties in the Pset are these:

![image](https://github.com/IFCjs/web-ifc/assets/111515188/88dc395a-cc79-45ca-be6e-7c583760a21d)

The properties markes with a red "X" return 0 values when using GetLine. Example:

![image](https://github.com/IFCjs/web-ifc/assets/111515188/e484bb54-b8f4-4f45-8f17-315b8d0fc67f)

If I'd have to guess, I would say that it returns 0 whenever there is no decimal point before the E and a negative number after the E.
When I write 3.0E-1 instead of 3E-1, I get the correct value.

### Version

0.0.43 wip

### What browsers are you seeing the problem on?

Chrome

### Anything else?

Test file:
[Numbers_IFC2x3.zip](https://github.com/IFCjs/web-ifc/files/12162898/Numbers_IFC2x3.zip)

**Comment by beachtom** [comment]
So I recently updated our number parsing to fix some other bugs and it seems it has also fixed this one. Can you validate and re-open if it is the case?

**Comment by andy-wrks** [comment]
Hi @beachtom 
We just updated to 0.0.44 and I had a look at it. The behaviour is now different in that it doesn't return "0" anymore.
However, there is still a problem and it seems to happen whenever the number before "e" is given without decimals.
See the current values and expected values, referring to the same test file:

![image](https://github.com/IFCjs/web-ifc/assets/111515188/586f0407-9268-40e8-9c69-13763385e3a5)

**Comment by beachtom** [comment]
Ok that was an case we didn't deal with - so it is now fixed

**Comment by andy-wrks** [comment]
Tested it today with the new release and got the expected results.
Thanks :-)
