### ISSUE TITLE
[Bug]: Inverted normals for a model 

### ISSUE THREAD

**Issue by agviegas** [IFCjs/web-ifc#455]
### What happened?

It looks like there are some normals that are inverted in some of the geometries. Probably there's a bug somewhere in the geometry generation. The model is quite small and can be found [here](https://drive.google.com/file/d/1ArTh6emFGfOag331noJXR3PDqcnvKLmH/view?usp=drive_link).

![image](https://github.com/IFCjs/web-ifc/assets/56475338/5fdd003a-1b54-4c41-ac02-6ff1cebd41ff)

### Version

0.0.42

**Comment by QuimMoya** [comment]
We decided to show both faces of each surface.

The issue is solved

![image](https://github.com/IFCjs/web-ifc/assets/12625508/5affc633-8d34-4a19-8bd9-e3e21e5e0bc5)
