### ISSUE TITLE
[Bug]: Rebar model doesn't open

### ISSUE THREAD

**Issue by agviegas** [IFCjs/web-ifc#464]
### What happened?

When trying to open [this model](https://drive.google.com/file/d/1BbsAwmaF0UTyoLKFZt_K4Vmt79TzvarB/view?usp=drive_link), the browser runs out of memory.

### Version

0.0.42

**Comment by beachtom** [comment]
Requested access to the file to look at thisl

**Comment by agviegas** [comment]
@beachtom I gave you access, let me know if you have any issues.

**Comment by QuimMoya** [comment]
![image](https://github.com/IFCjs/web-ifc/assets/12625508/3b404132-5c57-474b-a2db-05b50b839164)
Takes a while but last commit solves the issue

**Comment by QuimMoya** [comment]
The current version opens the model 
![image](https://github.com/IFCjs/web-ifc/assets/12625508/973404aa-a60a-413c-9c7d-1a31e700ff7e)
