### ISSUE TITLE
Get (Space) Geometry in correct coordinates or get correct transformation matrix

### ISSUE THREAD

**Issue by ragnhmyr** [IFCjs/web-ifc#467]
Hi! 

I'm trying to get hold of space geometry (get points in correct (global) coordinates to create polygons and/or save points in a database)
Further on I want to do the same with other objects.

Tried both with streamGeometry, flatMesh = client.GetFlatMesh(modelId, 26832), change Coordinate to origin and so on.
But the vertice data (Float32Array (216)) is always the same:

```typescript
export const parse: Parse = async args => {
  if (args.content == null || args.content.byteLength === 0) {
    throw new Error('No content in ifc download')
  }
  const client = new IfcAPI()
  await client.Init()

  const loaderSettings: LoaderSettings = {
    COORDINATE_TO_ORIGIN: false,
  };

  const modelId = client.OpenModel(args.content, loaderSettings)

  const lines = client.GetAllLines(0)

  //START Get geometry for space == WOMENS TOILET 26832

  function handleMesh(mesh: any) {
    // Do something with the mesh, for example, log its properties
    console.log("Received mesh:", mesh);
    console.log(mesh.geometries)
    for (var j = 0; j < mesh.geometries.size(); j++) {
      let flatGeometry = mesh.geometries.get(j)
      let id = flatGeometry.geometryExpressID
      console.log("ExpressID: ", id)
      let geometry = client.GetGeometry(modelId, flatGeometry.geometryExpressID)
      console.log(geometry)
      console.log("Flat transformation", flatGeometry.flatTransformation)
      let vertices = client.GetVertexArray(geometry.GetVertexData(), geometry.GetVertexDataSize());
      console.log("VERTICES")
      console.dir(vertices, {'maxArrayLength': null})
  }
}

  client.StreamMeshes(modelId,[26832],handleMesh)
```

IFC-file attached (a solibri sample ifc file): [IFC_Solibri Building.zip](https://github.com/IFCjs/web-ifc/files/12418419/IFC_Solibri.Building.zip)

Just worked with a simple square space (line 26832) and also tried with a more complex space (line 49914)

![image](https://github.com/IFCjs/web-ifc/assets/78514454/1b358322-20d3-43b1-8253-554c7bab3c22)

![image](https://github.com/IFCjs/web-ifc/assets/78514454/d3bbae48-832c-4b07-b7f4-6d4f35e03707)

Tried to do the transformation with three.js (applyMatrix4(flatTransformation)) but I can't seem to get the correct coordinates.
I was notified that xyz axes are switched in three.js (y is up)
but I could not figure out how to adjust the transformation matrix to get the correct transformation.

Asked in the Discord server and was suggested to add it as an issue here. 
I'm using the newest web-ifc (0.0.42)

**So question is: How can i get the vertices in their correct global coordinate or do the correct transformation?**

Please let me know if it is not clear or you need additional information :blush: Thank you!

Test code with three.js attached: [Three_test.zip](https://github.com/IFCjs/web-ifc/files/12418742/Three_test.zip)

![image](https://github.com/IFCjs/web-ifc/assets/78514454/c3b351bd-81c2-4e62-b1a0-e47d5df64abc)

**Comment by RyugaRyuzaki** [comment]
@ragnhmyr , you can try this 
``` 
// commonArea_spacegeometry.applyMatrix4(commonArea_matrix)

console.log(toalett_spacegeometry.attributes.position.array);
// toalett_spacegeometry.applyMatrix4(toalett_matrix);
console.log(toalett_spacegeometry.attributes.position.array);

const toalett_mesh = new THREE.Mesh(toalett_spacegeometry, blueMaterial);
toalett_mesh.matrix = new THREE.Matrix4().fromArray(toalett_matrix.toArray());
toalett_mesh.matrixAutoUpdate = false;
const commonArea_mesh = new THREE.Mesh(commonArea_spacegeometry, redMaterial);
commonArea_mesh.matrix = new THREE.Matrix4().fromArray(commonArea_matrix.toArray());
commonArea_mesh.matrixAutoUpdate = false;
``` try : transformmatrix mesh, not transfrom matrix geometry

**Comment by ragnhmyr** [comment]
thank you @RyugaRyuzaki for the suggestion, but same result unfortunately.
I do anyway want to transform the geometry since it is the points that I want to save

**Comment by RyugaRyuzaki** [comment]
> 
if i use :toalett_spacegeometry.applyMatrix4(toalett_matrix); then the toalet is on the commonArea_mesh , but when i use this :toalett_mesh.matrix = new THREE.Matrix4().fromArray(toalett_matrix.toArray());=> toalet is out . What's your goal?

**Comment by ragnhmyr** [comment]
Don't mind the plotting of the meshes just now
My goal is to get the correct coordinates of the points (x, y, z), please see screenshot: :blush: 

![image](https://github.com/IFCjs/web-ifc/assets/78514454/b68bda0a-d4bb-4574-91e3-fe8090447e90)

**Comment by RyugaRyuzaki** [comment]
> Don't mind the plotting of the meshes just now My goal is to get the correct coordinates of the points (x, y, z), please see screenshot: 😊
> 
> ![image](https://user-images.githubusercontent.com/78514454/263222219-b68bda0a-d4bb-4574-91e3-fe8090447e90.png)

You mean you wanna get all vertices (x,yz) of the space?

**Comment by ragnhmyr** [comment]
yes! :) In the correct coordinates

**Comment by ragnhmyr** [comment]
I kind of figured it out :)

Three.js take arguments in row-major order, but perform calculations in column major order
```
export function RightToLeftHand(vector: THREE.Vector3): THREE.Vector3 {
  return new THREE.Vector3(vector.x, -vector.z, vector.y);
}
```
To get correct coordinates i  made a new matrix with the input from the transformationMatrix (array) and multiplied that with each point to get the points with correct coordinates. 
```
[x,y,z,1]
*
[
[array[0],array[4],array[8],array[12]],
[-array[2],-array[6],-array[10],-array[14]],
[array[1],array[5],array[9],array[13]],
[array[3],array[7],array[11],array[15]]
]
```
