### ISSUE TITLE
[Bug]: String Encoding Problem (Mac OS Roman encoding)

### ISSUE THREAD

**Issue by gezar** [IFCjs/web-ifc#468]
### What happened?

Some models made on Mac use the "Mac OS Roman" encoding. (https://en.wikipedia.org/wiki/Mac_OS_Roman)

That leads to some decoding problem :
Example : "Côté opposé" is encoded "C\X\99t\X\8E oppos\X\8E and is not decoded right. We get : C�t� oppos�

In Latin-1 the \X\80 to \X\9F characters are "control characters", so when we see those in an IFC file, we can assume it's a MacRoman encoding.

### Version

0.0.42

### Anything else?

Here is an example of a model with such encoding problems: 
[ARCHITECTE - ArchiCAD.zip](https://github.com/IFCjs/web-ifc/files/12438923/ARCHITECTE.-.ArchiCAD.zip)

**Comment by beachtom** [comment]
Ok this should now be fixed
