### ISSUE TITLE
[Bug]: Exporting (save model) corrupts geometry (precision problem)

### ISSUE THREAD

**Issue by LukasKStavario** [IFCjs/web-ifc#470]
### What happened?

Hi, I have a problem, we are strugling with reexporting IFC via this library. We reported 3 bugs on this feature, thank you very much for repair. But now, we are in production stage and models are broken. I think it is caused by loose of precision.
![image](https://github.com/IFCjs/web-ifc/assets/112091369/e7753d6d-231f-4c18-92cd-480f55d3c969)

May I send you a models to email?
I hope that is the last problem - in diff everything looks good except for precision. Thank you

### Version

0.0.43 - last build not from NPM

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

**Comment by beachtom** [comment]
Yes please send the models. I was sure this was fixed - definetly running on latest version?

**Comment by LukasKStavario** [comment]
Any news on this please?

**Comment by beachtom** [comment]
Been busy with the day job will hopefully look today/tomorrow.

**Comment by beachtom** [comment]
This is now fixed

**Comment by LukasKStavario** [comment]
Thank you, works very well! 

I have a question related to this...I have some IFC4X3_RC1...If I go to file and remove "x3_RC1" everything works fine. Is there any way to ignore schema type on my risk?

**Comment by beachtom** [comment]
Yeah that one should be supported - I just fixed it

**Comment by LukasKStavario** [comment]
Super Tom, thank you very much! Schema works fine.
