### ISSUE TITLE
[Feat]: Add support for trimmingselect IFCLINE

### ISSUE THREAD

**Issue by harrycollin** [IFCjs/web-ifc#472]
### What is your idea?

Some models using IfcReinforcingBar exported from Tekla use an unsupported trimming operation not yet implemented by web-ifc. ```web-ifc``` currently produces this error:```ERROR: Unsupported trimmingselect IFCLINE``` for all of the rebar is my Tekla IFC models. This results in missing geometry in the final output.

**Comment by QuimMoya** [comment]
It is solved in the last commit
