### ISSUE TITLE
[Bug]: Specific model stuck at 70%

### ISSUE THREAD

**Issue by mikisf** [IFCjs/web-ifc#473]
### What happened?

I'm trying to load this IFC (https://we.tl/t-F9Mkp0CKGC or in case it expires: https://github.com/mikisf/Tests/blob/main/public/ifc.ifc) in my project but it gets stuck in the 70%. You can see what I mean in this page: https://tests-virid-three.vercel.app/ (the % appear in the console)
You can see the code in this github repository: https://github.com/mikisf/Tests

### Version

0.0.35

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
web-ifc: 0.0.34 threading: 0
10.00633312222926
20.01266624445852
30.018999366687776
40.02533248891704
unexpected style type
50
60.00633312222926
70.01266624445852
Unsupported curve type
```

### Anything else?

As you can see the last message before it gets stucked is ```Unsupported curve type``` which I think I have never seen it. It might be related with the issue.

**Comment by QuimMoya** [comment]
I just opened it without problems ....
![image](https://github.com/IFCjs/web-ifc/assets/12625508/44647b6e-cb4d-4223-a782-33eff3250cc1)

**Comment by QuimMoya** [comment]
I will close the issue now

If there is any update i will open this issue again
