### ISSUE TITLE
[Bug]: IFC axes and coding problem

### ISSUE THREAD

**Issue by LukasKStavario** [IFCjs/web-ifc#479]
### What happened?

Hi, I have a model, that have two problems with web-ifc library.

One, is the axes...If I change the axes to correct, it is ok, but I want to it ideally in web-ifc (a have clonned source in my project) how to do it?
Left model is in error, right is ok
![image](https://github.com/IFCjs/web-ifc/assets/112091369/94c0e8ba-605b-4a81-bece-a5a437fb0d03)

Second problem is with coding. If line of property single value is empty string in IFCLabel - I am getting weird string on output

#117212=IFCPROPERTYSINGLEVALUE('ConstructionStart',$,IFCLABEL(''),$);

![image](https://github.com/IFCjs/web-ifc/assets/112091369/6bd5ace5-c4e4-499a-9feb-c8a1e2f6c064)

### Version

0.0.43 - last build not from NPM

**Comment by beachtom** [comment]
I think i fixed the coding problem in the last update can you text. Not had chance to look at axis yet.

**Comment by beachtom** [comment]
@LukasKStavario  did you get chance to test this?

**Comment by LukasKStavario** [comment]
Yes, in the last build the coding of nulls are OK. But I am still waiting for the repair of the big model to get this version to production. Any infos about axes?

**Comment by beachtom** [comment]
I am trying to look at the axis now - but I can't work out what you are trying to do with the axis? Any code you can share.

**Comment by LukasKStavario** [comment]
It is a misunderstanding. I am trying to load a model that cannot be loaded, upon further investigation I found that if I change the axes, viz. screenshot, so web-ifc can load it so I can see the model. If I leave the axes as they are in the original model (left part), I cannot load the geometry. I don't know if it's an error in the given IFC or in your engine, but I know that both in Bimcollab and in bimvision everything is ok.

**Comment by beachtom** [comment]
OK can you share the error you get?

**Comment by beachtom** [comment]
This is fixed. It is actually an error in the IFC - but we are now dealing with it gracefully
