### ISSUE TITLE
[Bug]: this.ifcApi.GetLine stopped working with flatten set to true

### ISSUE THREAD

**Issue by lukasvdelft** [IFCjs/web-ifc#482]
### What happened?

I upgraded from 0.0.39 to 0.0.43. the following code: this.ifcApi.GetLine(this.modelId, relatedObject.value, true, true) now gives me an error. If I set flatten to false it does not give the error. @Tom, it is the same data I am using already for some months.

### Version

0.0.43

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
web-ifc-api.js:64872 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'type')
    at web-ifc-api.js:64872:80
    at Array.forEach (<anonymous>)
    at IfcAPI2.FlattenLine (web-ifc-api.js:64867:23)
    at IfcAPI2.GetLine (web-ifc-api.js:64771:12)
    at web-ifc-api.js:64871:37
    at Array.forEach (<anonymous>)
    at IfcAPI2.FlattenLine (web-ifc-api.js:64867:23)
    at IfcAPI2.GetLine (web-ifc-api.js:64771:12)
    at web-ifc-api.js:64871:37
    at Array.forEach (<anonymous>)
```

**Comment by beachtom** [comment]
Can you share the model you are using - or at least the IFC line you are retrieving

**Comment by lukasvdelft** [comment]
Sure
________________________________
Van: Tom Beach ***@***.***>
Verzonden: maandag 11 september 2023 21:44
Aan: IFCjs/web-ifc ***@***.***>
CC: Lukas van Delft ***@***.***>; Author ***@***.***>
Onderwerp: Re: [IFCjs/web-ifc] [Bug]: this.ifcApi.GetLine stopped working with flatten set to true (Issue #482)


Can you share the model you are using - or at least the IFC line you are retrieving

**Comment by beachtom** [comment]
Hi, did you send something - if so nothing came through

**Comment by lukasvdelft** [comment]
[20221221_Boelelaan_1117_Amsterdam_2023_L0.ifc.zip](https://github.com/IFCjs/web-ifc/files/12605767/20221221_Boelelaan_1117_Amsterdam_2023_L0.ifc.zip)

**Comment by lukasvdelft** [comment]
I replied to the mail with an attachment but it didn't come through I guess

**Comment by beachtom** [comment]
and what line in particular is causing you issues? can you give me the express ID/

**Comment by beachtom** [comment]
This is now fixed
