### ISSUE TITLE
Where i can get documentation for this web-ifc? 

### ISSUE THREAD

**Issue by dikyridhlo** [IFCjs/web-ifc#490]
### What happened?

i tried to open 
https://github.com/IFCjs/info
https://ifcjs.github.io/info/docs/Introduction/

its return 404, can someone share to me where i can find the documentation?

### Version

0.0.43

**Comment by beachtom** [comment]
So the API docs are on this repository - click on documentation on the readme

The wider docs are here: https://platform.thatopen.com/documentation
