### ISSUE TITLE
[Question]: What happend to ifc.js?

### ISSUE THREAD

**Issue by SimonF89** [IFCjs/web-ifc#491]
### What is your idea?

Hi,
do you know what happend to ifc.js? Has the project been discontinued or turned into a commercial product?

Since we would like to use a web ifc viewer in our professional app we would like to use something that will be maintained. What are the plans with this (web-ifc) project?

**Comment by beachtom** [comment]
This will continue being maintained - web-ifc-viewer is being deprecated - but the components repository is replacing it
