### ISSUE TITLE
[Bug]: Cannot read properties of undefined (reading 'CreateModel')

### ISSUE THREAD

**Issue by sushantc-inode** [IFCjs/web-ifc#492]
### What happened?

I was trying to create a model and CreateIfcEntity but getting error 

**web-ifc-api.js:64692 Uncaught TypeError: Cannot read properties of undefined (reading 'CreateModel')
    at IfcAPI2.CreateModel (web-ifc-api.js:64692:34)**

### Version

0.0.44

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
web-ifc-api.js:64692 Uncaught TypeError: Cannot read properties of undefined (reading 'CreateModel')
    at IfcAPI2.CreateModel (web-ifc-api.js:64692:34)
    at CreateTestModel (index.ts:15:26)
    at main.ts:56:1
```

### Anything else?

code:
import { IfcAPI, LoaderSettings, NewIfcModel, Schemas, IFC4 } from "web-ifc";

const CreateTestModel = () => {
  const ifcApi = new IfcAPI();
  ifcApi.Init();
  const model: NewIfcModel = {
    authorization: "test",
    authors: ["Test"],
    description: ["Test Model"],
    name: "Test-Ifc",
    organizations: ["test"],
    schema: Schemas.IFC4,
  };
  const modelSettings: LoaderSettings = { COORDINATE_TO_ORIGIN: true };
  const modelID = ifcApi.CreateModel(model, modelSettings);

  let column = ifcApi.CreateIfcEntity(
    modelID,
    ifcApi.CreateIfcType(modelID, IFC4.IfcColumnTypeEnum.COLUMN, "2")
  );
  ifcApi.WriteLine(modelID, column);
};

export { CreateTestModel };

**Comment by beachtom** [comment]
I think you need to await IfcAPi.init(); I think you are calling CreateModel before the library has initiated. Please re-open if this is not the fix.

**Comment by sushantc-inode** [comment]
Thanks @beachtom
