### ISSUE TITLE
[Bug]: Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

### ISSUE THREAD

**Issue by nhutruong-arent** [IFCjs/web-ifc#493]
### What happened?

I am using IFCLoader from web-ifc-three version 0.0.125, and after running 'yarn start,' I encountered a warning as shown in the image below.
![image](https://github.com/IFCjs/web-ifc/assets/99541143/0a3694be-ab9a-41e2-aa9d-4c39be272514)

### Version

"web-ifc": "0.0.41", "web-ifc-three": "0.0.125"

### What browsers are you seeing the problem on?

Microsoft Edge

**Comment by nhutruong-beycons** [comment]
This issue has been resolved by integrating web-ifc-three into my project without the need for a package.
![image](https://github.com/IFCjs/web-ifc/assets/101889353/6769c74a-c7e5-44d8-9d9f-79a7197d9a82)

**Comment by beachtom** [comment]
So I suspect that web-ifc-three is still using an older version of web-ifc. This bug has been fixed in the current version
