### ISSUE TITLE
[Bug]: Regression: Writing Raw Lines in 0.0.44 works unexpected compared to 0.0.43

### ISSUE THREAD

**Issue by quasarchimaere** [IFCjs/web-ifc#494]
### What happened?

If one uses the writeRawLine function to write lines with an empty description web-ifc 0.0.43 works appropriately, but 0.0.44 just omits the parameter all together

Result 0.0.43:
`#282=IFCPROPERTYSINGLEVALUE('Id',$,IFCLABEL('1'),$);`
Result 0.0.44:
`#282=IFCPROPERTYSINGLEVALUE('Id',IFCLABEL('1'),$);`

### Version

0.0.44

**Comment by quasarchimaere** [comment]
i think i made a mistake in choosing the appropriate ToRawLineData index, since it has changed from 3,4,5 to 1,2,3 in the dependency upgrade -> closing this ticket until investigation/trial is done again

**Comment by beachtom** [comment]
Did you check this out? Is it working as expected?

**Comment by quasarchimaere** [comment]
No the issue is still present, however while trying to create a lil reproduction case for you i found out that it has to do with undefined<->null (oh what a joy js is...) differences, let me explain:

```
const ifcApi = new WebIFC.IfcAPI();
  await ifcApi.Init();
  const ifcData = fs.readFileSync(
    path.join(__dirname, "/resources/anyifcfile.ifc")
  );
  const modelID = ifcApi.OpenModel(ifcData);
  const nextExpressID = ifcApi.GetMaxExpressID(modelID) + 1;

  // We use some code generation to create Lines (and referencing lines) that result in the payload for WriteRawLineData (i spare you the superflous code since it does not affect the test outcome)
  ifcApi.WriteRawLineData(modelID, {
    ID: nextExpressID,
    type: IFCPROPERTYSINGLEVALUE,
    arguments: [
      { value: "Test", type: 1 },
      null,
      { value: "Value", valueType: 1, type: 2, label: "IFCLABEL" },
      null,
    ],
  });

  const actualIfcFileContentString = new TextDecoder().decode(ifcApi.ExportFileAsIFC(modelID));

  //Expected #658=IFCPROPERTYSINGLEVALUE('Test',$,IFCLABEL('Value'),$);
  //Actual 0.0.43 with null values: #658=IFCPROPERTYSINGLEVALUE('Test',$,IFCLABEL('Value'),$);
  //Actual 0.0.43 with undefined values: #658=IFCPROPERTYSINGLEVALUE('Test',IFCLABEL('Value'));
  //Actual 0.0.44 with null values: #658=IFCPROPERTYSINGLEVALUE('Test',$,IFCLABEL('Value'),$);
  //Actual 0.0.44 with undefined values: #658=IFCPROPERTYSINGLEVALUE('Test',IFCLABEL('Value'));
```
As you can see in the last comments of the code example, the proper parsing of the line depends on wheter or not empty params in the array are defined as "undefined" (everything is off) or "null" (everything works great)

I'm not sure why the test example produces the same errors even for 0.0.43 but i probably won't have time to find that out, it is not an issue now since i can simply replace the undefined values with null values when we translate our lines to the rawdatarepresentation.

Thanks a lot for asking, because the Repro steps made me come up with a solution!

**Comment by beachtom** [comment]
I think this is now fixed.
