### ISSUE TITLE
[Bug]: WebAssembly.instantiate()

### ISSUE THREAD

**Issue by mermicode** [IFCjs/web-ifc#497]
### What happened?

I've tried to implmenet web-ifc and I can see the pane without issues.

When I select to load an IFC I get this error:

ERROR
Aborted(CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 3c 21 44 4f @+0). Build with -sASSERTIONS for more info.
RuntimeError: Aborted(CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 3c 21 44 4f @+0). Build with -sASSERTIONS for more info.
    at abort (http://localhost:3000/static/js/bundle.js:394164:19)
    at http://localhost:3000/static/js/bundle.js:394204:13

### Version

latest

### What browsers are you seeing the problem on?

Chrome, Safari, Microsoft Edge

### Relevant log output

```shell
web-ifc-api.js:5072 Aborted(CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 3c 21 44 4f @+0)
abort @ web-ifc-api.js:5072
web-ifc-api.js:5076 Uncaught (in promise) RuntimeError: Aborted(CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 3c 21 44 4f @+0). Build with -sASSERTIONS for more info.
    at abort (web-ifc-api.js:5076:1)
    at web-ifc-api.js:5114:1
```

### Anything else?

I've been on this error for quite a while now. I've copied templated and wasm files in my public folders but haven't had any luck. It's a React App created with create-react-app

**Comment by beachtom** [comment]
This normally means that for whatever reason the javascript cannot download the wasm file. BEst to check in the developer tools to see what is happening when it tried to download the WASM
