### ISSUE TITLE
Create a ifc file from scratch

### ISSUE THREAD

**Issue by sushantc-inode** [IFCjs/web-ifc#503]
### What happened?

I have created a ifc file from scratch by following a video from youtube  https://youtu.be/4EJyWjfPjB0?feature=shared  but the output is something different.
And also not able to find any related documentation for the same.

**Code**
`import * as WebIFC from "web-ifc";
import { DownloadIFC } from "./import-export";
import { NewUUID } from "./helpers/UUID";
export class IFCWriter {
  private IFCAPI = new WebIFC.IfcAPI();
  private modelId: number = 0;

  constructor() {
    this.init();
  }

  async init() {
    await this.IFCAPI.Init();

    const NewIfcModel: WebIFC.NewIfcModel = {
      schema: WebIFC.Schemas.IFC4,
      name: "Model",
      description: ["Demo ifc file"],
      authors: ["Sushant Chaudhari"],
      organizations: [],
    };

    this.modelId = this.IFCAPI.CreateModel(NewIfcModel);

    const org = new WebIFC.IFC4.IfcOrganization(
      null,
      new WebIFC.IFC4.IfcLabel("Sushant"),
      null,
      null,
      null
    );

    this.IFCAPI.WriteLine(this.modelId, org);
    const app = new WebIFC.IFC4.IfcApplication(
      org,
      new WebIFC.IFC4.IfcLabel("0.0.1"),
      new WebIFC.IFC4.IfcLabel("iNode WTP"),
      new WebIFC.IFC4.IfcIdentifier("app")
    );

    this.IFCAPI.WriteLine(this.modelId, app);

    // UNITS

    const unit_1 = new WebIFC.IFC4.IfcSIUnit(
      WebIFC.IFC4.IfcUnitEnum.VOLUMEUNIT,
      WebIFC.IFC4.IfcSIPrefix.MILLI,
      WebIFC.IFC4.IfcSIUnitName.CUBIC_METRE
    );

    const unitAssign = new WebIFC.IFC4.IfcUnitAssignment([unit_1]);
    this.IFCAPI.WriteLine(this.modelId, unitAssign);

    // Gemoratical Representation
    const origin = [
      new WebIFC.IFC4.IfcLengthMeasure(0),
      new WebIFC.IFC4.IfcLengthMeasure(0),
      new WebIFC.IFC4.IfcLengthMeasure(0),
    ];

    const cartPoint = new WebIFC.IFC4.IfcCartesianPoint(origin);
    this.IFCAPI.WriteLine(this.modelId, cartPoint);

    origin[1].value = 10;
    origin[2].value = 15;
    const dir = new WebIFC.IFC4.IfcDirection(origin);

    const axis = new WebIFC.IFC4.IfcAxis2Placement3D(cartPoint, dir, null);
    this.IFCAPI.WriteLine(this.modelId, axis);

    const geomContext = new WebIFC.IFC4.IfcGeometricRepresentationContext(
      new WebIFC.IFC4.IfcLabel("3D context"),
      new WebIFC.IFC4.IfcLabel("model"),
      new WebIFC.IFC4.IfcDimensionCount(3),
      new WebIFC.IFC4.IfcReal(0.01),
      axis,
      dir
    );
    this.IFCAPI.WriteLine(this.modelId, geomContext);

    // Create Project
    const project = new WebIFC.IFC4.IfcProject(
      this.generateGlobalId(),
      null,
      new WebIFC.IFC4.IfcLabel("Project"),
      new WebIFC.IFC4.IfcText("Project Description"),
      null,
      null,
      null,
      [geomContext],
      unitAssign
    );
    this.IFCAPI.WriteLine(this.modelId, project);

    // Create a Element
    // COLUMN
    const profile = new WebIFC.IFC4.IfcRectangleProfileDef(
      WebIFC.IFC4.IfcProfileTypeEnum.AREA,
      new WebIFC.IFC4.IfcLabel("rectangular profile"),
      new WebIFC.IFC4.IfcAxis2Placement2D(cartPoint, dir),
      new WebIFC.IFC4.IfcPositiveLengthMeasure(10),
      new WebIFC.IFC4.IfcPositiveLengthMeasure(10)
    );

    const extSolid = new WebIFC.IFC4.IfcExtrudedAreaSolid(
      profile,
      axis,
      dir,
      new WebIFC.IFC4.IfcPositiveLengthMeasure(10)
    );

    const shapeRep = new WebIFC.IFC4.IfcShapeRepresentation(
      geomContext,
      new WebIFC.IFC4.IfcLabel("Body"),
      new WebIFC.IFC4.IfcLabel("sweptSolid"),
      [extSolid]
    );

    const productDef = new WebIFC.IFC4.IfcProductDefinitionShape(null, null, [
      shapeRep,
    ]);

    const column = new WebIFC.IFC4.IfcColumn(
      this.generateGlobalId(),
      null,
      new WebIFC.IFC4.IfcLabel("m_column"),
      new WebIFC.IFC4.IfcText("Column Desc"),
      null,
      null,
      productDef,
      new WebIFC.IFC4.IfcIdentifier("a234234"),
      WebIFC.IFC4.IfcColumnTypeEnum.COLUMN
    );

    this.IFCAPI.WriteLine(this.modelId, column);

    // Styling
    const color = new WebIFC.IFC4.IfcColourRgb(
      null,
      new WebIFC.IFC4.IfcNormalisedRatioMeasure(0.7),
      new WebIFC.IFC4.IfcNormalisedRatioMeasure(0.7),
      new WebIFC.IFC4.IfcNormalisedRatioMeasure(0.7)
    );
    this.IFCAPI.WriteLine(this.modelId, color);

    const srfStyleRendering = new WebIFC.IFC4.IfcSurfaceStyleRendering(
      color,
      new WebIFC.IFC4.IfcNormalisedRatioMeasure(0.0),
      new WebIFC.IFC4.IfcNormalisedRatioMeasure(0.8),
      null,
      null,
      null,
      null,
      null,
      WebIFC.IFC4.IfcReflectanceMethodEnum.METAL
    );
    this.IFCAPI.WriteLine(this.modelId, srfStyleRendering);

    const srfStyle = new WebIFC.IFC4.IfcSurfaceStyle(
      new WebIFC.IFC4.IfcLabel("My surface style"),
      WebIFC.IFC4.IfcSurfaceSide.BOTH,
      [srfStyleRendering]
    );
    this.IFCAPI.WriteLine(this.modelId, srfStyle);

    const styledItem = new WebIFC.IFC4.IfcStyledItem(
      extSolid,
      [srfStyle],
      null
    );
    this.IFCAPI.WriteLine(this.modelId, styledItem);

    // Spatial Structure
    const site = new WebIFC.IFC4.IfcSite(
      this.generateGlobalId(),
      null,
      new WebIFC.IFC4.IfcLabel("My Site"),
      new WebIFC.IFC4.IfcText(""),
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
    );

    this.IFCAPI.WriteLine(this.modelId, site);

    let relAggr = new WebIFC.IFC4.IfcRelAggregates(
      this.generateGlobalId(),
      null,
      null,
      null,
      project,
      [site]
    );
    this.IFCAPI.WriteLine(this.modelId, relAggr);

    const building = new WebIFC.IFC4.IfcBuilding(
      this.generateGlobalId(),
      null,
      new WebIFC.IFC4.IfcLabel("Building"),
      new WebIFC.IFC4.IfcText(""),
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
    );
    this.IFCAPI.WriteLine(this.modelId, building);

    // relAggr.expressID = this.maxExpressId++;
    relAggr.GlobalId = this.generateGlobalId();
    relAggr.RelatedObjects = [building];
    relAggr.RelatingObject = site;

    this.IFCAPI.WriteLine(this.modelId, relAggr);

    const buildingStorey = new WebIFC.IFC4.IfcBuildingStorey(
      this.generateGlobalId(),
      null,
      new WebIFC.IFC4.IfcLabel("Level 0"),
      new WebIFC.IFC4.IfcText("Datum"),
      null,
      null,
      null,
      null,
      null,
      new WebIFC.IFC4.IfcPositiveLengthMeasure(0)
    );
    this.IFCAPI.WriteLine(this.modelId, buildingStorey);

    // relAggr.expressID = this.maxExpressId++;
    relAggr.GlobalId = this.generateGlobalId();
    relAggr.RelatedObjects = [buildingStorey];
    relAggr.RelatingObject = building;

    this.IFCAPI.WriteLine(this.modelId, relAggr);

    const elements = [column];

    const rel = new WebIFC.IFC4.IfcRelContainedInSpatialStructure(
      this.generateGlobalId(),
      null,
      null,
      null,
      elements,
      buildingStorey
    );
    this.IFCAPI.WriteLine(this.modelId, rel);
    this.saveModel();
  }

  private saveModel = (name: string = "model.ifc"): void => {
    const blob = new Blob([this.IFCAPI.SaveModel(this.modelId)]);
    DownloadIFC(blob);
  };

  private generateGlobalId = (): WebIFC.IFC4.IfcGloballyUniqueId => {
    return new WebIFC.IFC4.IfcGloballyUniqueId(NewUUID());
  };
}
`

**Output/Result**
![Screenshot 2023-10-09 171312](https://github.com/IFCjs/web-ifc/assets/92144016/ba2d78fc-1856-467f-a420-5e79b1cc18bf)

### Version

0.0.44

### What browsers are you seeing the problem on?

Chrome

**Comment by beachtom** [comment]
Can you send the IFC file it generates?

**Comment by sushantc-inode** [comment]
Sure, 
[ifc_2023-10-09T11_42_05.170Z.zip](https://github.com/IFCjs/web-ifc/files/12855554/ifc_2023-10-09T11_42_05.170Z.zip)
