### ISSUE TITLE
[Bug]: COORDINATE_TO_ORIGIN doesn't work correctly in some cases

### ISSUE THREAD

**Issue by janruo** [IFCjs/web-ifc#504]
### What happened?

Some IFC models have coordinate values that are large enough to cause floating point precision issues for rendering.

For most models it seems to be enough to just to use `COORDINATE_TO_ORIGIN = true`, which resets the coordinates and the model will render correctly without precision issues.

But for some models the setting doesn't seem to work properly. The model will be translated to origin with the precision issues baked right into the model, even though the coordinates are no longer large.

### Version

0.0.44

### Anything else?

What it looks like:
![road](https://github.com/IFCjs/web-ifc/assets/49906573/f23877c1-51f2-43c4-b95c-21f1b3eee42c)

What it should look like:
![road](https://github.com/IFCjs/web-ifc/assets/49906573/92f039b9-8eac-4412-ad1c-1fdc709d04bf)

The model:
[large_coords.zip](https://github.com/IFCjs/web-ifc/files/12866561/large_coords.zip)

**Comment by ArtemRash** [comment]
I have encountered a similar problem. I can say that https://ifcjs.github.io/web-ifc-viewer/example/index opens this file more adequately, although https://distellar.diroots.com/ does not consider this model to be an IFC model at all. Please, see the https://ifcjs.github.io/web-ifc-viewer/example/index, good luck!
Do you happen to know where the state of the model is stored after it is cast using the COORDINATE_TO_ORIGIN ? In case I want to calculate the absolute coordinates of a point, I will need this state to add it to the relative coordinates.

**Comment by HoyosJuan** [comment]
I'm just following this thanks to some comments in the community, and just passing by to linking this issue with https://github.com/IFCjs/web-ifc/issues/524.

**Comment by beachtom** [comment]
Do you have an example model you can share?

**Comment by beachtom** [comment]
Ok this is quite tricky because the model is so wide it is giving a double precision error - I will need to think about how best to fix this

**Comment by beachtom** [comment]
That is interesting I will try and track it down from that

**Comment by beachtom** [comment]
This is now fixed!

**Comment by beachtom** [comment]
So it is live on the demo - should do a new release this week
