### ISSUE TITLE
[Bug]: GetLine() outputs incomplete IfcText values

### ISSUE THREAD

**Issue by andy-wrks** [IFCjs/web-ifc#506]
### What happened?

Context: This bug became visible after updating from web-ifc 0.0.42 to web-ifc 0.0.44. I double checked with the older release and it's giving the expected result. So this bug must have been recently introduced.

Bug: Strings with special characters can be cut off since release 0.0.43 or 0.0.44.

To reproduce this, I made a small test file with only an IfcColumn. The relevant data is in the Pset "Test_Properties".
There are different flavours of encoding special characters, which for example differs between ArchiCAD and SimpleBIM. So I included two files, which are identical but use the different encoding flavours. There is one example value, where one encoding is decoded correctly, while the other isn't. I assume that both encoding flavours are legitimate, since other apps were displaying it correctly.

Below is an overview of the expected values of the 9 Properties and the actual results from web-ifc 0.0.44 for both files. Strings that fail (=are cut off) have a red background:

![image](https://github.com/IFCjs/web-ifc/assets/111515188/ac4303db-a92a-4fdb-adc3-0d0a8db4ccae)

Example of a cut-off string:
![image](https://github.com/IFCjs/web-ifc/assets/111515188/7d72df40-6df3-48fa-9cee-0988c9ffac1b)

I attached the two sample files and the Excel file with the expected values.
[files.zip](https://github.com/IFCjs/web-ifc/files/12915882/files.zip)

### Version

0.0.44

### What browsers are you seeing the problem on?

Chrome

**Comment by beachtom** [comment]
Fixed it1

**Comment by andy-wrks** [comment]
Great, thanks! I'll test it when 0.0.45 is released.

**Comment by andy-wrks** [comment]
Tested it today on the new release and got the expected results.
Thanks for fixing :-)
