### ISSUE TITLE
[Question]: WriteRawLine is really really slow on "bigger" models

### ISSUE THREAD

**Issue by quasarchimaere** [IFCjs/web-ifc#507]
### What happened?

i am not sure why it happens but moving from the old web-ifc (i think we had 0.0.36) to web-ifc (0.0.43) writing rawlinedata (which we use to write lines in bulk) became very very slow (18mb ifc file -- we can't share --) takes around 1sec for each writeLine call. This used to be way faster.

Did you change anything in the write Architecture that could have caused this?

I see that with 0.0.44 there is a writeLineS function that only iterates over the lines and calls individual writeRawLines within the js code. only addition is that it is preemptively adding lines.length entries to the wasm line "array", but other than that it is the same.

### Version

0.0.43

**Comment by beachtom** [comment]
It should not be that slow - what exactly are you doing? Are you writing multiple lines? How are you doing it.

**Comment by quasarchimaere** [comment]
```
deletedLineIds: Array<number> //--> lines we want to delete completely
addedLines: Array<RawLine> //--> json object { ID: expressID, type: lineTypeNumber, arguments: ArrayOfArgs based on the correct ToRawLineData function)

deletedLineIds?.forEach((idToDelete) => {
      try {
        ifcApi.DeleteLine(modelID, idToDelete);
      } catch (err) {
        console.error("writeChangedLinesToModel: err", err, " while deleting lineId: ", idToDelete);
      }
    });

    addedLines?.forEach((rawLineData) => {
      try {
        ifcApi.WriteRawLineData(modelID, rawLineData);
      } catch (err) {
        console.error("writeChangedLinesToModel: err", err, " while writing line: ", rawLineData);
      }
    });
```

**Comment by beachtom** [comment]
So I just uploaded a fix that adds a WriteRawLinesData that takes an array of rawLine data. This should mean it will do memory allocation (which I think is what is taking the time once).

If you download from the repository main page the latest download and place it in node_modules/web-ifc you should be able to test it. Can you let me know if it speeds it up at all

**Comment by beachtom** [comment]
so you should be able to call it 

ifcApi.wasmModule.ExtendLineStorage(modelID,numberOfLines)

Its not documented but it should still work - let me know if it does not.
