### ISSUE TITLE
[Bug]: Missing Geometry on Curved Piping with Profiles

### ISSUE THREAD

**Issue by ferictael** [IFCjs/web-ifc#512]
### What happened?

It seems that certain objects refuse to generate geometry, which seem to be focused almost entirely on sections of piping.

We're working on a platform that processes large IFC models of commercial ships which often contain miles of such piping, and while nearly all geometry comes out well, piping seems to be consistently lacking.

As an example: Here's how an IFC file containing only piping comes out of both the online demo and our project
![image](https://github.com/IFCjs/web-ifc/assets/84565546/a3106741-82ef-4566-a027-022a64c0d780)

And here's how it is supposed to look
![image](https://github.com/IFCjs/web-ifc/assets/84565546/78aae64e-79e4-4fc9-b5c8-9ca66f6d8ffd)

The only two features I have been able to identify differentiating these missing sections of piping from others is that they are not straight sections, and/or they contain the Profile property. I cannot say for certain this is the culprit, but it looks like a good clue as to the real cause of this issue.

Image from the properties inspector in BIM Vision on one of the curves pipe sections, for added clarification
![image](https://github.com/IFCjs/web-ifc/assets/84565546/83aa9b60-b6af-415a-93a7-48fb69587e93)

### Version

0.0.44

### What browsers are you seeing the problem on?

Chrome

### Anything else?

The file used in the screenshot examples:
[427.zip](https://github.com/IFCjs/web-ifc/files/13068275/427.zip)

**Comment by QuimMoya** [comment]
![image](https://github.com/IFCjs/web-ifc/assets/12625508/1fe938dc-6bb1-4354-836d-9a63aa9368bc)
Now i have to test that this fix does not break anything else and i will merge it in the main

**Comment by ferictael** [comment]
Thanks for the swift response and (potential) fix! I'll be looking forward to the next release with this fix implemented.
