### ISSUE TITLE
[Bug]: IFCCONVERSIONBASEDUNIT Parsing Faulty

### ISSUE THREAD

**Issue by quasarchimaere** [IFCjs/web-ifc#522]
### What happened?

Having a IFCCONVERSIONBASEDUNIT with an inferred Dimension Vector fails, due to a mixup in the parameters

`#285=IFCCONVERSIONBASEDUNIT(*,.MASSFLOWRATEUNIT.,'Kilogram per Hour',#284);`
-> This line results in the Unit Object having `{type: 3, value: 'Kilogram per Hour'}` as the UnitType Prop and not as the Name Prop (the Name Prop is `{type: 1, value: 284}`) it seems like the infer shifted the parsing to the left, because if you use:
`#285=IFCCONVERSIONBASEDUNIT(#1,.MASSFLOWRATEUNIT.,'Kilogram per Hour',#284);` (non existing line or fault as the dimension vector) it parses the line appropriately

### Version

0.0.43

**Comment by beachtom** [comment]
What version of the schema are you working on. I can't find any information in the schemas we use to show dimensions can be derived?

**Comment by quasarchimaere** [comment]
the file in question (which i sadly can't share) is IFC2X3, so i think the parser uses the FromRawDataLine[1] (in the new web-ifc) and the FromRawDataLine[3] in the old web-ifc (0.0.43)

**Comment by beachtom** [comment]
I still can't track this down. If you can't share the file - can you share just the one troublesome line?

**Comment by fkleedorfer** [comment]
This is the relevant part of the file we use to reproduce the bug:
```
#34=IFCSIUNIT(*,.TIMEUNIT.,$,.SECOND.);
#279=IFCOWNERHISTORY(#275,#277,$,.ADDED.,$,#275,#277,1600);
#280=IFCSIUNIT(*,.MASSUNIT.,$,.GRAM.);
#281=IFCDERIVEDUNITELEMENT(#280,1);
#282=IFCDERIVEDUNITELEMENT(#34,-1);
#283=IFCDERIVEDUNIT((#281,#282),.MASSFLOWRATEUNIT.,$);
#284=IFCMEASUREWITHUNIT(IFCMASSFLOWRATEMEASURE(0.277777778),#283);
#285=IFCCONVERSIONBASEDUNIT(*,.MASSFLOWRATEUNIT.,'Kilogram per Hour',#284);
#286=IFCPROPERTYSINGLEVALUE('Massestrom_kg/h',$,IFCMASSFLOWRATEMEASURE(130),#285);
#287=IFCPROPERTYSET('zdt6AcrEdoV6HJ6FJGtndR',#279,'SI_Einheit',$,(#286));
```

**Comment by beachtom** [comment]
Ok, so in the IFC schema - it does not give any infromation on how the first parameter of IFCconversionbased unit is calculated.

Dimension is defined in IfcNamedUnit:

ENTITY IfcNamedUnit
 ABSTRACT SUPERTYPE OF (ONEOF
	(IfcContextDependentUnit
	,IfcConversionBasedUnit
	,IfcSIUnit));
	Dimensions : IfcDimensionalExponents;
	UnitType : IfcUnitEnum;
 WHERE
	WR1 : IfcCorrectDimensions (SELF.UnitType, SELF.Dimensions);
END_ENTITY;

Whereas if you look at say IfcSIUnit you can see the definition:

ENTITY IfcSIUnit
 SUBTYPE OF (IfcNamedUnit);
	Prefix : OPTIONAL IfcSIPrefix;
	Name : IfcSIUnitName;
 DERIVE
	SELF\IfcNamedUnit.Dimensions : IfcDimensionalExponents := IfcDimensionsForSiUnit (SELF.Name);
END_ENTITY;

So i am not sure that IFCDerivedUnit can have an infered first parameter

**Comment by fkleedorfer** [comment]
Thanks for digging deeper here.

I looked here: https://standards.buildingsmart.org/documents/Implementation/IFC2x_Model_Implementation_Guide_V2-0b.pdf and I cannot find an example there or anywhere else that uses an inferred dimension vector. It seems wasteful - the dimensions must be the same as the base unit's - but that seems to be how it's specified.

**Comment by beachtom** [comment]
I agree - but I don't think we should implement if not in the specification. All our code for handling this is generated automatically from the specs. It would be very difficult to hard code anything in for this. 

I guess the best option is to raise this as a change request with BuildingSMART they may consider it for a future version

**Comment by fkleedorfer** [comment]
It may be worth looking into a more graceful way of handling errors like this, though. 

Using '*' for the dimension vector caused the follwing parameters each to be assigned to the wrong member variable, and thus was harder to debug than necessary as it led to a type error much later when the object was accessed.
