### ISSUE TITLE
[Question]: webifc on a Node environment gives compilation fail error but seems to work correctly

### ISSUE THREAD

**Issue by lukasvdelft** [IFCjs/web-ifc#526]
### What happened?

We are moving the WebIfc.IfcAPI processing to a node-based backend (Azure). Loading a model now gives the following notification "index-699a742b.js:2590 wasm streaming compile failed: TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'."

![Screenshot 2023-11-20 at 11 39 50](https://github.com/IFCjs/web-ifc/assets/103726718/2165a53a-5d18-45ae-92c8-b05eb1720708)

So far it is functioning correctly though. Is there specific configuration we need to add to prevent this compilation fail?

### Version

0.0.39

**Comment by beachtom** [comment]
So this looks like the server is not sending the correct mime type with the WASM file

**Comment by lukasvdelft** [comment]
Thnx Tom
