### ISSUE TITLE
[Bug]: Civil files with file schema IFC4_RC4 header fail

### ISSUE THREAD

**Issue by agviegas** [IFCjs/web-ifc#530]
### What happened?

IFC4 files with the following header line work fine:

`FILE_SCHEMA(('IFC4X3'));`

Nevertheless, when civil files have the following line, they don't load correctly in components FragmentIfcLoader.

`FILE_SCHEMA(('IFC4X3_RC4'));`

This is the header of some files coming from authoring applications, but it can be reproduced simply by manually writing that header in any civil file.

## Steps to reproduce

1. Clone the components repository
2. Open the [FragmentIfcLoader](https://github.com/IFCjs/components/blob/main/src/fragments/FragmentIfcLoader/index.html) example.
3. Open an IFC4 file with the abovementioned header.

### Version

0.0.44

### What browsers are you seeing the problem on?

Chrome

**Comment by agviegas** [comment]
Models available [here](https://drive.google.com/drive/folders/1b5yppMnp-YxJJITpBnu1O7nQOW_lvt0L?usp=sharing)

**Comment by beachtom** [comment]
Fixed
