### ISSUE TITLE
[Bug]: Incorrect normals on some faces

### ISSUE THREAD

**Issue by szamocza** [IFCjs/web-ifc#536]
### What happened?

We have some ifc models in which the normal vector of some elements' face is incorrect.
These errors are not visible in the viewer, at most some artifacts appear in shadows, like #306.
The problem occurs consistently with some many-vertex polygons, but not all cases, even with seemingly identical shapes, produce different results.

For expample:
![image](https://github.com/IFCjs/web-ifc/assets/9346954/826f6754-f55b-4b4e-ab96-2d6a003b296f)

The ifc shape definition has correct definition: polygons, windigs etc.

(Unfortunately, I can't attach a sample because I don't have the right to do so.)

### Version

0.0.47

**Comment by beachtom** [comment]
This is now fixed
