### ISSUE TITLE
[Feat]: Question about Comment

### ISSUE THREAD

**Issue by is0263rf** [IFCjs/web-ifc#539]
### What is your idea?

The comment says "model must not be closed". Is this comment a mistake for "model must be closed"?

https://github.com/IFCjs/web-ifc/blob/234105f91f211fb6cfd8be18616779e73799d77f/src/web-ifc-api.ts#L961-L968

**Comment by beachtom** [comment]
Yes that is confusing! It should read something like model must be closed after use.
