### ISSUE TITLE
[Bug]: `WriteLine` cannot write a new line

### ISSUE THREAD

**Issue by NiklasPor** [IFCjs/web-ifc#541]
### What happened?

It seems like `WriteLine` cannot be used to write new lines, because there's not storage increase before the line type is checked, which then checks if the expressId is in range of the existing lines.

Line 617 call `GetLineType`: 
https://github.com/IFCjs/web-ifc/blob/c3f64efbcfc77d954213f360a46aa352a2dd9573/src/web-ifc-api.ts#L611-L621

Line 286 will lead to an error, because `expressID > _lines.size()` (the size wasn't increased before)
https://github.com/IFCjs/web-ifc/blob/c3f64efbcfc77d954213f360a46aa352a2dd9573/src/wasm/parsing/IfcLoader.cpp#L284-L291

### Version

0.0.46

### What browsers are you seeing the problem on?

Chrome

**Comment by NiklasPor** [comment]
Simple workaround is to extract the `WriteLine` method into your own codespace and only run the checks for type mismatches when the line does not exist.

**Comment by beachtom** [comment]
I will check this out - but you can also not set a express ID on the lineItem object and it will work - but I will fix this in any case

**Comment by NiklasPor** [comment]
Awesome, thanks ❤️

**Comment by beachtom** [comment]
This is now fixed
