### ISSUE TITLE
[Bug]: Heap memory held by `wasmModule` is not disposed for each model

### ISSUE THREAD

**Issue by shota-hamamatsu** [IFCjs/web-ifc#545]
### What happened?

- Even after the model is closed, the vertex of this geometry remain in `wasmModule.HEAPF32`, causing a memory leak.
- Is the heap memory held by wasmModule disposed for each model?

- This issue  is contenued from https://github.com/IFCjs/web-ifc/issues/542

### Version

0.0.39

### What browsers are you seeing the problem on?

Chrome

**Comment by beachtom** [comment]
This should now be fixed as well!

**Comment by beachtom** [comment]
Just to add - that you may need to call delete() on the IfcGeometry object force memory to clear. The underlying EMSCRIPTEN layer will keep it allocated unti it is sure the JS engine is done with it - this forces its clearance
