### ISSUE TITLE
[Bug]: GetNameFromTypeCode from UPPERCASE to PascalCase

### ISSUE THREAD

**Issue by cvillagrasa** [IFCjs/web-ifc#547]
### What happened?

Currently, `ifcAPI.GetNameFromTypeCode(myIfcElement.type)` returns an uppercase string with the IFC class of the element, whereas `myIfcElement.constructor.name` returns a pascal case string. However, the latter can pose some trouble with minification [on downstream libs](https://github.com/xeokit/xeokit-sdk/issues/1185), and going to uppercase is trivial, but not the other way around.

Therefore, is it possible to change `GetNameFromTypeCode` so that it returns `IfcWall` instead of `IFCWALL`?

### Version

0.0.48

**Comment by beachtom** [comment]
So this make sense.... but it may beak lots of other stuff. It is trivial to change, but I will need to investigate what else will break

**Comment by paireks** [comment]
Maybe additional argument set as default=uppercase with ability to switch to pascalcase? Or separate method?

**Comment by beachtom** [comment]
Doesn't seem like this actually breaks too much. I've done it now.
