### ISSUE TITLE
[Docs]: Web IFC loading

### ISSUE THREAD

**Issue by boycce** [IFCjs/web-ifc#548]
### What is your idea?

1. Documentation on what the different bundled files represents, and how each one is used/loaded? E.g. `web-ifc.*`, `web-ifc-mt.*`
2. If possible, add documentation or example on how to setup basic IFC string parsing on the browser without loading a 5MB dependency (`web-ifc-api.js`). Maybe a build guide?

Thanks!

**Comment by beachtom** [comment]
1. Good point, I have added some information to the readme.
2.  That is just not something we support - all of that dependency is needed (most of it is the representation of the IFC schema).

**Comment by boycce** [comment]
Thanks for the reply @beachtom. 

1. Thanks for adding those notes!
2. Okay, I see, so we would need to load both `web-ifc.wasm` and `web-ifc-api.js` in the browser together
