### ISSUE TITLE
[Bug]: IFC4.IfcCartesianPointList2D CoordList 

### ISSUE THREAD

**Issue by sushantc-inode** [IFCjs/web-ifc#572]
### What happened?

While creating a IFCCARTESIANPOINTLIST2D ifc requires a list like IFCCARTESIANPOINTLIST2D(((0.,0.),(1.,0.))) but web-ifc generate a list like IFCCARTESIANPOINTLIST2D((0.,0.,1.,0.));
and same for the IFCCARTESIANPOINTLIST3D 

I solved this problem in my local by changing 

 class IfcCartesianPointList2D extends IfcCartesianPointList {
        CoordList: IfcLengthMeasure[];
        type: number;
        constructor(CoordList: IfcLengthMeasure[]);
    }
    class IfcCartesianPointList3D extends IfcCartesianPointList {
        CoordList: IfcLengthMeasure[];
        type: number;
        constructor(CoordList: IfcLengthMeasure[]);
    }

to 

 class IfcCartesianPointList2D extends IfcCartesianPointList {
        CoordList: IfcLengthMeasure[][];
        type: number;
        constructor(CoordList: IfcLengthMeasure[][]);
    }
    class IfcCartesianPointList3D extends IfcCartesianPointList {
        CoordList: IfcLengthMeasure[][];
        type: number;
        constructor(CoordList: IfcLengthMeasure[][]);
    }

### Version

0.0.50

**Comment by beachtom** [comment]
Can you share the code as to how you are generating these points?

**Comment by sushantc-inode** [comment]
> Can you share the code as to how you are generating these points?


For IfcCartesianPointList2D:
```
[
     [ new IFC4.IfcLengthMeasure(x), new IFC4.IfcLengthMeasure(y) ],
     [ new IFC4.IfcLengthMeasure(x), new IFC4.IfcLengthMeasure(y) ]
]
```

For IfcCartesianPointList3D :
```
[
    [ new IFC4.IfcLengthMeasure(x), new IFC4.IfcLengthMeasure(y), new IFC4.IfcLengthMeasure(z) ],
    [ new IFC4.IfcLengthMeasure(x), new IFC4.IfcLengthMeasure(y), new IFC4.IfcLengthMeasure(z) ]
]
```

**Comment by beachtom** [comment]
This should now be fixed!
