### ISSUE TITLE
[Feat]: refactor `Vector<T>` to a class that implements the `Iterable<T>` interface

### ISSUE THREAD

**Issue by oxcabe** [IFCjs/web-ifc#578]
## Description

The following interface:
https://github.com/IFCjs/web-ifc/blob/b55d8bde10067415d4536b23c27edcc13acf217c/src/web-ifc-api.ts#L80-L83

Cannot be iterated nor destructured, since it is not an [Iterable](https://www.typescriptlang.org/docs/handbook/iterators-and-generators.html#iterable-interface). I propose refactoring the interface into a generic class  that implements the `Iterable<T>` interface.

## Alternatives

Use native `Array<T>` structures instead. If there is a reason for not doing so, someone please explain it here to have a better understanding of the design choice.

**EDIT**: The explanation is that, when C++ functions like
https://github.com/IFCjs/web-ifc/blob/b55d8bde10067415d4536b23c27edcc13acf217c/src/wasm/web-ifc-api.cpp#L259
are passed to JavaScript, they expose `{"get", "size", "push_back", "resize", "set"}` methods, thus making it directly incompatible with `Array<T>`.

(from: https://stackoverflow.com/a/35564995)

**Comment by beachtom** [comment]
This always struck me as odd - the reason I never changed it is I did not want to add an iteration to the vectors that come from C++ slowing things down - but there may be a way around it let me think on it

**Comment by oxcabe** [comment]
In that case, an approach we can follow is to support both. E.g:

```
VectorLike<T> = Vector<T> | IterableVector<T>  // Return this instead of Vector<T>

interface Vector<T> { ... }  // Stays the same

interface IterableVector<T> implements Iterable<T> { ... }  // Less efficient iterable vector which could be compatible with Array<T>
```

Pros:
* The API does not add breaking changes.
* It does not affect performance, since it's a compile-time check and `Vector<T>` is still an option.
* Developers can now use a compatible iterable structure on their side if they want to.

Cons:
* The code-base is slightly more complex since we add two new types.

What's your opinion on this?

**Comment by beachtom** [comment]
OK I've managed to find a way to do it without breaking the interface - so this should work now.

**Comment by oxcabe** [comment]
Thank you for the quick resolution!
